package pe.gob.mef.gescon.hibernate.domain;
// Generated 10/09/2015 10:47:32 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;


/**
 * Mtmaestro generated by hbm2java
 */
public class Mtalerta implements java.io.Serializable {

    private BigDecimal nalertaid;
    private String vnombre;
    private String vdescripcion;
    private String vusuariocreacion;
    private Date dfechacreacion;
    private String vusuariomodificacion;
    private Date dfechamodificacion;
    private BigDecimal nactivo;
    private BigDecimal nuseraplica;
    private BigDecimal nparametroid;
    private Date dfechini;
    private Date dfechfin;
    private String ncondicion1;
    private String ncondicion2;
    private BigDecimal nvalor1;
    private BigDecimal ntipo1;
    private BigDecimal nvalor2;
    private BigDecimal ntipo2;

    public Mtalerta() {
    }

    public Mtalerta(BigDecimal nalertaid) {
        this.nalertaid = nalertaid;
    }

    public Mtalerta(BigDecimal nalertaid, String vnombre, String vdescripcion, String vusuariocreacion, Date dfechacreacion, String vusuariomodificacion, Date dfechamodificacion, BigDecimal nactivo, BigDecimal nuseraplica, BigDecimal nparametroid, Date dfechini, Date dfechfin, String ncondicion1, String ncondicion2, BigDecimal nvalor1, BigDecimal ntipo1, BigDecimal nvalor2, BigDecimal ntipo2) {
        this.nalertaid = nalertaid;
        this.vnombre = vnombre;
        this.vdescripcion = vdescripcion;
        this.vusuariocreacion = vusuariocreacion;
        this.dfechacreacion = dfechacreacion;
        this.vusuariomodificacion = vusuariomodificacion;
        this.dfechamodificacion = dfechamodificacion;
        this.nactivo = nactivo;
        this.nuseraplica = nuseraplica;
        this.nparametroid = nparametroid;
        this.dfechini = dfechini;
        this.dfechfin = dfechfin;
        this.ncondicion1 = ncondicion1;
        this.ncondicion2 = ncondicion2;
        this.nvalor1 = nvalor1;
        this.ntipo1 = ntipo1;
        this.nvalor2 = nvalor2;
        this.ntipo2 = ntipo2;
    }

    public BigDecimal getNalertaid() {
        return this.nalertaid;
    }

    public void setNalertaid(BigDecimal nalertaid) {
        this.nalertaid = nalertaid;
    }

    public String getVnombre() {
        return this.vnombre;
    }

    public void setVnombre(String vnombre) {
        this.vnombre = vnombre;
    }

    public String getVdescripcion() {
        return this.vdescripcion;
    }

    public void setVdescripcion(String vdescripcion) {
        this.vdescripcion = vdescripcion;
    }

    public String getVusuariocreacion() {
        return this.vusuariocreacion;
    }

    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }

    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    public String getVusuariomodificacion() {
        return this.vusuariomodificacion;
    }

    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }

    public Date getDfechamodificacion() {
        return this.dfechamodificacion;
    }

    public void setDfechamodificacion(Date dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }
    
    public BigDecimal getNactivo() {
        return this.nactivo;
    }
    
    public void setNactivo(BigDecimal nactivo) {
        this.nactivo = nactivo;
    }

    /**
     * @return the nuseraplica
     */
    public BigDecimal getNuseraplica() {
        return nuseraplica;
    }

    /**
     * @param nuseraplica the nuseraplica to set
     */
    public void setNuseraplica(BigDecimal nuseraplica) {
        this.nuseraplica = nuseraplica;
    }

    /**
     * @return the nparametroid
     */
    public BigDecimal getNparametroid() {
        return nparametroid;
    }

    /**
     * @param nparametroid the nparametroid to set
     */
    public void setNparametroid(BigDecimal nparametroid) {
        this.nparametroid = nparametroid;
    }

    /**
     * @return the dfechini
     */
    public Date getDfechini() {
        return dfechini;
    }

    /**
     * @param dfechini the dfechini to set
     */
    public void setDfechini(Date dfechini) {
        this.dfechini = dfechini;
    }

    /**
     * @return the dfechfin
     */
    public Date getDfechfin() {
        return dfechfin;
    }

    /**
     * @param dfechfin the dfechfin to set
     */
    public void setDfechfin(Date dfechfin) {
        this.dfechfin = dfechfin;
    }

    /**
     * @return the ncondicion1
     */
    public String getNcondicion1() {
        return ncondicion1;
    }

    /**
     * @param ncondicion1 the ncondicion1 to set
     */
    public void setNcondicion1(String ncondicion1) {
        this.ncondicion1 = ncondicion1;
    }

    /**
     * @return the ncondicion2
     */
    public String getNcondicion2() {
        return ncondicion2;
    }

    /**
     * @param ncondicion2 the ncondicion2 to set
     */
    public void setNcondicion2(String ncondicion2) {
        this.ncondicion2 = ncondicion2;
    }

    /**
     * @return the nvalor1
     */
    public BigDecimal getNvalor1() {
        return nvalor1;
    }

    /**
     * @param nvalor1 the nvalor1 to set
     */
    public void setNvalor1(BigDecimal nvalor1) {
        this.nvalor1 = nvalor1;
    }

    /**
     * @return the ntipo1
     */
    public BigDecimal getNtipo1() {
        return ntipo1;
    }

    /**
     * @param ntipo1 the ntipo1 to set
     */
    public void setNtipo1(BigDecimal ntipo1) {
        this.ntipo1 = ntipo1;
    }

    /**
     * @return the nvalor2
     */
    public BigDecimal getNvalor2() {
        return nvalor2;
    }

    /**
     * @param nvalor2 the nvalor2 to set
     */
    public void setNvalor2(BigDecimal nvalor2) {
        this.nvalor2 = nvalor2;
    }

    /**
     * @return the ntipo2
     */
    public BigDecimal getNtipo2() {
        return ntipo2;
    }

    /**
     * @param ntipo2 the ntipo2 to set
     */
    public void setNtipo2(BigDecimal ntipo2) {
        this.ntipo2 = ntipo2;
    }
}
