package pe.gob.mef.gescon.hibernate.domain;
// Generated 06/11/2015 11:03:52 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Mtalerta generated by hbm2java
 */
public class Mtalerta  implements java.io.Serializable {


     private BigDecimal nalertaid;
     private Mtparametro mtparametro;
     private String vnombre;
     private String vdescripcion;
     private BigDecimal nactivo;
     private BigDecimal nuseraplica;
     private Date dfechini;
     private Date dfechfin;
     private String vcondicion1;
     private String vcondicion2;
     private BigDecimal nvalor1;
     private BigDecimal nvalor2;
     private BigDecimal ntipo1;
     private BigDecimal ntipo2;
     private String vusuariocreacion;
     private String vusuariomodificacion;
     private Date dfechacreacion;
     private Date dfechamodificacion;

    public Mtalerta() {
    }

	
    public Mtalerta(BigDecimal nalertaid, Mtparametro mtparametro) {
        this.nalertaid = nalertaid;
        this.mtparametro = mtparametro;
    }
    public Mtalerta(BigDecimal nalertaid, Mtparametro mtparametro, String vnombre, String vdescripcion, BigDecimal nactivo, BigDecimal nuseraplica, Date dfechini, Date dfechfin, String vcondicion1, String vcondicion2, BigDecimal nvalor1, BigDecimal nvalor2, BigDecimal ntipo1, BigDecimal ntipo2, String vusuariocreacion, String vusuariomodificacion, Date dfechacreacion, Date dfechamodificacion) {
       this.nalertaid = nalertaid;
       this.mtparametro = mtparametro;
       this.vnombre = vnombre;
       this.vdescripcion = vdescripcion;
       this.nactivo = nactivo;
       this.nuseraplica = nuseraplica;
       this.dfechini = dfechini;
       this.dfechfin = dfechfin;
       this.vcondicion1 = vcondicion1;
       this.vcondicion2 = vcondicion2;
       this.nvalor1 = nvalor1;
       this.nvalor2 = nvalor2;
       this.ntipo1 = ntipo1;
       this.ntipo2 = ntipo2;
       this.vusuariocreacion = vusuariocreacion;
       this.vusuariomodificacion = vusuariomodificacion;
       this.dfechacreacion = dfechacreacion;
       this.dfechamodificacion = dfechamodificacion;
    }
   
    public BigDecimal getNalertaid() {
        return this.nalertaid;
    }
    
    public void setNalertaid(BigDecimal nalertaid) {
        this.nalertaid = nalertaid;
    }
    public Mtparametro getMtparametro() {
        return this.mtparametro;
    }
    
    public void setMtparametro(Mtparametro mtparametro) {
        this.mtparametro = mtparametro;
    }
    public String getVnombre() {
        return this.vnombre;
    }
    
    public void setVnombre(String vnombre) {
        this.vnombre = vnombre;
    }
    public String getVdescripcion() {
        return this.vdescripcion;
    }
    
    public void setVdescripcion(String vdescripcion) {
        this.vdescripcion = vdescripcion;
    }
    public BigDecimal getNactivo() {
        return this.nactivo;
    }
    
    public void setNactivo(BigDecimal nactivo) {
        this.nactivo = nactivo;
    }
    public BigDecimal getNuseraplica() {
        return this.nuseraplica;
    }
    
    public void setNuseraplica(BigDecimal nuseraplica) {
        this.nuseraplica = nuseraplica;
    }
    public Date getDfechini() {
        return this.dfechini;
    }
    
    public void setDfechini(Date dfechini) {
        this.dfechini = dfechini;
    }
    public Date getDfechfin() {
        return this.dfechfin;
    }
    
    public void setDfechfin(Date dfechfin) {
        this.dfechfin = dfechfin;
    }
    public String getVcondicion1() {
        return this.vcondicion1;
    }
    
    public void setVcondicion1(String vcondicion1) {
        this.vcondicion1 = vcondicion1;
    }
    public String getVcondicion2() {
        return this.vcondicion2;
    }
    
    public void setVcondicion2(String vcondicion2) {
        this.vcondicion2 = vcondicion2;
    }
    public BigDecimal getNvalor1() {
        return this.nvalor1;
    }
    
    public void setNvalor1(BigDecimal nvalor1) {
        this.nvalor1 = nvalor1;
    }
    public BigDecimal getNvalor2() {
        return this.nvalor2;
    }
    
    public void setNvalor2(BigDecimal nvalor2) {
        this.nvalor2 = nvalor2;
    }
    public BigDecimal getNtipo1() {
        return this.ntipo1;
    }
    
    public void setNtipo1(BigDecimal ntipo1) {
        this.ntipo1 = ntipo1;
    }
    public BigDecimal getNtipo2() {
        return this.ntipo2;
    }
    
    public void setNtipo2(BigDecimal ntipo2) {
        this.ntipo2 = ntipo2;
    }
    public String getVusuariocreacion() {
        return this.vusuariocreacion;
    }
    
    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }
    public String getVusuariomodificacion() {
        return this.vusuariomodificacion;
    }
    
    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }
    public Serializable getDfechacreacion() {
        return this.dfechacreacion;
    }
    
    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }
    public Serializable getDfechamodificacion() {
        return this.dfechamodificacion;
    }
    
    public void setDfechamodificacion(Date dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }




}


