package pe.gob.mef.gescon.hibernate.domain;
// Generated 11/09/2015 05:20:07 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mtcategoria generated by hbm2java
 */
public class Mtcategoria implements java.io.Serializable {

    private BigDecimal ncategoriaid;
    private String vdescripcion;
    private BigDecimal nestado;
    private BigDecimal ncategoriasup;
    private BigDecimal nnivel;
    private String vnombre;
    private String vusuariomod;
    private String vusuariocreacion;
    private Date dfechacreacion;
    private Date dfechamod;
    private BigDecimal nflagwiki;
    private BigDecimal nflagbl;
    private BigDecimal nflagpr;
    private BigDecimal nflagct;
    private BigDecimal nflagbp;
    private BigDecimal nflagom;
    private Blob bimagen;
    private String vimagennombre;
    private String vespecialista;
    private String vmoderador;
    private Set<TcategoriaConocimiento> tcategoriaConocimientos = new HashSet<TcategoriaConocimiento>(0);

    public Mtcategoria() {
    }

    public Mtcategoria(BigDecimal ncategoriaid) {
        this.ncategoriaid = ncategoriaid;
    }

    public Mtcategoria(BigDecimal ncategoriaid, String vdescripcion, BigDecimal nestado, BigDecimal ncategoriasup, BigDecimal nnivel, String vnombre, String vusuariomod, String vusuariocreacion, Date dfechacreacion, Date dfechamod, BigDecimal nflagwiki, BigDecimal nflagbl, BigDecimal nflagpr, BigDecimal nflagct, BigDecimal nflagbp, BigDecimal nflagom, Blob bimagen, String vimagennombre, String vespecialista, String vmoderador, Set<TcategoriaConocimiento> tcategoriaConocimientos) {
        this.ncategoriaid = ncategoriaid;
        this.vdescripcion = vdescripcion;
        this.nestado = nestado;
        this.ncategoriasup = ncategoriasup;
        this.nnivel = nnivel;
        this.vnombre = vnombre;
        this.vusuariomod = vusuariomod;
        this.vusuariocreacion = vusuariocreacion;
        this.dfechacreacion = dfechacreacion;
        this.dfechamod = dfechamod;
        this.nflagwiki = nflagwiki;
        this.nflagbl = nflagbl;
        this.nflagpr = nflagpr;
        this.nflagct = nflagct;
        this.nflagbp = nflagbp;
        this.nflagom = nflagom;
        this.bimagen = bimagen;
        this.vimagennombre = vimagennombre;
        this.vespecialista = vespecialista;
        this.vmoderador = vmoderador;
        this.tcategoriaConocimientos = tcategoriaConocimientos;
    }

    public BigDecimal getNcategoriaid() {
        return this.ncategoriaid;
    }

    public void setNcategoriaid(BigDecimal ncategoriaid) {
        this.ncategoriaid = ncategoriaid;
    }

    public String getVdescripcion() {
        return this.vdescripcion;
    }

    public void setVdescripcion(String vdescripcion) {
        this.vdescripcion = vdescripcion;
    }

    public BigDecimal getNestado() {
        return this.nestado;
    }

    public void setNestado(BigDecimal nestado) {
        this.nestado = nestado;
    }

    public BigDecimal getNcategoriasup() {
        return this.ncategoriasup;
    }

    public void setNcategoriasup(BigDecimal ncategoriasup) {
        this.ncategoriasup = ncategoriasup;
    }

    public BigDecimal getNnivel() {
        return this.nnivel;
    }

    public void setNnivel(BigDecimal nnivel) {
        this.nnivel = nnivel;
    }

    public String getVnombre() {
        return this.vnombre;
    }

    public void setVnombre(String vnombre) {
        this.vnombre = vnombre;
    }

    public String getVusuariomod() {
        return this.vusuariomod;
    }

    public void setVusuariomod(String vusuariomod) {
        this.vusuariomod = vusuariomod;
    }

    public String getVusuariocreacion() {
        return this.vusuariocreacion;
    }

    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }

    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    public Date getDfechamod() {
        return this.dfechamod;
    }

    public void setDfechamod(Date dfechamod) {
        this.dfechamod = dfechamod;
    }

    public BigDecimal getNflagwiki() {
        return this.nflagwiki;
    }

    public void setNflagwiki(BigDecimal nflagwiki) {
        this.nflagwiki = nflagwiki;
    }

    public BigDecimal getNflagbl() {
        return this.nflagbl;
    }

    public void setNflagbl(BigDecimal nflagbl) {
        this.nflagbl = nflagbl;
    }

    public BigDecimal getNflagpr() {
        return this.nflagpr;
    }

    public void setNflagpr(BigDecimal nflagpr) {
        this.nflagpr = nflagpr;
    }

    public BigDecimal getNflagct() {
        return this.nflagct;
    }

    public void setNflagct(BigDecimal nflagct) {
        this.nflagct = nflagct;
    }

    public BigDecimal getNflagbp() {
        return this.nflagbp;
    }

    public void setNflagbp(BigDecimal nflagbp) {
        this.nflagbp = nflagbp;
    }

    public BigDecimal getNflagom() {
        return this.nflagom;
    }

    public void setNflagom(BigDecimal nflagom) {
        this.nflagom = nflagom;
    }

    /**
     * @return the bimagen
     */
    public Blob getBimagen() {
        return bimagen;
    }

    /**
     * @param bimagen the bimagen to set
     */
    public void setBimagen(Blob bimagen) {
        this.bimagen = bimagen;
    }

    /**
     * @return the vimagennombre
     */
    public String getVimagennombre() {
        return vimagennombre;
    }

    /**
     * @param vimagennombre the vimagennombre to set
     */
    public void setVimagennombre(String vimagennombre) {
        this.vimagennombre = vimagennombre;
    }

    public String getVespecialista() {
        return vespecialista;
    }

    public void setVespecialista(String vespecialista) {
        this.vespecialista = vespecialista;
    }

    public String getVmoderador() {
        return vmoderador;
    }

    public void setVmoderador(String vmoderador) {
        this.vmoderador = vmoderador;
    }

    public Set<TcategoriaConocimiento> getTcategoriaConocimientos() {
        return this.tcategoriaConocimientos;
    }

    public void setTcategoriaConocimientos(Set<TcategoriaConocimiento> tcategoriaConocimientos) {
        this.tcategoriaConocimientos = tcategoriaConocimientos;
    }

}
