package pe.gob.mef.gescon.hibernate.domain;
// Generated 11/09/2015 05:20:07 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mtmaestro generated by hbm2java
 */
public class Mtmaestro  implements java.io.Serializable {


     private BigDecimal nmaestroid;
     private String vnombre;
     private String vdescripcion;
     private String vusucrea;
     private Date dfechcrea;
     private String vusumod;
     private Date dfechmod;
     private BigDecimal nactivo;
     private Set<Tmaestrodetalle> tmaestrodetalles = new HashSet<Tmaestrodetalle>(0);

    public Mtmaestro() {
    }

	
    public Mtmaestro(BigDecimal nmaestroid) {
        this.nmaestroid = nmaestroid;
    }
    public Mtmaestro(BigDecimal nmaestroid, String vnombre, String vdescripcion, String vusucrea, Date dfechcrea, String vusumod, Date dfechmod, BigDecimal nactivo, Set<Tmaestrodetalle> tmaestrodetalles) {
       this.nmaestroid = nmaestroid;
       this.vnombre = vnombre;
       this.vdescripcion = vdescripcion;
       this.vusucrea = vusucrea;
       this.dfechcrea = dfechcrea;
       this.vusumod = vusumod;
       this.dfechmod = dfechmod;
       this.nactivo = nactivo;
       this.tmaestrodetalles = tmaestrodetalles;
    }
   
    public BigDecimal getNmaestroid() {
        return this.nmaestroid;
    }
    
    public void setNmaestroid(BigDecimal nmaestroid) {
        this.nmaestroid = nmaestroid;
    }
    public String getVnombre() {
        return this.vnombre;
    }
    
    public void setVnombre(String vnombre) {
        this.vnombre = vnombre;
    }
    public String getVdescripcion() {
        return this.vdescripcion;
    }
    
    public void setVdescripcion(String vdescripcion) {
        this.vdescripcion = vdescripcion;
    }
    public String getVusucrea() {
        return this.vusucrea;
    }
    
    public void setVusucrea(String vusucrea) {
        this.vusucrea = vusucrea;
    }
    public Date getDfechcrea() {
        return this.dfechcrea;
    }
    
    public void setDfechcrea(Date dfechcrea) {
        this.dfechcrea = dfechcrea;
    }
    public String getVusumod() {
        return this.vusumod;
    }
    
    public void setVusumod(String vusumod) {
        this.vusumod = vusumod;
    }
    public Date getDfechmod() {
        return this.dfechmod;
    }
    
    public void setDfechmod(Date dfechmod) {
        this.dfechmod = dfechmod;
    }
    public BigDecimal getNactivo() {
        return this.nactivo;
    }
    
    public void setNactivo(BigDecimal nactivo) {
        this.nactivo = nactivo;
    }
    public Set<Tmaestrodetalle> getTmaestrodetalles() {
        return this.tmaestrodetalles;
    }
    
    public void setTmaestrodetalles(Set<Tmaestrodetalle> tmaestrodetalles) {
        this.tmaestrodetalles = tmaestrodetalles;
    }




}


