package pe.gob.mef.gescon.hibernate.domain;
// Generated 10/09/2015 10:47:32 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;


/**
 * Mtmaestro generated by hbm2java
 */
public class Mtparametro implements java.io.Serializable {

    private BigDecimal nparametroid;
    private String vnombre;
    private BigDecimal vvalor;
    private String vdescripcion;
    private String vusuariocreacion;
    private Date dfechacreacion;
    private String vusuariomodificacion;
    private Date dfechamodificacion;
    private BigDecimal nactivo;
    

    public Mtparametro() {
    }

    public Mtparametro(BigDecimal nparametroid) {
        this.nparametroid = nparametroid;
    }

    public Mtparametro(BigDecimal nparametroid, String vnombre, BigDecimal vvalor, String vdescripcion, String vusuariocreacion, Date dfechacreacion, String vusuariomodificacion, Date dfechamodificacion, BigDecimal nactivo) {
        this.nparametroid = nparametroid;
        this.vnombre = vnombre;
        this.vvalor= vvalor;
        this.vdescripcion = vdescripcion;
        this.vusuariocreacion = vusuariocreacion;
        this.dfechacreacion = dfechacreacion;
        this.vusuariomodificacion = vusuariomodificacion;
        this.dfechamodificacion = dfechamodificacion;
        this.nactivo = nactivo;
        
    }

    public BigDecimal getNparametroid() {
        return this.nparametroid;
    }

    public void setNparametroid(BigDecimal nparametroid) {
        this.nparametroid = nparametroid;
    }

    public String getVnombre() {
        return this.vnombre;
    }

    public void setVnombre(String vnombre) {
        this.vnombre = vnombre;
    }
    
    public BigDecimal getVvalor() {
        return this.vvalor;
    }

    public void setVvalor(BigDecimal vvalor) {
        this.vvalor = vvalor;
    }

    public String getVdescripcion() {
        return this.vdescripcion;
    }

    public void setVdescripcion(String vdescripcion) {
        this.vdescripcion = vdescripcion;
    }

    public String getVusuariocreacion() {
        return this.vusuariocreacion;
    }

    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }

    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    public String getVusuariomodificacion() {
        return this.vusuariomodificacion;
    }

    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }

    public Date getDfechamodificacion() {
        return this.dfechamodificacion;
    }

    public void setDfechamodificacion(Date dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }
    
    public BigDecimal getNactivo() {
        return this.nactivo;
    }
    
    public void setNactivo(BigDecimal nactivo) {
        this.nactivo = nactivo;
    }

}
