package pe.gob.mef.gescon.hibernate.domain;
// Generated 11/09/2015 05:20:07 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mtperfil generated by hbm2java
 */
public class Mtperfil  implements java.io.Serializable {


     private BigDecimal nperfilid;
     private String vdescripcion;
     private Character nestado;
     private BigDecimal nusuariomod;
     private BigDecimal nusuariocreacion;
     private Date dfechacreacion;
     private Set<TpoliticaPerfil> tpoliticaPerfils = new HashSet<TpoliticaPerfil>(0);
     private Set<TuserPerfil> tuserPerfils = new HashSet<TuserPerfil>(0);

    public Mtperfil() {
    }

	
    public Mtperfil(BigDecimal nperfilid) {
        this.nperfilid = nperfilid;
    }
    public Mtperfil(BigDecimal nperfilid, String vdescripcion, Character nestado, BigDecimal nusuariomod, BigDecimal nusuariocreacion, Date dfechacreacion, Set<TpoliticaPerfil> tpoliticaPerfils, Set<TuserPerfil> tuserPerfils) {
       this.nperfilid = nperfilid;
       this.vdescripcion = vdescripcion;
       this.nestado = nestado;
       this.nusuariomod = nusuariomod;
       this.nusuariocreacion = nusuariocreacion;
       this.dfechacreacion = dfechacreacion;
       this.tpoliticaPerfils = tpoliticaPerfils;
       this.tuserPerfils = tuserPerfils;
    }
   
    public BigDecimal getNperfilid() {
        return this.nperfilid;
    }
    
    public void setNperfilid(BigDecimal nperfilid) {
        this.nperfilid = nperfilid;
    }
    public String getVdescripcion() {
        return this.vdescripcion;
    }
    
    public void setVdescripcion(String vdescripcion) {
        this.vdescripcion = vdescripcion;
    }
    public Character getNestado() {
        return this.nestado;
    }
    
    public void setNestado(Character nestado) {
        this.nestado = nestado;
    }
    public BigDecimal getNusuariomod() {
        return this.nusuariomod;
    }
    
    public void setNusuariomod(BigDecimal nusuariomod) {
        this.nusuariomod = nusuariomod;
    }
    public BigDecimal getNusuariocreacion() {
        return this.nusuariocreacion;
    }
    
    public void setNusuariocreacion(BigDecimal nusuariocreacion) {
        this.nusuariocreacion = nusuariocreacion;
    }
    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }
    
    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }
    public Set<TpoliticaPerfil> getTpoliticaPerfils() {
        return this.tpoliticaPerfils;
    }
    
    public void setTpoliticaPerfils(Set<TpoliticaPerfil> tpoliticaPerfils) {
        this.tpoliticaPerfils = tpoliticaPerfils;
    }
    public Set<TuserPerfil> getTuserPerfils() {
        return this.tuserPerfils;
    }
    
    public void setTuserPerfils(Set<TuserPerfil> tuserPerfils) {
        this.tuserPerfils = tuserPerfils;
    }




}


