package pe.gob.mef.gescon.hibernate.domain;
// Generated 06/11/2015 11:03:52 AM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mtperfil generated by hbm2java
 */
public class Mtperfil implements java.io.Serializable {

    private BigDecimal nperfilid;
    private BigDecimal nactivo;
    private String vusuariomodificacion;
    private String vusuariocreacion;
    private Date dfechacreacion;
    private Date dfechamodificacion;
    private String vdescripcion;
    private String vnombre;
    private String vdescripcion1232;
    private String vdescripcion1234;
    private String vdescripcion1236;
    private String vdescripcion1238;
    private Set tpoliticaPerfils = new HashSet(0);
    private Set tuserPerfils = new HashSet(0);

    public Mtperfil() {
    }

    public Mtperfil(BigDecimal nperfilid) {
        this.nperfilid = nperfilid;
    }

    public Mtperfil(BigDecimal nperfilid, BigDecimal nactivo, String vusuariomodificacion, String vusuariocreacion, Date dfechacreacion, Date dfechamodificacion, String vdescripcion, String vnombre, String vdescripcion1232, String vdescripcion1234, String vdescripcion1236, String vdescripcion1238, Set tpoliticaPerfils, Set tuserPerfils) {
        this.nperfilid = nperfilid;
        this.nactivo = nactivo;
        this.vusuariomodificacion = vusuariomodificacion;
        this.vusuariocreacion = vusuariocreacion;
        this.dfechacreacion = dfechacreacion;
        this.dfechamodificacion = dfechamodificacion;
        this.vdescripcion = vdescripcion;
        this.vnombre = vnombre;
        this.vdescripcion1232 = vdescripcion1232;
        this.vdescripcion1234 = vdescripcion1234;
        this.vdescripcion1236 = vdescripcion1236;
        this.vdescripcion1238 = vdescripcion1238;
        this.tpoliticaPerfils = tpoliticaPerfils;
        this.tuserPerfils = tuserPerfils;
    }

    public BigDecimal getNperfilid() {
        return this.nperfilid;
    }

    public void setNperfilid(BigDecimal nperfilid) {
        this.nperfilid = nperfilid;
    }

    public BigDecimal getNactivo() {
        return this.nactivo;
    }

    public void setNactivo(BigDecimal nactivo) {
        this.nactivo = nactivo;
    }

    public String getVusuariomodificacion() {
        return this.vusuariomodificacion;
    }

    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }

    public String getVusuariocreacion() {
        return this.vusuariocreacion;
    }

    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }

    public Serializable getDfechacreacion() {
        return this.dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    public Serializable getDfechamodificacion() {
        return this.dfechamodificacion;
    }

    public void setDfechamodificacion(Date dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }

    public String getVdescripcion() {
        return this.vdescripcion;
    }

    public void setVdescripcion(String vdescripcion) {
        this.vdescripcion = vdescripcion;
    }

    public String getVnombre() {
        return this.vnombre;
    }

    public void setVnombre(String vnombre) {
        this.vnombre = vnombre;
    }

    public String getVdescripcion1232() {
        return this.vdescripcion1232;
    }

    public void setVdescripcion1232(String vdescripcion1232) {
        this.vdescripcion1232 = vdescripcion1232;
    }

    public String getVdescripcion1234() {
        return this.vdescripcion1234;
    }

    public void setVdescripcion1234(String vdescripcion1234) {
        this.vdescripcion1234 = vdescripcion1234;
    }

    public String getVdescripcion1236() {
        return this.vdescripcion1236;
    }

    public void setVdescripcion1236(String vdescripcion1236) {
        this.vdescripcion1236 = vdescripcion1236;
    }

    public String getVdescripcion1238() {
        return this.vdescripcion1238;
    }

    public void setVdescripcion1238(String vdescripcion1238) {
        this.vdescripcion1238 = vdescripcion1238;
    }

    public Set getTpoliticaPerfils() {
        return this.tpoliticaPerfils;
    }

    public void setTpoliticaPerfils(Set tpoliticaPerfils) {
        this.tpoliticaPerfils = tpoliticaPerfils;
    }

    public Set getTuserPerfils() {
        return this.tuserPerfils;
    }

    public void setTuserPerfils(Set tuserPerfils) {
        this.tuserPerfils = tuserPerfils;
    }

}
