package pe.gob.mef.gescon.hibernate.domain;
// Generated 11/09/2015 05:20:07 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mtperfil generated by hbm2java
 */
public class Mtperfil implements java.io.Serializable {

    private BigDecimal nperfilid;
    private String vnombre;
    private String vdescripcion;
    private BigDecimal nactivo;
    private String vusuariomodificacion;
    private String vusuariocreacion;
    private Date dfechacreacion;
    private Set<TpoliticaPerfil> tpoliticaPerfils = new HashSet<TpoliticaPerfil>(0);
    private Set<TuserPerfil> tuserPerfils = new HashSet<TuserPerfil>(0);

    public Mtperfil() {
    }

    public Mtperfil(BigDecimal nperfilid) {
        this.nperfilid = nperfilid;
    }

    public Mtperfil(BigDecimal nperfilid, String vnombre, String vdescripcion, BigDecimal nactivo, String vusuariomodificacion, String vusuariocreacion, Date dfechacreacion, Set<TpoliticaPerfil> tpoliticaPerfils, Set<TuserPerfil> tuserPerfils) {
        this.nperfilid = nperfilid;
        this.vnombre = vnombre;
        this.vdescripcion = vdescripcion;
        this.nactivo = nactivo;
        this.vusuariomodificacion = vusuariomodificacion;
        this.vusuariocreacion = vusuariocreacion;
        this.dfechacreacion = dfechacreacion;
        this.tpoliticaPerfils = tpoliticaPerfils;
        this.tuserPerfils = tuserPerfils;
    }

    public BigDecimal getNperfilid() {
        return this.nperfilid;
    }

    public void setNperfilid(BigDecimal nperfilid) {
        this.nperfilid = nperfilid;
    }

    /**
     * @return the vnombre
     */
    public String getVnombre() {
        return vnombre;
    }

    /**
     * @param vnombre the vnombre to set
     */
    public void setVnombre(String vnombre) {
        this.vnombre = vnombre;
    }

    public String getVdescripcion() {
        return this.vdescripcion;
    }

    public void setVdescripcion(String vdescripcion) {
        this.vdescripcion = vdescripcion;
    }

    public BigDecimal getNactivo() {
        return this.nactivo;
    }

    public void setNactivo(BigDecimal nactivo) {
        this.nactivo = nactivo;
    }

    public String getVusuariomodificacion() {
        return this.vusuariomodificacion;
    }

    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }

    public String getVusuariocreacion() {
        return this.vusuariocreacion;
    }

    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }

    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    public Set<TpoliticaPerfil> getTpoliticaPerfils() {
        return this.tpoliticaPerfils;
    }

    public void setTpoliticaPerfils(Set<TpoliticaPerfil> tpoliticaPerfils) {
        this.tpoliticaPerfils = tpoliticaPerfils;
    }

    public Set<TuserPerfil> getTuserPerfils() {
        return this.tuserPerfils;
    }

    public void setTuserPerfils(Set<TuserPerfil> tuserPerfils) {
        this.tuserPerfils = tuserPerfils;
    }

}
