package pe.gob.mef.gescon.hibernate.domain;
// Generated 11/09/2015 05:20:07 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mtpolitica generated by hbm2java
 */
public class Mtpolitica implements java.io.Serializable {

    private BigDecimal npoliticaid;
    private String vnombre;
    private String vdescripcion;
    private BigDecimal nactivo;
    private String vusuariomodificacion;
    private String vusuariocreacion;
    private Date dfechamodificacion;
    private Date dfechacreacion;
    private Set<TpoliticaPerfil> tpoliticaPerfils = new HashSet<TpoliticaPerfil>(0);

    public Mtpolitica() {
    }

    public Mtpolitica(BigDecimal npoliticaid) {
        this.npoliticaid = npoliticaid;
    }

    public Mtpolitica(BigDecimal npoliticaid, String vnombre, String vdescripcion, BigDecimal nactivo, String vusuariomodificacion, String vusuariocreacion, Date dfechamodificacion, Date dfechacreacion, Set<TpoliticaPerfil> tpoliticaPerfils) {
        this.npoliticaid = npoliticaid;
        this.vnombre = vnombre;
        this.vdescripcion = vdescripcion;
        this.nactivo = nactivo;
        this.vusuariomodificacion = vusuariomodificacion;
        this.vusuariocreacion = vusuariocreacion;
        this.dfechamodificacion = dfechamodificacion;
        this.dfechacreacion = dfechacreacion;
        this.tpoliticaPerfils = tpoliticaPerfils;
    }

    public BigDecimal getNpoliticaid() {
        return this.npoliticaid;
    }

    public void setNpoliticaid(BigDecimal npoliticaid) {
        this.npoliticaid = npoliticaid;
    }

    public String getVnombre() {
        return this.vnombre;
    }

    public void setVnombre(String vnombre) {
        this.vnombre = vnombre;
    }

    public String getVdescripcion() {
        return this.vdescripcion;
    }

    public void setVdescripcion(String vdescripcion) {
        this.vdescripcion = vdescripcion;
    }

    public BigDecimal getNactivo() {
        return this.nactivo;
    }

    public void setNactivo(BigDecimal nactivo) {
        this.nactivo = nactivo;
    }

    public String getVusuariomodificacion() {
        return this.vusuariomodificacion;
    }

    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }

    public String getVusuariocreacion() {
        return this.vusuariocreacion;
    }

    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }

    public Date getDfechamodificacion() {
        return dfechamodificacion;
    }

    public void setDfechamodificacion(Date dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }

    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    public Set<TpoliticaPerfil> getTpoliticaPerfils() {
        return this.tpoliticaPerfils;
    }

    public void setTpoliticaPerfils(Set<TpoliticaPerfil> tpoliticaPerfils) {
        this.tpoliticaPerfils = tpoliticaPerfils;
    }

}
