package pe.gob.mef.gescon.hibernate.domain;
// Generated 06/11/2015 11:03:52 AM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mtsituacion generated by hbm2java
 */
public class Mtsituacion implements java.io.Serializable {

    private BigDecimal nsituacionid;
    private String vnombre;
    private String vdescripcion;
    private String vusuariocreacion;
    private String vusuariomodificacion;
    private Date dfechacreacion;
    private Date dfechamodificacion;
    private Set tpreguntas = new HashSet(0);
    private Set tconocimientos = new HashSet(0);

    public Mtsituacion() {
    }

    public Mtsituacion(BigDecimal nsituacionid) {
        this.nsituacionid = nsituacionid;
    }

    public Mtsituacion(BigDecimal nsituacionid, String vnombre, String vdescripcion, String vusuariocreacion, String vusuariomodificacion, Date dfechacreacion, Date dfechamodificacion, Set tpreguntas, Set tconocimientos) {
        this.nsituacionid = nsituacionid;
        this.vnombre = vnombre;
        this.vdescripcion = vdescripcion;
        this.vusuariocreacion = vusuariocreacion;
        this.vusuariomodificacion = vusuariomodificacion;
        this.dfechacreacion = dfechacreacion;
        this.dfechamodificacion = dfechamodificacion;
        this.tpreguntas = tpreguntas;
        this.tconocimientos = tconocimientos;
    }

    public BigDecimal getNsituacionid() {
        return this.nsituacionid;
    }

    public void setNsituacionid(BigDecimal nsituacionid) {
        this.nsituacionid = nsituacionid;
    }

    public String getVnombre() {
        return this.vnombre;
    }

    public void setVnombre(String vnombre) {
        this.vnombre = vnombre;
    }

    public String getVdescripcion() {
        return this.vdescripcion;
    }

    public void setVdescripcion(String vdescripcion) {
        this.vdescripcion = vdescripcion;
    }

    public String getVusuariocreacion() {
        return this.vusuariocreacion;
    }

    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }

    public String getVusuariomodificacion() {
        return this.vusuariomodificacion;
    }

    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }

    public Serializable getDfechacreacion() {
        return this.dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    public Serializable getDfechamodificacion() {
        return this.dfechamodificacion;
    }

    public void setDfechamodificacion(Date dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }

    public Set getTpreguntas() {
        return this.tpreguntas;
    }

    public void setTpreguntas(Set tpreguntas) {
        this.tpreguntas = tpreguntas;
    }

    public Set getTconocimientos() {
        return this.tconocimientos;
    }

    public void setTconocimientos(Set tconocimientos) {
        this.tconocimientos = tconocimientos;
    }

}
