package pe.gob.mef.gescon.hibernate.domain;
// Generated 11/09/2015 05:20:07 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MttipoConocimiento generated by hbm2java
 */
public class MttipoConocimiento  implements java.io.Serializable {


     private BigDecimal ntpoconocimientoid;
     private String vnombre;
     private BigDecimal nusuariomod;
     private BigDecimal nusuariocreacion;
     private Date dfechacreacion;
     private Set<Tconocimiento> tconocimientos = new HashSet<Tconocimiento>(0);

    public MttipoConocimiento() {
    }

	
    public MttipoConocimiento(BigDecimal ntpoconocimientoid) {
        this.ntpoconocimientoid = ntpoconocimientoid;
    }
    public MttipoConocimiento(BigDecimal ntpoconocimientoid, String vnombre, BigDecimal nusuariomod, BigDecimal nusuariocreacion, Date dfechacreacion, Set<Tconocimiento> tconocimientos) {
       this.ntpoconocimientoid = ntpoconocimientoid;
       this.vnombre = vnombre;
       this.nusuariomod = nusuariomod;
       this.nusuariocreacion = nusuariocreacion;
       this.dfechacreacion = dfechacreacion;
       this.tconocimientos = tconocimientos;
    }
   
    public BigDecimal getNtpoconocimientoid() {
        return this.ntpoconocimientoid;
    }
    
    public void setNtpoconocimientoid(BigDecimal ntpoconocimientoid) {
        this.ntpoconocimientoid = ntpoconocimientoid;
    }
    public String getVnombre() {
        return this.vnombre;
    }
    
    public void setVnombre(String vnombre) {
        this.vnombre = vnombre;
    }
    public BigDecimal getNusuariomod() {
        return this.nusuariomod;
    }
    
    public void setNusuariomod(BigDecimal nusuariomod) {
        this.nusuariomod = nusuariomod;
    }
    public BigDecimal getNusuariocreacion() {
        return this.nusuariocreacion;
    }
    
    public void setNusuariocreacion(BigDecimal nusuariocreacion) {
        this.nusuariocreacion = nusuariocreacion;
    }
    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }
    
    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }
    public Set<Tconocimiento> getTconocimientos() {
        return this.tconocimientos;
    }
    
    public void setTconocimientos(Set<Tconocimiento> tconocimientos) {
        this.tconocimientos = tconocimientos;
    }




}


