package pe.gob.mef.gescon.hibernate.domain;
// Generated 06/11/2015 11:03:52 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Mtrango generated by hbm2java
 */
public class MttipoEntidad implements java.io.Serializable {

    private BigDecimal ntipoentidadid;
    private String vdescripcion;

    public MttipoEntidad() {
    }

    public MttipoEntidad(BigDecimal ntipoentidadid) {
        this.ntipoentidadid = ntipoentidadid;
    }

    public MttipoEntidad(BigDecimal ntipoentidadid, String vdescripcion) {
        this.ntipoentidadid = ntipoentidadid;
        this.vdescripcion = vdescripcion;
    }

    /**
     * @return the ntipoentidadid
     */
    public BigDecimal getNtipoentidadid() {
        return ntipoentidadid;
    }

    /**
     * @param ntipoentidadid the ntipoentidadid to set
     */
    public void setNtipoentidadid(BigDecimal ntipoentidadid) {
        this.ntipoentidadid = ntipoentidadid;
    }

    /**
     * @return the vdescripcion
     */
    public String getVdescripcion() {
        return vdescripcion;
    }

    /**
     * @param vdescripcion the vdescripcion to set
     */
    public void setVdescripcion(String vdescripcion) {
        this.vdescripcion = vdescripcion;
    }

    
}
