package pe.gob.mef.gescon.hibernate.domain;
// Generated 11/09/2015 05:20:07 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MttipoConocimiento generated by hbm2java
 */
public class MttipoConocimiento implements java.io.Serializable {

    private BigDecimal ntpoconocimientoid;
    private String vnombre;
    private String vusuariomodificacion;
    private String vusuariocreacion;    
    private Date dfechacreacion;
    private Date dfechamodificacion;
    private Set<Tconocimiento> tconocimientos = new HashSet<Tconocimiento>(0);

    public MttipoConocimiento() {
    }

    public MttipoConocimiento(BigDecimal ntpoconocimientoid) {
        this.ntpoconocimientoid = ntpoconocimientoid;
    }

    public MttipoConocimiento(BigDecimal ntpoconocimientoid, String vnombre, String vusuariomodificacion, String vusuariocreacion, Date dfechacreacion, Date dfechamodificacion, Set<Tconocimiento> tconocimientos) {
        this.ntpoconocimientoid = ntpoconocimientoid;
        this.vnombre = vnombre;
        this.vusuariomodificacion = vusuariomodificacion;
        this.vusuariocreacion = vusuariocreacion;
        this.dfechacreacion = dfechacreacion;
        this.dfechamodificacion = dfechamodificacion;
        this.tconocimientos = tconocimientos;
    }

    public BigDecimal getNtpoconocimientoid() {
        return this.ntpoconocimientoid;
    }

    public void setNtpoconocimientoid(BigDecimal ntpoconocimientoid) {
        this.ntpoconocimientoid = ntpoconocimientoid;
    }

    public String getVnombre() {
        return this.vnombre;
    }

    public void setVnombre(String vnombre) {
        this.vnombre = vnombre;
    }

    public String getVusuariomodificacion() {
        return vusuariomodificacion;
    }

    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }

    public String getVusuariocreacion() {
        return vusuariocreacion;
    }

    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }

    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    public Date getDfechamodificacion() {
        return dfechamodificacion;
    }

    public void setDfechamodificacion(Date dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }

    public Set<Tconocimiento> getTconocimientos() {
        return this.tconocimientos;
    }

    public void setTconocimientos(Set<Tconocimiento> tconocimientos) {
        this.tconocimientos = tconocimientos;
    }

}
