package pe.gob.mef.gescon.hibernate.domain;
// Generated 28/01/2016 07:52:47 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * Mtubigeo generated by hbm2java
 */
public class Mtubigeo implements java.io.Serializable {

    private BigDecimal nubigeoid;
    private String vcoddep;
    private String vcodprov;
    private String vcoddist;
    private String vdescdep;
    private String vdescprov;
    private String vdescdist;

    public Mtubigeo() {
    }

    public Mtubigeo(BigDecimal nubigeoid) {
        this.nubigeoid = nubigeoid;
    }

    public Mtubigeo(BigDecimal nubigeoid, String vcoddep, String vcodprov, String vcoddist, String vdescdep, String vdescprov, String vdescdist) {
        this.nubigeoid = nubigeoid;
        this.vcoddep = vcoddep;
        this.vcodprov = vcodprov;
        this.vcoddist = vcoddist;
        this.vdescdep = vdescdep;
        this.vdescprov = vdescprov;
        this.vdescdist = vdescdist;
    }

    public BigDecimal getNubigeoid() {
        return this.nubigeoid;
    }

    public void setNubigeoid(BigDecimal nubigeoid) {
        this.nubigeoid = nubigeoid;
    }

    public String getVcoddep() {
        return this.vcoddep;
    }

    public void setVcoddep(String vcoddep) {
        this.vcoddep = vcoddep;
    }

    public String getVcodprov() {
        return this.vcodprov;
    }

    public void setVcodprov(String vcodprov) {
        this.vcodprov = vcodprov;
    }

    public String getVcoddist() {
        return this.vcoddist;
    }

    public void setVcoddist(String vcoddist) {
        this.vcoddist = vcoddist;
    }

    public String getVdescdep() {
        return this.vdescdep;
    }

    public void setVdescdep(String vdescdep) {
        this.vdescdep = vdescdep;
    }

    public String getVdescprov() {
        return this.vdescprov;
    }

    public void setVdescprov(String vdescprov) {
        this.vdescprov = vdescprov;
    }

    public String getVdescdist() {
        return this.vdescdist;
    }

    public void setVdescdist(String vdescdist) {
        this.vdescdist = vdescdist;
    }

}
