package pe.gob.mef.gescon.hibernate.domain;
// Generated 28/01/2016 07:52:47 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * Mtubigeo generated by hbm2java
 */
public class MtubigeoEntidad implements java.io.Serializable {

    private BigDecimal nubigeoid;
    private String cdepartamento;
    private String cprovincia;
    private String cdistrito;
    private String vdescripcion;

    public MtubigeoEntidad() {
    }

    public MtubigeoEntidad(BigDecimal nubigeoid) {
        this.nubigeoid = nubigeoid;
    }

    public MtubigeoEntidad(BigDecimal nubigeoid, String cdepartamento, String cprovincia, String cdistrito, String vdescripcion) {
        this.nubigeoid = nubigeoid;
        this.cdepartamento = cdepartamento;
        this.cprovincia = cprovincia;
        this.cdistrito = cdistrito;
        this.vdescripcion = vdescripcion;
    }

    public BigDecimal getNubigeoid() {
        return this.nubigeoid;
    }

    public void setNubigeoid(BigDecimal nubigeoid) {
        this.nubigeoid = nubigeoid;
    }

    /**
     * @return the cdepartamento
     */
    public String getCdepartamento() {
        return cdepartamento;
    }

    /**
     * @param cdepartamento the cdepartamento to set
     */
    public void setCdepartamento(String cdepartamento) {
        this.cdepartamento = cdepartamento;
    }

    /**
     * @return the cprovincia
     */
    public String getCprovincia() {
        return cprovincia;
    }

    /**
     * @param cprovincia the cprovincia to set
     */
    public void setCprovincia(String cprovincia) {
        this.cprovincia = cprovincia;
    }

    /**
     * @return the cdistrito
     */
    public String getCdistrito() {
        return cdistrito;
    }

    /**
     * @param cdistrito the cdistrito to set
     */
    public void setCdistrito(String cdistrito) {
        this.cdistrito = cdistrito;
    }

    /**
     * @return the vdescripcion
     */
    public String getVdescripcion() {
        return vdescripcion;
    }

    /**
     * @param vdescripcion the vdescripcion to set
     */
    public void setVdescripcion(String vdescripcion) {
        this.vdescripcion = vdescripcion;
    }

    

}
