package pe.gob.mef.gescon.hibernate.domain;
// Generated 11/09/2015 05:20:07 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mtuser generated by hbm2java
 */
public class Mtuser implements java.io.Serializable {

    private BigDecimal nusuarioid;
    private String vlogin;
    private String vnombres;
    private String vapellidos;
    private String vcorreo;
    private Character nestado;
    private BigDecimal nusuariomod;
    private BigDecimal nusuariocreacion;
    private Date dfechacreacion;
    private Set<TuserPerfil> tuserPerfils = new HashSet<TuserPerfil>(0);
    private Set<Tpass> tpasses = new HashSet<Tpass>(0);

    public Mtuser() {
    }

    public Mtuser(BigDecimal nusuarioid) {
        this.nusuarioid = nusuarioid;
    }

    public Mtuser(BigDecimal nusuarioid, String vlogin, String vnombres, String vapellidos, String vcorreo, Character nestado, BigDecimal nusuariomod, BigDecimal nusuariocreacion, Date dfechacreacion, Set<TuserPerfil> tuserPerfils, Set<Tpass> tpasses) {
        this.nusuarioid = nusuarioid;
        this.vlogin = vlogin;
        this.vnombres = vnombres;
        this.vapellidos = vapellidos;
        this.vcorreo = vcorreo;
        this.nestado = nestado;
        this.nusuariomod = nusuariomod;
        this.nusuariocreacion = nusuariocreacion;
        this.dfechacreacion = dfechacreacion;
        this.tuserPerfils = tuserPerfils;
        this.tpasses = tpasses;
    }

    public BigDecimal getNusuarioid() {
        return this.nusuarioid;
    }

    public void setNusuarioid(BigDecimal nusuarioid) {
        this.nusuarioid = nusuarioid;
    }

    public String getVlogin() {
        return this.vlogin;
    }

    public void setVlogin(String vlogin) {
        this.vlogin = vlogin;
    }

    public String getVnombres() {
        return this.vnombres;
    }

    public void setVnombres(String vnombres) {
        this.vnombres = vnombres;
    }

    public String getVapellidos() {
        return this.vapellidos;
    }

    public void setVapellidos(String vapellidos) {
        this.vapellidos = vapellidos;
    }

    public String getVcorreo() {
        return this.vcorreo;
    }

    public void setVcorreo(String vcorreo) {
        this.vcorreo = vcorreo;
    }

    public Character getNestado() {
        return this.nestado;
    }

    public void setNestado(Character nestado) {
        this.nestado = nestado;
    }

    public BigDecimal getNusuariomod() {
        return this.nusuariomod;
    }

    public void setNusuariomod(BigDecimal nusuariomod) {
        this.nusuariomod = nusuariomod;
    }

    public BigDecimal getNusuariocreacion() {
        return this.nusuariocreacion;
    }

    public void setNusuariocreacion(BigDecimal nusuariocreacion) {
        this.nusuariocreacion = nusuariocreacion;
    }

    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    public Set<TuserPerfil> getTuserPerfils() {
        return this.tuserPerfils;
    }

    public void setTuserPerfils(Set<TuserPerfil> tuserPerfils) {
        this.tuserPerfils = tuserPerfils;
    }

    public Set<Tpass> getTpasses() {
        return this.tpasses;
    }

    public void setTpasses(Set<Tpass> tpasses) {
        this.tpasses = tpasses;
    }

}
