package pe.gob.mef.gescon.hibernate.domain;
// Generated 12/10/2015 03:16:20 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Tarchivo generated by hbm2java
 */
public class Tarchivo  implements java.io.Serializable {


     private TarchivoId id;
     private Tbaselegal tbaselegal;
     private String vnombre;
     private String vruta;
     private BigDecimal nversion;
     private String vusuariocreacion;
     private Date dfechacreacion;
     private String vusuariomodificacion;
     private Date dfechamodificacion;

    public Tarchivo() {
    }

	
    public Tarchivo(TarchivoId id, Tbaselegal tbaselegal) {
        this.id = id;
        this.tbaselegal = tbaselegal;
    }
    public Tarchivo(TarchivoId id, Tbaselegal tbaselegal, String vnombre, String vruta, BigDecimal nversion, String vusuariocreacion, Date dfechacreacion, String vusuariomodificacion, Date dfechamodificacion) {
       this.id = id;
       this.tbaselegal = tbaselegal;
       this.vnombre = vnombre;
       this.vruta = vruta;
       this.nversion = nversion;
       this.vusuariocreacion = vusuariocreacion;
       this.dfechacreacion = dfechacreacion;
       this.vusuariomodificacion = vusuariomodificacion;
       this.dfechamodificacion = dfechamodificacion;
    }
   
    public TarchivoId getId() {
        return this.id;
    }
    
    public void setId(TarchivoId id) {
        this.id = id;
    }
    public Tbaselegal getTbaselegal() {
        return this.tbaselegal;
    }
    
    public void setTbaselegal(Tbaselegal tbaselegal) {
        this.tbaselegal = tbaselegal;
    }
    public String getVnombre() {
        return this.vnombre;
    }
    
    public void setVnombre(String vnombre) {
        this.vnombre = vnombre;
    }
    public String getVruta() {
        return this.vruta;
    }
    
    public void setVruta(String vruta) {
        this.vruta = vruta;
    }
    public BigDecimal getNversion() {
        return this.nversion;
    }
    
    public void setNversion(BigDecimal nversion) {
        this.nversion = nversion;
    }
    public String getVusuariocreacion() {
        return this.vusuariocreacion;
    }
    
    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }
    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }
    
    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }
    public String getVusuariomodificacion() {
        return this.vusuariomodificacion;
    }
    
    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }
    public Date getDfechamodificacion() {
        return this.dfechamodificacion;
    }
    
    public void setDfechamodificacion(Date dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }




}


