package pe.gob.mef.gescon.hibernate.domain;
// Generated 28/12/2015 01:39:52 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TarchivoHist generated by hbm2java
 */
public class TarchivoHist implements java.io.Serializable {

    private BigDecimal narchivohistid;
    private BigDecimal nhistorialid;
    private BigDecimal nbaselegalid;
    private String vnombre;
    private String vruta;
    private BigDecimal nversion;
    private String vusuariocreacion;
    private Date dfechacreacion;
    private String vusuariomodificacion;
    private Date dfechamodificacion;

    public TarchivoHist() {
    }

    public TarchivoHist(BigDecimal narchivohistid) {
        this.narchivohistid = narchivohistid;
    }

    public TarchivoHist(BigDecimal narchivohistid, BigDecimal nhistorialid, BigDecimal nbaselegalid, String vnombre, String vruta, String vusuariocreacion, Date dfechacreacion, String vusuariomodificacion, Date dfechamodificacion) {
        this.narchivohistid = narchivohistid;
        this.nhistorialid = nhistorialid;
        this.nbaselegalid = nbaselegalid;
        this.vnombre = vnombre;
        this.vruta = vruta;
        this.vusuariocreacion = vusuariocreacion;
        this.dfechacreacion = dfechacreacion;
        this.vusuariomodificacion = vusuariomodificacion;
        this.dfechamodificacion = dfechamodificacion;
    }

    public BigDecimal getNarchivohistid() {
        return this.narchivohistid;
    }

    public void setNarchivohistid(BigDecimal narchivohistid) {
        this.narchivohistid = narchivohistid;
    }

    public BigDecimal getNhistorialid() {
        return this.nhistorialid;
    }

    public void setNhistorialid(BigDecimal nhistorialid) {
        this.nhistorialid = nhistorialid;
    }

    public BigDecimal getNbaselegalid() {
        return this.nbaselegalid;
    }

    public void setNbaselegalid(BigDecimal nbaselegalid) {
        this.nbaselegalid = nbaselegalid;
    }

    public String getVnombre() {
        return this.vnombre;
    }

    public void setVnombre(String vnombre) {
        this.vnombre = vnombre;
    }

    public String getVruta() {
        return this.vruta;
    }

    public void setVruta(String vruta) {
        this.vruta = vruta;
    }

    public String getVusuariocreacion() {
        return this.vusuariocreacion;
    }

    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }

    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    public String getVusuariomodificacion() {
        return this.vusuariomodificacion;
    }

    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }

    public Date getDfechamodificacion() {
        return this.dfechamodificacion;
    }

    public void setDfechamodificacion(Date dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }

    public BigDecimal getNversion() {
        return nversion;
    }

    public void setNversion(BigDecimal nversion) {
        this.nversion = nversion;
    }

}
