package pe.gob.mef.gescon.hibernate.domain;
// Generated 12/10/2015 03:16:20 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TarchivoId generated by hbm2java
 */
public class TarchivoId  implements java.io.Serializable {


     private BigDecimal nbaselegalid;
     private BigDecimal narchivoid;

    public TarchivoId() {
    }

    public TarchivoId(BigDecimal nbaselegalid, BigDecimal narchivoid) {
       this.nbaselegalid = nbaselegalid;
       this.narchivoid = narchivoid;
    }
   
    public BigDecimal getNbaselegalid() {
        return this.nbaselegalid;
    }
    
    public void setNbaselegalid(BigDecimal nbaselegalid) {
        this.nbaselegalid = nbaselegalid;
    }
    public BigDecimal getNarchivoid() {
        return this.narchivoid;
    }
    
    public void setNarchivoid(BigDecimal narchivoid) {
        this.narchivoid = narchivoid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TarchivoId) ) return false;
		 TarchivoId castOther = ( TarchivoId ) other; 
         
		 return ( (this.getNbaselegalid()==castOther.getNbaselegalid()) || ( this.getNbaselegalid()!=null && castOther.getNbaselegalid()!=null && this.getNbaselegalid().equals(castOther.getNbaselegalid()) ) )
 && ( (this.getNarchivoid()==castOther.getNarchivoid()) || ( this.getNarchivoid()!=null && castOther.getNarchivoid()!=null && this.getNarchivoid().equals(castOther.getNarchivoid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNbaselegalid() == null ? 0 : this.getNbaselegalid().hashCode() );
         result = 37 * result + ( getNarchivoid() == null ? 0 : this.getNarchivoid().hashCode() );
         return result;
   }   


}


