package pe.gob.mef.gescon.hibernate.domain;
// Generated 22/09/2015 05:59:19 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Tasignacion generated by hbm2java
 */
public class Tasignacion implements java.io.Serializable {

    private BigDecimal nasignacionid;
    private BigDecimal ntipoconocimientoid;
    private BigDecimal nconocimientoid;
    private BigDecimal nusuarioid;
    private BigDecimal nestadoid;
    private String vusuariocreacion;
    private String vusuariomodificacion;
    private Date dfechacreacion;
    private Date dfechamodificacion;

    public Tasignacion() {
    }

    public Tasignacion(BigDecimal nasignacionid, BigDecimal ntipoconocimientoid, BigDecimal nconocimientoid, BigDecimal nusuarioid, BigDecimal nestadoid, String vusuariocreacion, Date dfechacreacion, String vusuariomodificacion, Date dfechamodificacion) {
        this.nasignacionid = nasignacionid;
        this.ntipoconocimientoid = ntipoconocimientoid;
        this.nconocimientoid = nconocimientoid;
        this.nusuarioid = nusuarioid;
        this.nestadoid = nestadoid;
        this.vusuariocreacion = vusuariocreacion;
        this.dfechacreacion = dfechacreacion;
        this.vusuariomodificacion = vusuariomodificacion;
        this.dfechamodificacion = dfechamodificacion;
    }

    /**
     * @return the nasignacionid
     */
    public BigDecimal getNasignacionid() {
        return nasignacionid;
    }

    /**
     * @param nasignacionid the nasignacionid to set
     */
    public void setNasignacionid(BigDecimal nasignacionid) {
        this.nasignacionid = nasignacionid;
    }

    /**
     * @return the ntipoconocimientoid
     */
    public BigDecimal getNtipoconocimientoid() {
        return ntipoconocimientoid;
    }

    /**
     * @param ntipoconocimientoid the ntipoconocimientoid to set
     */
    public void setNtipoconocimientoid(BigDecimal ntipoconocimientoid) {
        this.ntipoconocimientoid = ntipoconocimientoid;
    }

    /**
     * @return the nconocimientoid
     */
    public BigDecimal getNconocimientoid() {
        return nconocimientoid;
    }

    /**
     * @param nconocimientoid the nconocimientoid to set
     */
    public void setNconocimientoid(BigDecimal nconocimientoid) {
        this.nconocimientoid = nconocimientoid;
    }

    /**
     * @return the nusuarioid
     */
    public BigDecimal getNusuarioid() {
        return nusuarioid;
    }

    /**
     * @param nusuarioid the nusuarioid to set
     */
    public void setNusuarioid(BigDecimal nusuarioid) {
        this.nusuarioid = nusuarioid;
    }

    /**
     * @return the nestadoid
     */
    public BigDecimal getNestadoid() {
        return nestadoid;
    }

    /**
     * @param nestadoid the nestadoid to set
     */
    public void setNestadoid(BigDecimal nestadoid) {
        this.nestadoid = nestadoid;
    }

    /**
     * @return the vusuariocreacion
     */
    public String getVusuariocreacion() {
        return vusuariocreacion;
    }

    /**
     * @param vusuariocreacion the vusuariocreacion to set
     */
    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }

    /**
     * @return the vusuariomodificacion
     */
    public String getVusuariomodificacion() {
        return vusuariomodificacion;
    }

    /**
     * @param vusuariomodificacion the vusuariomodificacion to set
     */
    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }

    /**
     * @return the dfechacreacion
     */
    public Date getDfechacreacion() {
        return dfechacreacion;
    }

    /**
     * @param dfechacreacion the dfechacreacion to set
     */
    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    /**
     * @return the dfechamodificacion
     */
    public Date getDfechamodificacion() {
        return dfechamodificacion;
    }

    /**
     * @param dfechamodificacion the dfechamodificacion to set
     */
    public void setDfechamodificacion(Date dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }

    
    
}
