package pe.gob.mef.gescon.hibernate.domain;
// Generated 06/11/2015 11:03:52 AM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Tasignacion generated by hbm2java
 */
public class Tasignacion implements java.io.Serializable {

    private BigDecimal nasignacionid;
    private BigDecimal ntipoconocimientoid;
    private BigDecimal nconocimientoid;
    private BigDecimal nusuarioid;
    private BigDecimal nestadoid;
    private String vusuariocreacion;
    private String vusuariomodificacion;
    private Date dfechacreacion;
    private Date dfechamodificacion;
    private Date dfechaasignacion;
    private Date dfechaatencion;
    private Date dfecharecepcion;
    private BigDecimal naccionid;

    public Tasignacion() {
    }

    public Tasignacion(BigDecimal nasignacionid) {
        this.nasignacionid = nasignacionid;
    }

    public Tasignacion(BigDecimal nasignacionid, BigDecimal ntipoconocimientoid, BigDecimal nconocimientoid, BigDecimal nusuarioid, BigDecimal nestadoid, String vusuariocreacion, String vusuariomodificacion, Date dfechacreacion, Date dfechamodificacion, Date dfechaasignacion, Date dfechaatencion, Date dfecharecepcion) {
        this.nasignacionid = nasignacionid;
        this.ntipoconocimientoid = ntipoconocimientoid;
        this.nconocimientoid = nconocimientoid;
        this.nusuarioid = nusuarioid;
        this.nestadoid = nestadoid;
        this.vusuariocreacion = vusuariocreacion;
        this.vusuariomodificacion = vusuariomodificacion;
        this.dfechacreacion = dfechacreacion;
        this.dfechamodificacion = dfechamodificacion;
        this.dfechaasignacion = dfechaasignacion;
        this.dfechaatencion = dfechaatencion;
        this.dfecharecepcion = dfecharecepcion;
    }

    public BigDecimal getNasignacionid() {
        return this.nasignacionid;
    }

    public void setNasignacionid(BigDecimal nasignacionid) {
        this.nasignacionid = nasignacionid;
    }

    public BigDecimal getNtipoconocimientoid() {
        return this.ntipoconocimientoid;
    }

    public void setNtipoconocimientoid(BigDecimal ntipoconocimientoid) {
        this.ntipoconocimientoid = ntipoconocimientoid;
    }

    public BigDecimal getNconocimientoid() {
        return this.nconocimientoid;
    }

    public void setNconocimientoid(BigDecimal nconocimientoid) {
        this.nconocimientoid = nconocimientoid;
    }

    public BigDecimal getNusuarioid() {
        return this.nusuarioid;
    }

    public void setNusuarioid(BigDecimal nusuarioid) {
        this.nusuarioid = nusuarioid;
    }

    public BigDecimal getNestadoid() {
        return this.nestadoid;
    }

    public void setNestadoid(BigDecimal nestadoid) {
        this.nestadoid = nestadoid;
    }

    public String getVusuariocreacion() {
        return this.vusuariocreacion;
    }

    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }

    public String getVusuariomodificacion() {
        return this.vusuariomodificacion;
    }

    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }

    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    public Date getDfechamodificacion() {
        return this.dfechamodificacion;
    }

    public void setDfechamodificacion(Date dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }

    public Date getDfechaasignacion() {
        return this.dfechaasignacion;
    }

    public void setDfechaasignacion(Date dfechaasignacion) {
        this.dfechaasignacion = dfechaasignacion;
    }

    public Date getDfechaatencion() {
        return this.dfechaatencion;
    }

    public void setDfechaatencion(Date dfechaatencion) {
        this.dfechaatencion = dfechaatencion;
    }

    public Date getDfecharecepcion() {
        return this.dfecharecepcion;
    }

    public void setDfecharecepcion(Date dfecharecepcion) {
        this.dfecharecepcion = dfecharecepcion;
    }

    public BigDecimal getNaccionid() {
        return naccionid;
    }

    public void setNaccionid(BigDecimal naccionid) {
        this.naccionid = naccionid;
    }

}
