package pe.gob.mef.gescon.hibernate.domain;
// Generated 28/12/2015 01:39:52 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbaselegalHist generated by hbm2java
 */
public class TbaselegalHist implements java.io.Serializable {

    private BigDecimal nhistorialid;
    private BigDecimal nbaselegalid;
    private BigDecimal ncategoriaid;
    private String vnombre;
    private String vnumero;
    private BigDecimal nrangoid;
    private BigDecimal ngobnacional;
    private BigDecimal ngobregional;
    private BigDecimal ngoblocal;
    private BigDecimal nmancomunidades;
    private String vsumilla;
    private Date dfechapublicacion;
    private String vtema;
    private BigDecimal nactivo;
    private BigDecimal nestadoid;
    private String vusuariocreacion;
    private Date dfechacreacion;
    private String vusuariomodificacion;
    private Date dfechamodificacion;
    private BigDecimal ndestacado;
    private BigDecimal nversion;
    private Set tvinculoBaselegalHists = new HashSet(0);
    private Set tarchivoHists = new HashSet(0);

    public TbaselegalHist() {
    }

    public TbaselegalHist(BigDecimal nhistorialid) {
        this.nhistorialid = nhistorialid;
    }

    public TbaselegalHist(BigDecimal nhistorialid, BigDecimal nbaselegalid, BigDecimal ncategoriaid, String vnombre, String vnumero, BigDecimal nrangoid, BigDecimal ngobnacional, BigDecimal ngobregional, BigDecimal ngoblocal, BigDecimal nmancomunidades, String vsumilla, Date dfechapublicacion, String vtema, BigDecimal nactivo, BigDecimal nestadoid, String vusuariocreacion, Date dfechacreacion, String vusuariomodificacion, Date dfechamodificacion, BigDecimal ndestacado, Set tvinculoBaselegalHists, Set tarchivoHists) {
        this.nhistorialid = nhistorialid;
        this.nbaselegalid = nbaselegalid;
        this.ncategoriaid = ncategoriaid;
        this.vnombre = vnombre;
        this.vnumero = vnumero;
        this.nrangoid = nrangoid;
        this.ngobnacional = ngobnacional;
        this.ngobregional = ngobregional;
        this.ngoblocal = ngoblocal;
        this.nmancomunidades = nmancomunidades;
        this.vsumilla = vsumilla;
        this.dfechapublicacion = dfechapublicacion;
        this.vtema = vtema;
        this.nactivo = nactivo;
        this.nestadoid = nestadoid;
        this.vusuariocreacion = vusuariocreacion;
        this.dfechacreacion = dfechacreacion;
        this.vusuariomodificacion = vusuariomodificacion;
        this.dfechamodificacion = dfechamodificacion;
        this.ndestacado = ndestacado;
        this.tvinculoBaselegalHists = tvinculoBaselegalHists;
        this.tarchivoHists = tarchivoHists;
    }

    public BigDecimal getNhistorialid() {
        return this.nhistorialid;
    }

    public void setNhistorialid(BigDecimal nhistorialid) {
        this.nhistorialid = nhistorialid;
    }

    public BigDecimal getNbaselegalid() {
        return this.nbaselegalid;
    }

    public void setNbaselegalid(BigDecimal nbaselegalid) {
        this.nbaselegalid = nbaselegalid;
    }

    public BigDecimal getNcategoriaid() {
        return this.ncategoriaid;
    }

    public void setNcategoriaid(BigDecimal ncategoriaid) {
        this.ncategoriaid = ncategoriaid;
    }

    public String getVnombre() {
        return this.vnombre;
    }

    public void setVnombre(String vnombre) {
        this.vnombre = vnombre;
    }

    public String getVnumero() {
        return this.vnumero;
    }

    public void setVnumero(String vnumero) {
        this.vnumero = vnumero;
    }

    public BigDecimal getNrangoid() {
        return this.nrangoid;
    }

    public void setNrangoid(BigDecimal nrangoid) {
        this.nrangoid = nrangoid;
    }

    public BigDecimal getNgobnacional() {
        return this.ngobnacional;
    }

    public void setNgobnacional(BigDecimal ngobnacional) {
        this.ngobnacional = ngobnacional;
    }

    public BigDecimal getNgobregional() {
        return this.ngobregional;
    }

    public void setNgobregional(BigDecimal ngobregional) {
        this.ngobregional = ngobregional;
    }

    public BigDecimal getNgoblocal() {
        return this.ngoblocal;
    }

    public void setNgoblocal(BigDecimal ngoblocal) {
        this.ngoblocal = ngoblocal;
    }

    public BigDecimal getNmancomunidades() {
        return this.nmancomunidades;
    }

    public void setNmancomunidades(BigDecimal nmancomunidades) {
        this.nmancomunidades = nmancomunidades;
    }

    public String getVsumilla() {
        return this.vsumilla;
    }

    public void setVsumilla(String vsumilla) {
        this.vsumilla = vsumilla;
    }

    public Date getDfechapublicacion() {
        return this.dfechapublicacion;
    }

    public void setDfechapublicacion(Date dfechapublicacion) {
        this.dfechapublicacion = dfechapublicacion;
    }

    public String getVtema() {
        return this.vtema;
    }

    public void setVtema(String vtema) {
        this.vtema = vtema;
    }

    public BigDecimal getNactivo() {
        return this.nactivo;
    }

    public void setNactivo(BigDecimal nactivo) {
        this.nactivo = nactivo;
    }

    public BigDecimal getNestadoid() {
        return this.nestadoid;
    }

    public void setNestadoid(BigDecimal nestadoid) {
        this.nestadoid = nestadoid;
    }

    public String getVusuariocreacion() {
        return this.vusuariocreacion;
    }

    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }

    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    public String getVusuariomodificacion() {
        return this.vusuariomodificacion;
    }

    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }

    public Date getDfechamodificacion() {
        return this.dfechamodificacion;
    }

    public void setDfechamodificacion(Date dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }

    public BigDecimal getNdestacado() {
        return this.ndestacado;
    }

    public void setNdestacado(BigDecimal ndestacado) {
        this.ndestacado = ndestacado;
    }

    public BigDecimal getNversion() {
        return nversion;
    }

    public void setNversion(BigDecimal nversion) {
        this.nversion = nversion;
    }

    public Set getTvinculoBaselegalHists() {
        return this.tvinculoBaselegalHists;
    }

    public void setTvinculoBaselegalHists(Set tvinculoBaselegalHists) {
        this.tvinculoBaselegalHists = tvinculoBaselegalHists;
    }

    public Set getTarchivoHists() {
        return this.tarchivoHists;
    }

    public void setTarchivoHists(Set tarchivoHists) {
        this.tarchivoHists = tarchivoHists;
    }

}
