package pe.gob.mef.gescon.hibernate.domain;
// Generated 11/09/2015 05:20:07 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Tcalificacion generated by hbm2java
 */
public class Tcalificacion  implements java.io.Serializable {


     private TcalificacionId id;
     private Tconocimiento tconocimiento;
     private BigDecimal ncalificacion;
     private BigDecimal nusuariomod;
     private BigDecimal nusuariocreacion;
     private Date dfechacreacion;

    public Tcalificacion() {
    }

	
    public Tcalificacion(TcalificacionId id, Tconocimiento tconocimiento) {
        this.id = id;
        this.tconocimiento = tconocimiento;
    }
    public Tcalificacion(TcalificacionId id, Tconocimiento tconocimiento, BigDecimal ncalificacion, BigDecimal nusuariomod, BigDecimal nusuariocreacion, Date dfechacreacion) {
       this.id = id;
       this.tconocimiento = tconocimiento;
       this.ncalificacion = ncalificacion;
       this.nusuariomod = nusuariomod;
       this.nusuariocreacion = nusuariocreacion;
       this.dfechacreacion = dfechacreacion;
    }
   
    public TcalificacionId getId() {
        return this.id;
    }
    
    public void setId(TcalificacionId id) {
        this.id = id;
    }
    public Tconocimiento getTconocimiento() {
        return this.tconocimiento;
    }
    
    public void setTconocimiento(Tconocimiento tconocimiento) {
        this.tconocimiento = tconocimiento;
    }
    public BigDecimal getNcalificacion() {
        return this.ncalificacion;
    }
    
    public void setNcalificacion(BigDecimal ncalificacion) {
        this.ncalificacion = ncalificacion;
    }
    public BigDecimal getNusuariomod() {
        return this.nusuariomod;
    }
    
    public void setNusuariomod(BigDecimal nusuariomod) {
        this.nusuariomod = nusuariomod;
    }
    public BigDecimal getNusuariocreacion() {
        return this.nusuariocreacion;
    }
    
    public void setNusuariocreacion(BigDecimal nusuariocreacion) {
        this.nusuariocreacion = nusuariocreacion;
    }
    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }
    
    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }




}


