package pe.gob.mef.gescon.hibernate.domain;
// Generated 26/12/2015 12:01:33 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TcalificacionPregunta generated by hbm2java
 */
public class TcalificacionPregunta implements java.io.Serializable {

    private BigDecimal ncalificacionid;
    private BigDecimal ncalificacion;
    private String vcomentario;
    private String vusuariocreacion;
    private Date dfechacreacion;
    private String vusuariomodificacion;
    private Date dfechamodificacion;
    private BigDecimal npreguntaid;

    public TcalificacionPregunta() {
    }

    public TcalificacionPregunta(BigDecimal ncalificacionid) {
        this.ncalificacionid = ncalificacionid;
    }

    public TcalificacionPregunta(BigDecimal ncalificacionid, BigDecimal ncalificacion, String vcomentario, String vusuariocreacion, Date dfechacreacion, String vusuariomodificacion, Date dfechamodificacion, BigDecimal npreguntaid) {
        this.ncalificacionid = ncalificacionid;
        this.ncalificacion = ncalificacion;
        this.vcomentario = vcomentario;
        this.vusuariocreacion = vusuariocreacion;
        this.dfechacreacion = dfechacreacion;
        this.vusuariomodificacion = vusuariomodificacion;
        this.dfechamodificacion = dfechamodificacion;
        this.npreguntaid = npreguntaid;
    }

    public BigDecimal getNcalificacionid() {
        return this.ncalificacionid;
    }

    public void setNcalificacionid(BigDecimal ncalificacionid) {
        this.ncalificacionid = ncalificacionid;
    }

    public BigDecimal getNcalificacion() {
        return this.ncalificacion;
    }

    public void setNcalificacion(BigDecimal ncalificacion) {
        this.ncalificacion = ncalificacion;
    }

    public String getVcomentario() {
        return this.vcomentario;
    }

    public void setVcomentario(String vcomentario) {
        this.vcomentario = vcomentario;
    }

    public String getVusuariocreacion() {
        return this.vusuariocreacion;
    }

    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }

    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    public String getVusuariomodificacion() {
        return this.vusuariomodificacion;
    }

    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }

    public Date getDfechamodificacion() {
        return this.dfechamodificacion;
    }

    public void setDfechamodificacion(Date dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }

    public BigDecimal getNpreguntaid() {
        return this.npreguntaid;
    }

    public void setNpreguntaid(BigDecimal npreguntaid) {
        this.npreguntaid = npreguntaid;
    }

}
