package pe.gob.mef.gescon.hibernate.domain;
// Generated 06/11/2015 11:03:52 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * TcalificacionHistId generated by hbm2java
 */
public class TcalificacionHistId implements java.io.Serializable {

    private BigDecimal nconocimientoid;
    private BigDecimal ncomentariohid;
    private BigDecimal nhistorialid;

    public TcalificacionHistId() {
    }

    public TcalificacionHistId(BigDecimal nconocimientoid, BigDecimal ncomentariohid, BigDecimal nhistorialid) {
        this.nconocimientoid = nconocimientoid;
        this.ncomentariohid = ncomentariohid;
        this.nhistorialid = nhistorialid;
    }

    public BigDecimal getNconocimientoid() {
        return this.nconocimientoid;
    }

    public void setNconocimientoid(BigDecimal nconocimientoid) {
        this.nconocimientoid = nconocimientoid;
    }

    public BigDecimal getNcomentariohid() {
        return this.ncomentariohid;
    }

    public void setNcomentariohid(BigDecimal ncomentariohid) {
        this.ncomentariohid = ncomentariohid;
    }

    public BigDecimal getNhistorialid() {
        return this.nhistorialid;
    }

    public void setNhistorialid(BigDecimal nhistorialid) {
        this.nhistorialid = nhistorialid;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof TcalificacionHistId)) {
            return false;
        }
        TcalificacionHistId castOther = (TcalificacionHistId) other;

        return ((this.getNconocimientoid() == castOther.getNconocimientoid()) || (this.getNconocimientoid() != null && castOther.getNconocimientoid() != null && this.getNconocimientoid().equals(castOther.getNconocimientoid())))
                && ((this.getNcomentariohid() == castOther.getNcomentariohid()) || (this.getNcomentariohid() != null && castOther.getNcomentariohid() != null && this.getNcomentariohid().equals(castOther.getNcomentariohid())))
                && ((this.getNhistorialid() == castOther.getNhistorialid()) || (this.getNhistorialid() != null && castOther.getNhistorialid() != null && this.getNhistorialid().equals(castOther.getNhistorialid())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getNconocimientoid() == null ? 0 : this.getNconocimientoid().hashCode());
        result = 37 * result + (getNcomentariohid() == null ? 0 : this.getNcomentariohid().hashCode());
        result = 37 * result + (getNhistorialid() == null ? 0 : this.getNhistorialid().hashCode());
        return result;
    }

}
