package pe.gob.mef.gescon.hibernate.domain;
// Generated 06/11/2015 11:03:52 AM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * TcalificacionHist generated by hbm2java
 */
public class TcalificacionHist implements java.io.Serializable {

    private TcalificacionHistId id;
    private Thistorial thistorial;
    private String vcomentario;
    private BigDecimal nestado;
    private String vusuariomodificacion;
    private String vusuariocreacion;
    private Date dfechacreacion;
    private BigDecimal ncalificacion;
    private Date dfechamodificacion;

    public TcalificacionHist() {
    }

    public TcalificacionHist(TcalificacionHistId id, Thistorial thistorial) {
        this.id = id;
        this.thistorial = thistorial;
    }

    public TcalificacionHist(TcalificacionHistId id, Thistorial thistorial, String vcomentario, BigDecimal nestado, String vusuariomodificacion, String vusuariocreacion, Date dfechacreacion, BigDecimal ncalificacion, Date dfechamodificacion) {
        this.id = id;
        this.thistorial = thistorial;
        this.vcomentario = vcomentario;
        this.nestado = nestado;
        this.vusuariomodificacion = vusuariomodificacion;
        this.vusuariocreacion = vusuariocreacion;
        this.dfechacreacion = dfechacreacion;
        this.ncalificacion = ncalificacion;
        this.dfechamodificacion = dfechamodificacion;
    }

    public TcalificacionHistId getId() {
        return this.id;
    }

    public void setId(TcalificacionHistId id) {
        this.id = id;
    }

    public Thistorial getThistorial() {
        return this.thistorial;
    }

    public void setThistorial(Thistorial thistorial) {
        this.thistorial = thistorial;
    }

    public String getVcomentario() {
        return this.vcomentario;
    }

    public void setVcomentario(String vcomentario) {
        this.vcomentario = vcomentario;
    }

    public BigDecimal getNestado() {
        return this.nestado;
    }

    public void setNestado(BigDecimal nestado) {
        this.nestado = nestado;
    }

    public String getVusuariomodificacion() {
        return this.vusuariomodificacion;
    }

    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }

    public String getVusuariocreacion() {
        return this.vusuariocreacion;
    }

    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }

    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    public BigDecimal getNcalificacion() {
        return this.ncalificacion;
    }

    public void setNcalificacion(BigDecimal ncalificacion) {
        this.ncalificacion = ncalificacion;
    }

    public Date getDfechamodificacion() {
        return this.dfechamodificacion;
    }

    public void setDfechamodificacion(Date dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }

}
