package pe.gob.mef.gescon.hibernate.domain;
// Generated 11/09/2015 05:20:07 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TcalificacionId generated by hbm2java
 */
public class TcalificacionId  implements java.io.Serializable {


     private BigDecimal ncalificacionid;
     private BigDecimal nconocimientoid;
     private BigDecimal ntpoconocimientoid;

    public TcalificacionId() {
    }

    public TcalificacionId(BigDecimal ncalificacionid, BigDecimal nconocimientoid, BigDecimal ntpoconocimientoid) {
       this.ncalificacionid = ncalificacionid;
       this.nconocimientoid = nconocimientoid;
       this.ntpoconocimientoid = ntpoconocimientoid;
    }
   
    public BigDecimal getNcalificacionid() {
        return this.ncalificacionid;
    }
    
    public void setNcalificacionid(BigDecimal ncalificacionid) {
        this.ncalificacionid = ncalificacionid;
    }
    public BigDecimal getNconocimientoid() {
        return this.nconocimientoid;
    }
    
    public void setNconocimientoid(BigDecimal nconocimientoid) {
        this.nconocimientoid = nconocimientoid;
    }
    public BigDecimal getNtpoconocimientoid() {
        return this.ntpoconocimientoid;
    }
    
    public void setNtpoconocimientoid(BigDecimal ntpoconocimientoid) {
        this.ntpoconocimientoid = ntpoconocimientoid;
    }




}


