package pe.gob.mef.gescon.hibernate.domain;
// Generated 24/12/2015 10:43:34 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TcalificacionBaselegal generated by hbm2java
 */
public class TcalificacionBaselegal implements java.io.Serializable {

    private BigDecimal ncalificacionid;
    private String vcomentario;
    private BigDecimal ncalificacion;
    private String vusuariocreacion;
    private Date dfechacreacion;
    private String vusuariomodificacion;
    private Date dfechamodificacion;
    private BigDecimal nbaselegalid;

    public TcalificacionBaselegal() {
    }

    public TcalificacionBaselegal(BigDecimal ncalificacionid) {
        this.ncalificacionid = ncalificacionid;
    }

    public TcalificacionBaselegal(BigDecimal ncalificacionid, String vcomentario, BigDecimal ncalificacion, String vusuariocreacion, Date dfechacreacion, String vusuariomodificacion, Date dfechamodificacion, BigDecimal nbaselegalid) {
        this.ncalificacionid = ncalificacionid;
        this.vcomentario = vcomentario;
        this.ncalificacion = ncalificacion;
        this.vusuariocreacion = vusuariocreacion;
        this.dfechacreacion = dfechacreacion;
        this.vusuariomodificacion = vusuariomodificacion;
        this.dfechamodificacion = dfechamodificacion;
        this.nbaselegalid = nbaselegalid;
    }

    public BigDecimal getNcalificacionid() {
        return this.ncalificacionid;
    }

    public void setNcalificacionid(BigDecimal ncalificacionid) {
        this.ncalificacionid = ncalificacionid;
    }

    public String getVcomentario() {
        return this.vcomentario;
    }

    public void setVcomentario(String vcomentario) {
        this.vcomentario = vcomentario;
    }

    public BigDecimal getNcalificacion() {
        return this.ncalificacion;
    }

    public void setNcalificacion(BigDecimal ncalificacion) {
        this.ncalificacion = ncalificacion;
    }

    public String getVusuariocreacion() {
        return this.vusuariocreacion;
    }

    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }

    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    public String getVusuariomodificacion() {
        return this.vusuariomodificacion;
    }

    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }

    public Date getDfechamodificacion() {
        return this.dfechamodificacion;
    }

    public void setDfechamodificacion(Date dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }

    public BigDecimal getNbaselegalid() {
        return this.nbaselegalid;
    }

    public void setNbaselegalid(BigDecimal nbaselegalid) {
        this.nbaselegalid = nbaselegalid;
    }

}
