package pe.gob.mef.gescon.hibernate.domain;
// Generated 11/09/2015 05:20:07 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TcategoriaConocimientoId generated by hbm2java
 */
public class TcategoriaConocimientoId  implements java.io.Serializable {


     private BigDecimal nconocimientoid;
     private BigDecimal ntpoconocimientoid;
     private BigDecimal ncategoriaid;

    public TcategoriaConocimientoId() {
    }

    public TcategoriaConocimientoId(BigDecimal nconocimientoid, BigDecimal ntpoconocimientoid, BigDecimal ncategoriaid) {
       this.nconocimientoid = nconocimientoid;
       this.ntpoconocimientoid = ntpoconocimientoid;
       this.ncategoriaid = ncategoriaid;
    }
   
    public BigDecimal getNconocimientoid() {
        return this.nconocimientoid;
    }
    
    public void setNconocimientoid(BigDecimal nconocimientoid) {
        this.nconocimientoid = nconocimientoid;
    }
    public BigDecimal getNtpoconocimientoid() {
        return this.ntpoconocimientoid;
    }
    
    public void setNtpoconocimientoid(BigDecimal ntpoconocimientoid) {
        this.ntpoconocimientoid = ntpoconocimientoid;
    }
    public BigDecimal getNcategoriaid() {
        return this.ncategoriaid;
    }
    
    public void setNcategoriaid(BigDecimal ncategoriaid) {
        this.ncategoriaid = ncategoriaid;
    }




}


