package pe.gob.mef.gescon.hibernate.domain;
// Generated 31/10/2015 11:21:40 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TcategoriaUser generated by hbm2java
 */
public class TcategoriaUser  implements java.io.Serializable {


     private BigDecimal ncategoriauserid;
     private BigDecimal ncategoriaid;
     private BigDecimal nperfilid;
     private BigDecimal nusuarioid;

    public TcategoriaUser() {
    }

    public TcategoriaUser(BigDecimal ncategoriauserid, BigDecimal ncategoriaid, BigDecimal nperfilid, BigDecimal nusuarioid) {
       this.ncategoriauserid = ncategoriauserid;
       this.ncategoriaid = ncategoriaid;
       this.nperfilid = nperfilid;
       this.nusuarioid = nusuarioid;
    }
   
    public BigDecimal getNcategoriauserid() {
        return this.ncategoriauserid;
    }
    
    public void setNcategoriauserid(BigDecimal ncategoriauserid) {
        this.ncategoriauserid = ncategoriauserid;
    }
    public BigDecimal getNcategoriaid() {
        return this.ncategoriaid;
    }
    
    public void setNcategoriaid(BigDecimal ncategoriaid) {
        this.ncategoriaid = ncategoriaid;
    }
    public BigDecimal getNperfilid() {
        return this.nperfilid;
    }
    
    public void setNperfilid(BigDecimal nperfilid) {
        this.nperfilid = nperfilid;
    }
    public BigDecimal getNusuarioid() {
        return this.nusuarioid;
    }
    
    public void setNusuarioid(BigDecimal nusuarioid) {
        this.nusuarioid = nusuarioid;
    }




}


