package pe.gob.mef.gescon.hibernate.domain;
// Generated 06/11/2015 11:03:52 AM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * TcategoriaUser generated by hbm2java
 */
public class TcategoriaUser implements java.io.Serializable {

    private BigDecimal ncategoriauserid;
    private Mtcategoria mtcategoria;
    private Mtuser mtuser;
    private BigDecimal nperfilid;
    private String vusuariocreacion;
    private String vusuariomodificacion;
    private Date dfechacreacion;
    private Date dfechamodificacion;

    public TcategoriaUser() {
    }

    public TcategoriaUser(BigDecimal ncategoriauserid, Mtcategoria mtcategoria, Mtuser mtuser) {
        this.ncategoriauserid = ncategoriauserid;
        this.mtcategoria = mtcategoria;
        this.mtuser = mtuser;
    }

    public TcategoriaUser(BigDecimal ncategoriauserid, Mtcategoria mtcategoria, Mtuser mtuser, BigDecimal nperfilid, String vusuariocreacion, String vusuariomodificacion, Date dfechacreacion, Date dfechamodificacion) {
        this.ncategoriauserid = ncategoriauserid;
        this.mtcategoria = mtcategoria;
        this.mtuser = mtuser;
        this.nperfilid = nperfilid;
        this.vusuariocreacion = vusuariocreacion;
        this.vusuariomodificacion = vusuariomodificacion;
        this.dfechacreacion = dfechacreacion;
        this.dfechamodificacion = dfechamodificacion;
    }

    public BigDecimal getNcategoriauserid() {
        return this.ncategoriauserid;
    }

    public void setNcategoriauserid(BigDecimal ncategoriauserid) {
        this.ncategoriauserid = ncategoriauserid;
    }

    public Mtcategoria getMtcategoria() {
        return this.mtcategoria;
    }

    public void setMtcategoria(Mtcategoria mtcategoria) {
        this.mtcategoria = mtcategoria;
    }

    public Mtuser getMtuser() {
        return this.mtuser;
    }

    public void setMtuser(Mtuser mtuser) {
        this.mtuser = mtuser;
    }

    public BigDecimal getNperfilid() {
        return this.nperfilid;
    }

    public void setNperfilid(BigDecimal nperfilid) {
        this.nperfilid = nperfilid;
    }

    public String getVusuariocreacion() {
        return this.vusuariocreacion;
    }

    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }

    public String getVusuariomodificacion() {
        return this.vusuariomodificacion;
    }

    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }

    public Serializable getDfechacreacion() {
        return this.dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    public Serializable getDfechamodificacion() {
        return this.dfechamodificacion;
    }

    public void setDfechamodificacion(Date dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }

}
