package pe.gob.mef.gescon.hibernate.domain;
// Generated 11/09/2015 05:20:07 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TcategoriaHistId generated by hbm2java
 */
public class TcategoriaHistId  implements java.io.Serializable {


     private BigDecimal ncategoriahid;
     private BigDecimal nhistorialid;
     private BigDecimal nconocimientoid;
     private BigDecimal ntpoconocimientoid;

    public TcategoriaHistId() {
    }

    public TcategoriaHistId(BigDecimal ncategoriahid, BigDecimal nhistorialid, BigDecimal nconocimientoid, BigDecimal ntpoconocimientoid) {
       this.ncategoriahid = ncategoriahid;
       this.nhistorialid = nhistorialid;
       this.nconocimientoid = nconocimientoid;
       this.ntpoconocimientoid = ntpoconocimientoid;
    }
   
    public BigDecimal getNcategoriahid() {
        return this.ncategoriahid;
    }
    
    public void setNcategoriahid(BigDecimal ncategoriahid) {
        this.ncategoriahid = ncategoriahid;
    }
    public BigDecimal getNhistorialid() {
        return this.nhistorialid;
    }
    
    public void setNhistorialid(BigDecimal nhistorialid) {
        this.nhistorialid = nhistorialid;
    }
    public BigDecimal getNconocimientoid() {
        return this.nconocimientoid;
    }
    
    public void setNconocimientoid(BigDecimal nconocimientoid) {
        this.nconocimientoid = nconocimientoid;
    }
    public BigDecimal getNtpoconocimientoid() {
        return this.ntpoconocimientoid;
    }
    
    public void setNtpoconocimientoid(BigDecimal ntpoconocimientoid) {
        this.ntpoconocimientoid = ntpoconocimientoid;
    }




}


