package pe.gob.mef.gescon.hibernate.domain;
// Generated 27/10/2015 06:08:09 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TcategoriaHistId generated by hbm2java
 */
public class TcategoriaHistId  implements java.io.Serializable {


     private BigDecimal ncategoriahid;
     private BigDecimal nhistorialid;
     private BigDecimal nconocimientoid;

    public TcategoriaHistId() {
    }

    public TcategoriaHistId(BigDecimal ncategoriahid, BigDecimal nhistorialid, BigDecimal nconocimientoid) {
       this.ncategoriahid = ncategoriahid;
       this.nhistorialid = nhistorialid;
       this.nconocimientoid = nconocimientoid;
    }
   
    public BigDecimal getNcategoriahid() {
        return this.ncategoriahid;
    }
    
    public void setNcategoriahid(BigDecimal ncategoriahid) {
        this.ncategoriahid = ncategoriahid;
    }
    public BigDecimal getNhistorialid() {
        return this.nhistorialid;
    }
    
    public void setNhistorialid(BigDecimal nhistorialid) {
        this.nhistorialid = nhistorialid;
    }
    public BigDecimal getNconocimientoid() {
        return this.nconocimientoid;
    }
    
    public void setNconocimientoid(BigDecimal nconocimientoid) {
        this.nconocimientoid = nconocimientoid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TcategoriaHistId) ) return false;
		 TcategoriaHistId castOther = ( TcategoriaHistId ) other; 
         
		 return ( (this.getNcategoriahid()==castOther.getNcategoriahid()) || ( this.getNcategoriahid()!=null && castOther.getNcategoriahid()!=null && this.getNcategoriahid().equals(castOther.getNcategoriahid()) ) )
 && ( (this.getNhistorialid()==castOther.getNhistorialid()) || ( this.getNhistorialid()!=null && castOther.getNhistorialid()!=null && this.getNhistorialid().equals(castOther.getNhistorialid()) ) )
 && ( (this.getNconocimientoid()==castOther.getNconocimientoid()) || ( this.getNconocimientoid()!=null && castOther.getNconocimientoid()!=null && this.getNconocimientoid().equals(castOther.getNconocimientoid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNcategoriahid() == null ? 0 : this.getNcategoriahid().hashCode() );
         result = 37 * result + ( getNhistorialid() == null ? 0 : this.getNhistorialid().hashCode() );
         result = 37 * result + ( getNconocimientoid() == null ? 0 : this.getNconocimientoid().hashCode() );
         return result;
   }   


}


