package pe.gob.mef.gescon.hibernate.domain;
// Generated 27/10/2015 06:08:09 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TcomentHistId generated by hbm2java
 */
public class TcomentHistId  implements java.io.Serializable {


     private BigDecimal nhistorialid;
     private BigDecimal nconocimientoid;
     private BigDecimal ncomentariohid;

    public TcomentHistId() {
    }

    public TcomentHistId(BigDecimal nhistorialid, BigDecimal nconocimientoid, BigDecimal ncomentariohid) {
       this.nhistorialid = nhistorialid;
       this.nconocimientoid = nconocimientoid;
       this.ncomentariohid = ncomentariohid;
    }
   
    public BigDecimal getNhistorialid() {
        return this.nhistorialid;
    }
    
    public void setNhistorialid(BigDecimal nhistorialid) {
        this.nhistorialid = nhistorialid;
    }
    public BigDecimal getNconocimientoid() {
        return this.nconocimientoid;
    }
    
    public void setNconocimientoid(BigDecimal nconocimientoid) {
        this.nconocimientoid = nconocimientoid;
    }
    public BigDecimal getNcomentariohid() {
        return this.ncomentariohid;
    }
    
    public void setNcomentariohid(BigDecimal ncomentariohid) {
        this.ncomentariohid = ncomentariohid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TcomentHistId) ) return false;
		 TcomentHistId castOther = ( TcomentHistId ) other; 
         
		 return ( (this.getNhistorialid()==castOther.getNhistorialid()) || ( this.getNhistorialid()!=null && castOther.getNhistorialid()!=null && this.getNhistorialid().equals(castOther.getNhistorialid()) ) )
 && ( (this.getNconocimientoid()==castOther.getNconocimientoid()) || ( this.getNconocimientoid()!=null && castOther.getNconocimientoid()!=null && this.getNconocimientoid().equals(castOther.getNconocimientoid()) ) )
 && ( (this.getNcomentariohid()==castOther.getNcomentariohid()) || ( this.getNcomentariohid()!=null && castOther.getNcomentariohid()!=null && this.getNcomentariohid().equals(castOther.getNcomentariohid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNhistorialid() == null ? 0 : this.getNhistorialid().hashCode() );
         result = 37 * result + ( getNconocimientoid() == null ? 0 : this.getNconocimientoid().hashCode() );
         result = 37 * result + ( getNcomentariohid() == null ? 0 : this.getNcomentariohid().hashCode() );
         return result;
   }   


}


