package pe.gob.mef.gescon.hibernate.domain;
// Generated 11/09/2015 05:20:07 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Tcomentario generated by hbm2java
 */
public class Tcomentario  implements java.io.Serializable {


     private TcomentarioId id;
     private Tconocimiento tconocimiento;
     private String vcomentario;
     private BigDecimal nusuariomod;
     private Character nestado;
     private BigDecimal nusuariocreacion;
     private Date dfechacreacion;

    public Tcomentario() {
    }

	
    public Tcomentario(TcomentarioId id, Tconocimiento tconocimiento) {
        this.id = id;
        this.tconocimiento = tconocimiento;
    }
    public Tcomentario(TcomentarioId id, Tconocimiento tconocimiento, String vcomentario, BigDecimal nusuariomod, Character nestado, BigDecimal nusuariocreacion, Date dfechacreacion) {
       this.id = id;
       this.tconocimiento = tconocimiento;
       this.vcomentario = vcomentario;
       this.nusuariomod = nusuariomod;
       this.nestado = nestado;
       this.nusuariocreacion = nusuariocreacion;
       this.dfechacreacion = dfechacreacion;
    }
   
    public TcomentarioId getId() {
        return this.id;
    }
    
    public void setId(TcomentarioId id) {
        this.id = id;
    }
    public Tconocimiento getTconocimiento() {
        return this.tconocimiento;
    }
    
    public void setTconocimiento(Tconocimiento tconocimiento) {
        this.tconocimiento = tconocimiento;
    }
    public String getVcomentario() {
        return this.vcomentario;
    }
    
    public void setVcomentario(String vcomentario) {
        this.vcomentario = vcomentario;
    }
    public BigDecimal getNusuariomod() {
        return this.nusuariomod;
    }
    
    public void setNusuariomod(BigDecimal nusuariomod) {
        this.nusuariomod = nusuariomod;
    }
    public Character getNestado() {
        return this.nestado;
    }
    
    public void setNestado(Character nestado) {
        this.nestado = nestado;
    }
    public BigDecimal getNusuariocreacion() {
        return this.nusuariocreacion;
    }
    
    public void setNusuariocreacion(BigDecimal nusuariocreacion) {
        this.nusuariocreacion = nusuariocreacion;
    }
    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }
    
    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }




}


