package pe.gob.mef.gescon.hibernate.domain;
// Generated 11/09/2015 05:20:07 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TcomentarioId generated by hbm2java
 */
public class TcomentarioId  implements java.io.Serializable {


     private BigDecimal ncomentarioid;
     private BigDecimal nconocimientoid;
     private BigDecimal ntpoconocimientoid;

    public TcomentarioId() {
    }

    public TcomentarioId(BigDecimal ncomentarioid, BigDecimal nconocimientoid, BigDecimal ntpoconocimientoid) {
       this.ncomentarioid = ncomentarioid;
       this.nconocimientoid = nconocimientoid;
       this.ntpoconocimientoid = ntpoconocimientoid;
    }
   
    public BigDecimal getNcomentarioid() {
        return this.ncomentarioid;
    }
    
    public void setNcomentarioid(BigDecimal ncomentarioid) {
        this.ncomentarioid = ncomentarioid;
    }
    public BigDecimal getNconocimientoid() {
        return this.nconocimientoid;
    }
    
    public void setNconocimientoid(BigDecimal nconocimientoid) {
        this.nconocimientoid = nconocimientoid;
    }
    public BigDecimal getNtpoconocimientoid() {
        return this.ntpoconocimientoid;
    }
    
    public void setNtpoconocimientoid(BigDecimal ntpoconocimientoid) {
        this.ntpoconocimientoid = ntpoconocimientoid;
    }




}


