package pe.gob.mef.gescon.hibernate.domain;
// Generated 11/09/2015 05:20:07 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * TcomentHist generated by hbm2java
 */
public class TcomentHist  implements java.io.Serializable {


     private TcomentHistId id;
     private String vcomentario;
     private Character nestado;
     private BigDecimal nusuariomod;
     private BigDecimal nusuariocreacion;
     private Date dfechacreacion;

    public TcomentHist() {
    }

	
    public TcomentHist(TcomentHistId id) {
        this.id = id;
    }
    public TcomentHist(TcomentHistId id, String vcomentario, Character nestado, BigDecimal nusuariomod, BigDecimal nusuariocreacion, Date dfechacreacion) {
       this.id = id;
       this.vcomentario = vcomentario;
       this.nestado = nestado;
       this.nusuariomod = nusuariomod;
       this.nusuariocreacion = nusuariocreacion;
       this.dfechacreacion = dfechacreacion;
    }
   
    public TcomentHistId getId() {
        return this.id;
    }
    
    public void setId(TcomentHistId id) {
        this.id = id;
    }
    public String getVcomentario() {
        return this.vcomentario;
    }
    
    public void setVcomentario(String vcomentario) {
        this.vcomentario = vcomentario;
    }
    public Character getNestado() {
        return this.nestado;
    }
    
    public void setNestado(Character nestado) {
        this.nestado = nestado;
    }
    public BigDecimal getNusuariomod() {
        return this.nusuariomod;
    }
    
    public void setNusuariomod(BigDecimal nusuariomod) {
        this.nusuariomod = nusuariomod;
    }
    public BigDecimal getNusuariocreacion() {
        return this.nusuariocreacion;
    }
    
    public void setNusuariocreacion(BigDecimal nusuariocreacion) {
        this.nusuariocreacion = nusuariocreacion;
    }
    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }
    
    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }




}


