package pe.gob.mef.gescon.hibernate.domain;
// Generated 11/09/2015 05:20:07 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TconocimientoId generated by hbm2java
 */
public class TconocimientoId  implements java.io.Serializable {


     private BigDecimal nconocimientoid;
     private BigDecimal ntpoconocimientoid;

    public TconocimientoId() {
    }

    public TconocimientoId(BigDecimal nconocimientoid, BigDecimal ntpoconocimientoid) {
       this.nconocimientoid = nconocimientoid;
       this.ntpoconocimientoid = ntpoconocimientoid;
    }
   
    public BigDecimal getNconocimientoid() {
        return this.nconocimientoid;
    }
    
    public void setNconocimientoid(BigDecimal nconocimientoid) {
        this.nconocimientoid = nconocimientoid;
    }
    public BigDecimal getNtpoconocimientoid() {
        return this.ntpoconocimientoid;
    }
    
    public void setNtpoconocimientoid(BigDecimal ntpoconocimientoid) {
        this.ntpoconocimientoid = ntpoconocimientoid;
    }




}


