package pe.gob.mef.gescon.hibernate.domain;
// Generated 11/09/2015 05:20:07 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tconocimiento generated by hbm2java
 */
public class Tconocimiento implements java.io.Serializable {

    private TconocimientoId id;
    private MttipoConocimiento mttipoConocimiento;
    private String vdescripcion;
    private String vtitulo;
    private BigDecimal nusuariomod;
    private BigDecimal nusuariocreacion;
    private Date dfechacreacion;
    private BigDecimal nundejecutora;
    private String varchivo;
    private String vrango;
    private String vnumero;
    private String vtema;
    private String vdesextra;
    private String vautor;
    private String vfuente;
    private String vtipo;
    private Set<Tvinculo> tvinculos = new HashSet<Tvinculo>(0);
    private Set<Tcomentario> tcomentarios = new HashSet<Tcomentario>(0);
    private Set<TcategoriaConocimiento> tcategoriaConocimientos = new HashSet<TcategoriaConocimiento>(0);
    private Set<Tdiscusion> tdiscusions = new HashSet<Tdiscusion>(0);
    private Set<Tcalificacion> tcalificacions = new HashSet<Tcalificacion>(0);

    public Tconocimiento() {
    }

    public Tconocimiento(TconocimientoId id, MttipoConocimiento mttipoConocimiento) {
        this.id = id;
        this.mttipoConocimiento = mttipoConocimiento;
    }

    public Tconocimiento(TconocimientoId id, MttipoConocimiento mttipoConocimiento, String vdescripcion, String vtitulo, BigDecimal nusuariomod, BigDecimal nusuariocreacion, Date dfechacreacion, BigDecimal nundejecutora, String varchivo, String vrango, String vnumero, String vtema, String vdesextra, String vautor, String vfuente, String vtipo, Set<Tvinculo> tvinculos, Set<Tcomentario> tcomentarios, Set<TcategoriaConocimiento> tcategoriaConocimientos, Set<Tdiscusion> tdiscusions, Set<Tcalificacion> tcalificacions) {
        this.id = id;
        this.mttipoConocimiento = mttipoConocimiento;
        this.vdescripcion = vdescripcion;
        this.vtitulo = vtitulo;
        this.nusuariomod = nusuariomod;
        this.nusuariocreacion = nusuariocreacion;
        this.dfechacreacion = dfechacreacion;
        this.nundejecutora = nundejecutora;
        this.varchivo = varchivo;
        this.vrango = vrango;
        this.vnumero = vnumero;
        this.vtema = vtema;
        this.vdesextra = vdesextra;
        this.vautor = vautor;
        this.vfuente = vfuente;
        this.vtipo = vtipo;
        this.tvinculos = tvinculos;
        this.tcomentarios = tcomentarios;
        this.tcategoriaConocimientos = tcategoriaConocimientos;
        this.tdiscusions = tdiscusions;
        this.tcalificacions = tcalificacions;
    }

    public TconocimientoId getId() {
        return this.id;
    }

    public void setId(TconocimientoId id) {
        this.id = id;
    }

    public MttipoConocimiento getMttipoConocimiento() {
        return this.mttipoConocimiento;
    }

    public void setMttipoConocimiento(MttipoConocimiento mttipoConocimiento) {
        this.mttipoConocimiento = mttipoConocimiento;
    }

    public String getVdescripcion() {
        return this.vdescripcion;
    }

    public void setVdescripcion(String vdescripcion) {
        this.vdescripcion = vdescripcion;
    }

    public String getVtitulo() {
        return this.vtitulo;
    }

    public void setVtitulo(String vtitulo) {
        this.vtitulo = vtitulo;
    }

    public BigDecimal getNusuariomod() {
        return this.nusuariomod;
    }

    public void setNusuariomod(BigDecimal nusuariomod) {
        this.nusuariomod = nusuariomod;
    }

    public BigDecimal getNusuariocreacion() {
        return this.nusuariocreacion;
    }

    public void setNusuariocreacion(BigDecimal nusuariocreacion) {
        this.nusuariocreacion = nusuariocreacion;
    }

    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    public BigDecimal getNundejecutora() {
        return this.nundejecutora;
    }

    public void setNundejecutora(BigDecimal nundejecutora) {
        this.nundejecutora = nundejecutora;
    }

    public String getVarchivo() {
        return this.varchivo;
    }

    public void setVarchivo(String varchivo) {
        this.varchivo = varchivo;
    }

    public String getVrango() {
        return this.vrango;
    }

    public void setVrango(String vrango) {
        this.vrango = vrango;
    }

    public String getVnumero() {
        return this.vnumero;
    }

    public void setVnumero(String vnumero) {
        this.vnumero = vnumero;
    }

    public String getVtema() {
        return this.vtema;
    }

    public void setVtema(String vtema) {
        this.vtema = vtema;
    }

    public String getVdesextra() {
        return this.vdesextra;
    }

    public void setVdesextra(String vdesextra) {
        this.vdesextra = vdesextra;
    }

    public String getVautor() {
        return this.vautor;
    }

    public void setVautor(String vautor) {
        this.vautor = vautor;
    }

    public String getVfuente() {
        return this.vfuente;
    }

    public void setVfuente(String vfuente) {
        this.vfuente = vfuente;
    }

    public String getVtipo() {
        return this.vtipo;
    }

    public void setVtipo(String vtipo) {
        this.vtipo = vtipo;
    }

    public Set<Tvinculo> getTvinculos() {
        return this.tvinculos;
    }

    public void setTvinculos(Set<Tvinculo> tvinculos) {
        this.tvinculos = tvinculos;
    }

    public Set<Tcomentario> getTcomentarios() {
        return this.tcomentarios;
    }

    public void setTcomentarios(Set<Tcomentario> tcomentarios) {
        this.tcomentarios = tcomentarios;
    }

    public Set<TcategoriaConocimiento> getTcategoriaConocimientos() {
        return this.tcategoriaConocimientos;
    }

    public void setTcategoriaConocimientos(Set<TcategoriaConocimiento> tcategoriaConocimientos) {
        this.tcategoriaConocimientos = tcategoriaConocimientos;
    }

    public Set<Tdiscusion> getTdiscusions() {
        return this.tdiscusions;
    }

    public void setTdiscusions(Set<Tdiscusion> tdiscusions) {
        this.tdiscusions = tdiscusions;
    }

    public Set<Tcalificacion> getTcalificacions() {
        return this.tcalificacions;
    }

    public void setTcalificacions(Set<Tcalificacion> tcalificacions) {
        this.tcalificacions = tcalificacions;
    }

}
