package pe.gob.mef.gescon.hibernate.domain;
// Generated 11/09/2015 05:20:07 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TdiscusionId generated by hbm2java
 */
public class TdiscusionId  implements java.io.Serializable {


     private BigDecimal ndiscusionid;
     private BigDecimal nconocimientoid;
     private BigDecimal ntpoconocimientoid;

    public TdiscusionId() {
    }

    public TdiscusionId(BigDecimal ndiscusionid, BigDecimal nconocimientoid, BigDecimal ntpoconocimientoid) {
       this.ndiscusionid = ndiscusionid;
       this.nconocimientoid = nconocimientoid;
       this.ntpoconocimientoid = ntpoconocimientoid;
    }
   
    public BigDecimal getNdiscusionid() {
        return this.ndiscusionid;
    }
    
    public void setNdiscusionid(BigDecimal ndiscusionid) {
        this.ndiscusionid = ndiscusionid;
    }
    public BigDecimal getNconocimientoid() {
        return this.nconocimientoid;
    }
    
    public void setNconocimientoid(BigDecimal nconocimientoid) {
        this.nconocimientoid = nconocimientoid;
    }
    public BigDecimal getNtpoconocimientoid() {
        return this.ntpoconocimientoid;
    }
    
    public void setNtpoconocimientoid(BigDecimal ntpoconocimientoid) {
        this.ntpoconocimientoid = ntpoconocimientoid;
    }




}


