package pe.gob.mef.gescon.hibernate.domain;
// Generated 06/11/2015 11:03:52 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * TdiscusionHistId generated by hbm2java
 */
public class TdiscusionHistId implements java.io.Serializable {

    private BigDecimal nconocimientoid;
    private BigDecimal nhistorialid;
    private BigDecimal ndiscusionhid;

    public TdiscusionHistId() {
    }

    public TdiscusionHistId(BigDecimal nconocimientoid, BigDecimal nhistorialid, BigDecimal ndiscusionhid) {
        this.nconocimientoid = nconocimientoid;
        this.nhistorialid = nhistorialid;
        this.ndiscusionhid = ndiscusionhid;
    }

    public BigDecimal getNconocimientoid() {
        return this.nconocimientoid;
    }

    public void setNconocimientoid(BigDecimal nconocimientoid) {
        this.nconocimientoid = nconocimientoid;
    }

    public BigDecimal getNhistorialid() {
        return this.nhistorialid;
    }

    public void setNhistorialid(BigDecimal nhistorialid) {
        this.nhistorialid = nhistorialid;
    }

    public BigDecimal getNdiscusionhid() {
        return this.ndiscusionhid;
    }

    public void setNdiscusionhid(BigDecimal ndiscusionhid) {
        this.ndiscusionhid = ndiscusionhid;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof TdiscusionHistId)) {
            return false;
        }
        TdiscusionHistId castOther = (TdiscusionHistId) other;

        return ((this.getNconocimientoid() == castOther.getNconocimientoid()) || (this.getNconocimientoid() != null && castOther.getNconocimientoid() != null && this.getNconocimientoid().equals(castOther.getNconocimientoid())))
                && ((this.getNhistorialid() == castOther.getNhistorialid()) || (this.getNhistorialid() != null && castOther.getNhistorialid() != null && this.getNhistorialid().equals(castOther.getNhistorialid())))
                && ((this.getNdiscusionhid() == castOther.getNdiscusionhid()) || (this.getNdiscusionhid() != null && castOther.getNdiscusionhid() != null && this.getNdiscusionhid().equals(castOther.getNdiscusionhid())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getNconocimientoid() == null ? 0 : this.getNconocimientoid().hashCode());
        result = 37 * result + (getNhistorialid() == null ? 0 : this.getNhistorialid().hashCode());
        result = 37 * result + (getNdiscusionhid() == null ? 0 : this.getNdiscusionhid().hashCode());
        return result;
    }

}
