package pe.gob.mef.gescon.hibernate.domain;
// Generated 18/12/2015 11:45:08 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tdiscusion generated by hbm2java
 */
public class Tdiscusion implements java.io.Serializable {

    private BigDecimal ndiscusionid;
    private String vdescripcion;
    private String vusuariomodificacion;
    private String vusuariocreacion;
    private Date dfechacreacion;
    private BigDecimal nconocimientoid;
    private Date dfechamodificacion;
    private Set tdiscusionSeccions = new HashSet(0);

    public Tdiscusion() {
    }

    public Tdiscusion(BigDecimal ndiscusionid, BigDecimal nconocimientoid) {
        this.ndiscusionid = ndiscusionid;
        this.nconocimientoid = nconocimientoid;
    }

    public Tdiscusion(BigDecimal ndiscusionid, String vdescripcion, String vusuariomodificacion, String vusuariocreacion, Date dfechacreacion, BigDecimal nconocimientoid, Date dfechamodificacion, Set tdiscusionSeccions) {
        this.ndiscusionid = ndiscusionid;
        this.vdescripcion = vdescripcion;
        this.vusuariomodificacion = vusuariomodificacion;
        this.vusuariocreacion = vusuariocreacion;
        this.dfechacreacion = dfechacreacion;
        this.nconocimientoid = nconocimientoid;
        this.dfechamodificacion = dfechamodificacion;
        this.tdiscusionSeccions = tdiscusionSeccions;
    }

    public BigDecimal getNdiscusionid() {
        return this.ndiscusionid;
    }

    public void setNdiscusionid(BigDecimal ndiscusionid) {
        this.ndiscusionid = ndiscusionid;
    }

    public String getVdescripcion() {
        return this.vdescripcion;
    }

    public void setVdescripcion(String vdescripcion) {
        this.vdescripcion = vdescripcion;
    }

    public String getVusuariomodificacion() {
        return this.vusuariomodificacion;
    }

    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }

    public String getVusuariocreacion() {
        return this.vusuariocreacion;
    }

    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }

    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    public BigDecimal getNconocimientoid() {
        return this.nconocimientoid;
    }

    public void setNconocimientoid(BigDecimal nconocimientoid) {
        this.nconocimientoid = nconocimientoid;
    }

    public Date getDfechamodificacion() {
        return this.dfechamodificacion;
    }

    public void setDfechamodificacion(Date dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }

    public Set getTdiscusionSeccions() {
        return this.tdiscusionSeccions;
    }

    public void setTdiscusionSeccions(Set tdiscusionSeccions) {
        this.tdiscusionSeccions = tdiscusionSeccions;
    }

}
