package pe.gob.mef.gescon.hibernate.domain;
// Generated 18/12/2015 06:17:48 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TdiscusionHist generated by hbm2java
 */
public class TdiscusionHist implements java.io.Serializable {

    private BigDecimal ndiscusionhid;
    private BigDecimal nconocimientoid;
    private String vdescripcion;
    private BigDecimal nnumversion;
    private String vusuariomodificacion;
    private String vusuariocreacion;
    private Date dfechacreacion;
    private Date dfechamodificacion;
    private Set tdiscusionSeccionHists = new HashSet(0);

    public TdiscusionHist() {
    }

    public TdiscusionHist(BigDecimal ndiscusionhid) {
        this.ndiscusionhid = ndiscusionhid;
    }

    public TdiscusionHist(BigDecimal ndiscusionhid, String vdescripcion, BigDecimal nnumversion, String vusuariomodificacion, String vusuariocreacion, Date dfechacreacion, Date dfechamodificacion, BigDecimal nconocimientoid, Set tdiscusionSeccionHists) {
        this.ndiscusionhid = ndiscusionhid;
        this.vdescripcion = vdescripcion;
        this.nnumversion = nnumversion;
        this.vusuariomodificacion = vusuariomodificacion;
        this.vusuariocreacion = vusuariocreacion;
        this.dfechacreacion = dfechacreacion;
        this.dfechamodificacion = dfechamodificacion;
        this.nconocimientoid = nconocimientoid;
        this.tdiscusionSeccionHists = tdiscusionSeccionHists;
    }

    public BigDecimal getNdiscusionhid() {
        return this.ndiscusionhid;
    }

    public void setNdiscusionhid(BigDecimal ndiscusionhid) {
        this.ndiscusionhid = ndiscusionhid;
    }

    public String getVdescripcion() {
        return this.vdescripcion;
    }

    public void setVdescripcion(String vdescripcion) {
        this.vdescripcion = vdescripcion;
    }

    public BigDecimal getNnumversion() {
        return nnumversion;
    }

    public void setNnumversion(BigDecimal nnumversion) {
        this.nnumversion = nnumversion;
    }

    public String getVusuariomodificacion() {
        return this.vusuariomodificacion;
    }

    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }

    public String getVusuariocreacion() {
        return this.vusuariocreacion;
    }

    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }

    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    public Date getDfechamodificacion() {
        return this.dfechamodificacion;
    }

    public void setDfechamodificacion(Date dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }

    public BigDecimal getNconocimientoid() {
        return this.nconocimientoid;
    }

    public void setNconocimientoid(BigDecimal nconocimientoid) {
        this.nconocimientoid = nconocimientoid;
    }

    public Set getTdiscusionSeccionHists() {
        return this.tdiscusionSeccionHists;
    }

    public void setTdiscusionSeccionHists(Set tdiscusionSeccionHists) {
        this.tdiscusionSeccionHists = tdiscusionSeccionHists;
    }
}
