package pe.gob.mef.gescon.hibernate.domain;
// Generated 06/11/2015 11:03:52 AM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Tdiscusion generated by hbm2java
 */
public class Tdiscusion implements java.io.Serializable {

    private BigDecimal ndiscusionid;
    private Tconocimiento tconocimiento;
    private String vdiscusion;
    private String vusuariomodificacion;
    private String vusuariocreacion;
    private Date dfechacreacion;
    private Date dfechamodificacion;

    public Tdiscusion() {
    }

    public Tdiscusion(BigDecimal ndiscusionid, Tconocimiento tconocimiento) {
        this.ndiscusionid = ndiscusionid;
        this.tconocimiento = tconocimiento;
    }

    public Tdiscusion(BigDecimal ndiscusionid, Tconocimiento tconocimiento, String vdiscusion, String vusuariomodificacion, String vusuariocreacion, Date dfechacreacion, Date dfechamodificacion) {
        this.ndiscusionid = ndiscusionid;
        this.tconocimiento = tconocimiento;
        this.vdiscusion = vdiscusion;
        this.vusuariomodificacion = vusuariomodificacion;
        this.vusuariocreacion = vusuariocreacion;
        this.dfechacreacion = dfechacreacion;
        this.dfechamodificacion = dfechamodificacion;
    }

    public BigDecimal getNdiscusionid() {
        return this.ndiscusionid;
    }

    public void setNdiscusionid(BigDecimal ndiscusionid) {
        this.ndiscusionid = ndiscusionid;
    }

    public Tconocimiento getTconocimiento() {
        return this.tconocimiento;
    }

    public void setTconocimiento(Tconocimiento tconocimiento) {
        this.tconocimiento = tconocimiento;
    }

    public String getVdiscusion() {
        return this.vdiscusion;
    }

    public void setVdiscusion(String vdiscusion) {
        this.vdiscusion = vdiscusion;
    }

    public String getVusuariomodificacion() {
        return this.vusuariomodificacion;
    }

    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }

    public String getVusuariocreacion() {
        return this.vusuariocreacion;
    }

    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }

    public Serializable getDfechacreacion() {
        return this.dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    public Serializable getDfechamodificacion() {
        return this.dfechamodificacion;
    }

    public void setDfechamodificacion(Date dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }

}
