package pe.gob.mef.gescon.hibernate.domain;
// Generated 27/10/2015 06:08:09 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Thistorial generated by hbm2java
 */
public class Thistorial  implements java.io.Serializable {


     private ThistorialId id;
     private Tconocimiento tconocimiento;
     private String vdescripcion;
     private String vtitulo;
     private BigDecimal nusuariomod;
     private BigDecimal nusuariocreacion;
     private Date dfechacreacion;
     private BigDecimal nundejecutora;
     private String varchivo;
     private String vrango;
     private String vnumero;
     private String vtema;
     private String vdesextra;
     private String vautor;
     private String vfuente;
     private String vtipo;
     private BigDecimal nnumversion;
     private String vcontenido;
     private BigDecimal nestado;
     private BigDecimal nsituacion;
     private BigDecimal ndias;
     private String vobservacion;
     private Set tvincHists = new HashSet(0);
     private Set tcomentHists = new HashSet(0);
     private Set tcategoriaHists = new HashSet(0);

    public Thistorial() {
    }

	
    public Thistorial(ThistorialId id, Tconocimiento tconocimiento) {
        this.id = id;
        this.tconocimiento = tconocimiento;
    }
    public Thistorial(ThistorialId id, Tconocimiento tconocimiento, String vdescripcion, String vtitulo, BigDecimal nusuariomod, BigDecimal nusuariocreacion, Date dfechacreacion, BigDecimal nundejecutora, String varchivo, String vrango, String vnumero, String vtema, String vdesextra, String vautor, String vfuente, String vtipo, BigDecimal nnumversion, String vcontenido, BigDecimal nestado, BigDecimal nsituacion, BigDecimal ndias, String vobservacion, Set tvincHists, Set tcomentHists, Set tcategoriaHists) {
       this.id = id;
       this.tconocimiento = tconocimiento;
       this.vdescripcion = vdescripcion;
       this.vtitulo = vtitulo;
       this.nusuariomod = nusuariomod;
       this.nusuariocreacion = nusuariocreacion;
       this.dfechacreacion = dfechacreacion;
       this.nundejecutora = nundejecutora;
       this.varchivo = varchivo;
       this.vrango = vrango;
       this.vnumero = vnumero;
       this.vtema = vtema;
       this.vdesextra = vdesextra;
       this.vautor = vautor;
       this.vfuente = vfuente;
       this.vtipo = vtipo;
       this.nnumversion = nnumversion;
       this.vcontenido = vcontenido;
       this.nestado = nestado;
       this.nsituacion = nsituacion;
       this.ndias = ndias;
       this.vobservacion = vobservacion;
       this.tvincHists = tvincHists;
       this.tcomentHists = tcomentHists;
       this.tcategoriaHists = tcategoriaHists;
    }
   
    public ThistorialId getId() {
        return this.id;
    }
    
    public void setId(ThistorialId id) {
        this.id = id;
    }
    public Tconocimiento getTconocimiento() {
        return this.tconocimiento;
    }
    
    public void setTconocimiento(Tconocimiento tconocimiento) {
        this.tconocimiento = tconocimiento;
    }
    public String getVdescripcion() {
        return this.vdescripcion;
    }
    
    public void setVdescripcion(String vdescripcion) {
        this.vdescripcion = vdescripcion;
    }
    public String getVtitulo() {
        return this.vtitulo;
    }
    
    public void setVtitulo(String vtitulo) {
        this.vtitulo = vtitulo;
    }
    public BigDecimal getNusuariomod() {
        return this.nusuariomod;
    }
    
    public void setNusuariomod(BigDecimal nusuariomod) {
        this.nusuariomod = nusuariomod;
    }
    public BigDecimal getNusuariocreacion() {
        return this.nusuariocreacion;
    }
    
    public void setNusuariocreacion(BigDecimal nusuariocreacion) {
        this.nusuariocreacion = nusuariocreacion;
    }
    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }
    
    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }
    public BigDecimal getNundejecutora() {
        return this.nundejecutora;
    }
    
    public void setNundejecutora(BigDecimal nundejecutora) {
        this.nundejecutora = nundejecutora;
    }
    public String getVarchivo() {
        return this.varchivo;
    }
    
    public void setVarchivo(String varchivo) {
        this.varchivo = varchivo;
    }
    public String getVrango() {
        return this.vrango;
    }
    
    public void setVrango(String vrango) {
        this.vrango = vrango;
    }
    public String getVnumero() {
        return this.vnumero;
    }
    
    public void setVnumero(String vnumero) {
        this.vnumero = vnumero;
    }
    public String getVtema() {
        return this.vtema;
    }
    
    public void setVtema(String vtema) {
        this.vtema = vtema;
    }
    public String getVdesextra() {
        return this.vdesextra;
    }
    
    public void setVdesextra(String vdesextra) {
        this.vdesextra = vdesextra;
    }
    public String getVautor() {
        return this.vautor;
    }
    
    public void setVautor(String vautor) {
        this.vautor = vautor;
    }
    public String getVfuente() {
        return this.vfuente;
    }
    
    public void setVfuente(String vfuente) {
        this.vfuente = vfuente;
    }
    public String getVtipo() {
        return this.vtipo;
    }
    
    public void setVtipo(String vtipo) {
        this.vtipo = vtipo;
    }
    public BigDecimal getNnumversion() {
        return this.nnumversion;
    }
    
    public void setNnumversion(BigDecimal nnumversion) {
        this.nnumversion = nnumversion;
    }
    public String getVcontenido() {
        return this.vcontenido;
    }
    
    public void setVcontenido(String vcontenido) {
        this.vcontenido = vcontenido;
    }
    public BigDecimal getNestado() {
        return this.nestado;
    }
    
    public void setNestado(BigDecimal nestado) {
        this.nestado = nestado;
    }
    public BigDecimal getNsituacion() {
        return this.nsituacion;
    }
    
    public void setNsituacion(BigDecimal nsituacion) {
        this.nsituacion = nsituacion;
    }
    public BigDecimal getNdias() {
        return this.ndias;
    }
    
    public void setNdias(BigDecimal ndias) {
        this.ndias = ndias;
    }
    public String getVobservacion() {
        return this.vobservacion;
    }
    
    public void setVobservacion(String vobservacion) {
        this.vobservacion = vobservacion;
    }
    public Set getTvincHists() {
        return this.tvincHists;
    }
    
    public void setTvincHists(Set tvincHists) {
        this.tvincHists = tvincHists;
    }
    public Set getTcomentHists() {
        return this.tcomentHists;
    }
    
    public void setTcomentHists(Set tcomentHists) {
        this.tcomentHists = tcomentHists;
    }
    public Set getTcategoriaHists() {
        return this.tcategoriaHists;
    }
    
    public void setTcategoriaHists(Set tcategoriaHists) {
        this.tcategoriaHists = tcategoriaHists;
    }




}


