package pe.gob.mef.gescon.hibernate.domain;
// Generated 06/11/2015 11:03:52 AM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TimplementacionHist generated by hbm2java
 */
public class TimplementacionHist implements java.io.Serializable {

    private TimplementacionHistId id;
    private Thistorial thistorial;
    private String vdescripcion;
    private String vtitulo;
    private String vcontenido;
    private String vmsjespecialista;
    private String vmsjmoderador;
    private String vusuariocreacion;
    private String vusuariomodificacion;
    private Date dfechacreacion;
    private Date dfechamodificacion;
    private Set tvinculoImplementacionHists = new HashSet(0);

    public TimplementacionHist() {
    }

    public TimplementacionHist(TimplementacionHistId id, Thistorial thistorial) {
        this.id = id;
        this.thistorial = thistorial;
    }

    public TimplementacionHist(TimplementacionHistId id, Thistorial thistorial, String vdescripcion, String vtitulo, String vcontenido, String vmsjespecialista, String vmsjmoderador, String vusuariocreacion, String vusuariomodificacion, Date dfechacreacion, Date dfechamodificacion, Set tvinculoImplementacionHists) {
        this.id = id;
        this.thistorial = thistorial;
        this.vdescripcion = vdescripcion;
        this.vtitulo = vtitulo;
        this.vcontenido = vcontenido;
        this.vmsjespecialista = vmsjespecialista;
        this.vmsjmoderador = vmsjmoderador;
        this.vusuariocreacion = vusuariocreacion;
        this.vusuariomodificacion = vusuariomodificacion;
        this.dfechacreacion = dfechacreacion;
        this.dfechamodificacion = dfechamodificacion;
        this.tvinculoImplementacionHists = tvinculoImplementacionHists;
    }

    public TimplementacionHistId getId() {
        return this.id;
    }

    public void setId(TimplementacionHistId id) {
        this.id = id;
    }

    public Thistorial getThistorial() {
        return this.thistorial;
    }

    public void setThistorial(Thistorial thistorial) {
        this.thistorial = thistorial;
    }

    public String getVdescripcion() {
        return this.vdescripcion;
    }

    public void setVdescripcion(String vdescripcion) {
        this.vdescripcion = vdescripcion;
    }

    public String getVtitulo() {
        return this.vtitulo;
    }

    public void setVtitulo(String vtitulo) {
        this.vtitulo = vtitulo;
    }

    public String getVcontenido() {
        return this.vcontenido;
    }

    public void setVcontenido(String vcontenido) {
        this.vcontenido = vcontenido;
    }

    public String getVmsjespecialista() {
        return this.vmsjespecialista;
    }

    public void setVmsjespecialista(String vmsjespecialista) {
        this.vmsjespecialista = vmsjespecialista;
    }

    public String getVmsjmoderador() {
        return this.vmsjmoderador;
    }

    public void setVmsjmoderador(String vmsjmoderador) {
        this.vmsjmoderador = vmsjmoderador;
    }

    public String getVusuariocreacion() {
        return this.vusuariocreacion;
    }

    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }

    public String getVusuariomodificacion() {
        return this.vusuariomodificacion;
    }

    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }

    public Serializable getDfechacreacion() {
        return this.dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    public Serializable getDfechamodificacion() {
        return this.dfechamodificacion;
    }

    public void setDfechamodificacion(Date dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }

    public Set getTvinculoImplementacionHists() {
        return this.tvinculoImplementacionHists;
    }

    public void setTvinculoImplementacionHists(Set tvinculoImplementacionHists) {
        this.tvinculoImplementacionHists = tvinculoImplementacionHists;
    }

}
