package pe.gob.mef.gescon.hibernate.domain;
// Generated 06/11/2015 11:03:52 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Timplementacion generated by hbm2java
 */
public class Timplementacion implements java.io.Serializable {

    private BigDecimal nimplementacionid;
    private BigDecimal nconocimientoid;
    private BigDecimal ncategoriaid;
    private BigDecimal nsituacionid;
    private BigDecimal ntipoconocimientoid;
    private String vdescripcion;
    private String vtitulo;
    private String vcontenido;
    private BigDecimal ndestacado;
    private String vruta;
    private String vmsjespecialista;
    private String vmsjmoderador;
    private String vusuariocreacion;
    private String vusuariomodificacion;
    private Date dfechacreacion;
    private Date dfechamodificacion;
    private Set tvinculoImplementacions = new HashSet(0);

    public Timplementacion() {
    }

    public Timplementacion(BigDecimal nimplementacionid) {
        this.nimplementacionid = nimplementacionid;
    }

    public Timplementacion(BigDecimal nimplementacionid, BigDecimal nconocimientoid, String vdescripcion, String vtitulo, String vcontenido, String vmsjespecialista, String vmsjmoderador, String vusuariocreacion, String vusuariomodificacion, Date dfechacreacion, Date dfechamodificacion, Set tvinculoImplementacions) {
        this.nimplementacionid = nimplementacionid;
        this.nconocimientoid = nconocimientoid;
        this.vdescripcion = vdescripcion;
        this.vtitulo = vtitulo;
        this.vcontenido = vcontenido;
        this.vmsjespecialista = vmsjespecialista;
        this.vmsjmoderador = vmsjmoderador;
        this.vusuariocreacion = vusuariocreacion;
        this.vusuariomodificacion = vusuariomodificacion;
        this.dfechacreacion = dfechacreacion;
        this.dfechamodificacion = dfechamodificacion;
        this.tvinculoImplementacions = tvinculoImplementacions;
    }

    public BigDecimal getNimplementacionid() {
        return this.nimplementacionid;
    }

    public void setNimplementacionid(BigDecimal nimplementacionid) {
        this.nimplementacionid = nimplementacionid;
    }

    public BigDecimal getNconocimientoid() {
        return this.nconocimientoid;
    }

    public void setNconocimientoid(BigDecimal nconocimientoid) {
        this.nconocimientoid = nconocimientoid;
    }

    public BigDecimal getNcategoriaid() {
        return ncategoriaid;
    }

    public void setNcategoriaid(BigDecimal ncategoriaid) {
        this.ncategoriaid = ncategoriaid;
    }

    public BigDecimal getNsituacionid() {
        return nsituacionid;
    }

    public void setNsituacionid(BigDecimal nsituacionid) {
        this.nsituacionid = nsituacionid;
    }

    public BigDecimal getNtipoconocimientoid() {
        return ntipoconocimientoid;
    }

    public void setNtipoconocimientoid(BigDecimal ntipoconocimientoid) {
        this.ntipoconocimientoid = ntipoconocimientoid;
    }

    public String getVdescripcion() {
        return this.vdescripcion;
    }

    public void setVdescripcion(String vdescripcion) {
        this.vdescripcion = vdescripcion;
    }

    public String getVtitulo() {
        return this.vtitulo;
    }

    public void setVtitulo(String vtitulo) {
        this.vtitulo = vtitulo;
    }

    public String getVcontenido() {
        return this.vcontenido;
    }

    public void setVcontenido(String vcontenido) {
        this.vcontenido = vcontenido;
    }

    public BigDecimal getNdestacado() {
        return ndestacado;
    }

    public void setNdestacado(BigDecimal ndestacado) {
        this.ndestacado = ndestacado;
    }

    public String getVruta() {
        return vruta;
    }

    public void setVruta(String vruta) {
        this.vruta = vruta;
    }

    public String getVmsjespecialista() {
        return this.vmsjespecialista;
    }

    public void setVmsjespecialista(String vmsjespecialista) {
        this.vmsjespecialista = vmsjespecialista;
    }

    public String getVmsjmoderador() {
        return this.vmsjmoderador;
    }

    public void setVmsjmoderador(String vmsjmoderador) {
        this.vmsjmoderador = vmsjmoderador;
    }

    public String getVusuariocreacion() {
        return this.vusuariocreacion;
    }

    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }

    public String getVusuariomodificacion() {
        return this.vusuariomodificacion;
    }

    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }

    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    public Date getDfechamodificacion() {
        return this.dfechamodificacion;
    }

    public void setDfechamodificacion(Date dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }

    public Set getTvinculoImplementacions() {
        return this.tvinculoImplementacions;
    }

    public void setTvinculoImplementacions(Set tvinculoImplementacions) {
        this.tvinculoImplementacions = tvinculoImplementacions;
    }

}
