package pe.gob.mef.gescon.hibernate.domain;
// Generated 27/10/2015 06:08:09 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Timplementacion generated by hbm2java
 */
public class Timplementacion  implements java.io.Serializable {


     private BigDecimal nimplementacionid;
     private Tconocimiento tconocimiento;
     private String vdescripcion;
     private String vtitulo;
     private String vcontenido;
     private String vmsjespecialista;
     private String vmsjmoderador;
     private String vusuariocreacion;
     private String vusuariomodificacion;
     private Serializable dfechacreacion;
     private Serializable dfechamodificacion;
     private Set tvinculoImplementacions = new HashSet(0);

    public Timplementacion() {
    }

	
    public Timplementacion(BigDecimal nimplementacionid, Tconocimiento tconocimiento) {
        this.nimplementacionid = nimplementacionid;
        this.tconocimiento = tconocimiento;
    }
    public Timplementacion(BigDecimal nimplementacionid, Tconocimiento tconocimiento, String vdescripcion, String vtitulo, String vcontenido, String vmsjespecialista, String vmsjmoderador, String vusuariocreacion, String vusuariomodificacion, Serializable dfechacreacion, Serializable dfechamodificacion, Set tvinculoImplementacions) {
       this.nimplementacionid = nimplementacionid;
       this.tconocimiento = tconocimiento;
       this.vdescripcion = vdescripcion;
       this.vtitulo = vtitulo;
       this.vcontenido = vcontenido;
       this.vmsjespecialista = vmsjespecialista;
       this.vmsjmoderador = vmsjmoderador;
       this.vusuariocreacion = vusuariocreacion;
       this.vusuariomodificacion = vusuariomodificacion;
       this.dfechacreacion = dfechacreacion;
       this.dfechamodificacion = dfechamodificacion;
       this.tvinculoImplementacions = tvinculoImplementacions;
    }
   
    public BigDecimal getNimplementacionid() {
        return this.nimplementacionid;
    }
    
    public void setNimplementacionid(BigDecimal nimplementacionid) {
        this.nimplementacionid = nimplementacionid;
    }
    public Tconocimiento getTconocimiento() {
        return this.tconocimiento;
    }
    
    public void setTconocimiento(Tconocimiento tconocimiento) {
        this.tconocimiento = tconocimiento;
    }
    public String getVdescripcion() {
        return this.vdescripcion;
    }
    
    public void setVdescripcion(String vdescripcion) {
        this.vdescripcion = vdescripcion;
    }
    public String getVtitulo() {
        return this.vtitulo;
    }
    
    public void setVtitulo(String vtitulo) {
        this.vtitulo = vtitulo;
    }
    public String getVcontenido() {
        return this.vcontenido;
    }
    
    public void setVcontenido(String vcontenido) {
        this.vcontenido = vcontenido;
    }
    public String getVmsjespecialista() {
        return this.vmsjespecialista;
    }
    
    public void setVmsjespecialista(String vmsjespecialista) {
        this.vmsjespecialista = vmsjespecialista;
    }
    public String getVmsjmoderador() {
        return this.vmsjmoderador;
    }
    
    public void setVmsjmoderador(String vmsjmoderador) {
        this.vmsjmoderador = vmsjmoderador;
    }
    public String getVusuariocreacion() {
        return this.vusuariocreacion;
    }
    
    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }
    public String getVusuariomodificacion() {
        return this.vusuariomodificacion;
    }
    
    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }
    public Serializable getDfechacreacion() {
        return this.dfechacreacion;
    }
    
    public void setDfechacreacion(Serializable dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }
    public Serializable getDfechamodificacion() {
        return this.dfechamodificacion;
    }
    
    public void setDfechamodificacion(Serializable dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }
    public Set getTvinculoImplementacions() {
        return this.tvinculoImplementacions;
    }
    
    public void setTvinculoImplementacions(Set tvinculoImplementacions) {
        this.tvinculoImplementacions = tvinculoImplementacions;
    }




}


