package pe.gob.mef.gescon.hibernate.domain;
// Generated 11/09/2015 05:20:07 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * TmaestrodetalleId generated by hbm2java
 */
public class TmaestrodetalleId implements java.io.Serializable {

    private BigDecimal nmaestroid;
    private BigDecimal ndetalleid;

    public TmaestrodetalleId() {
    }

    public TmaestrodetalleId(BigDecimal nmaestroid, BigDecimal ndetalleid) {
        this.nmaestroid = nmaestroid;
        this.ndetalleid = ndetalleid;
    }

    public BigDecimal getNmaestroid() {
        return this.nmaestroid;
    }

    public void setNmaestroid(BigDecimal nmaestroid) {
        this.nmaestroid = nmaestroid;
    }

    public BigDecimal getNdetalleid() {
        return this.ndetalleid;
    }

    public void setNdetalleid(BigDecimal ndetalleid) {
        this.ndetalleid = ndetalleid;
    }

}
