package pe.gob.mef.gescon.hibernate.domain;
// Generated 06/11/2015 11:03:52 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TobservacionHist generated by hbm2java
 */
public class TobservacionHist implements java.io.Serializable {

    private TobservacionHistId id;
    private Thistorial thistorial;
    private String vsumilla;
    private String vusuariomodificacion;
    private BigDecimal ntipo;
    private String vusuariocreacion;
    private Date dfechacreacion;
    private Date dfechamodificacion;

    public TobservacionHist() {
    }

    public TobservacionHist(TobservacionHistId id, Thistorial thistorial) {
        this.id = id;
        this.thistorial = thistorial;
    }

    public TobservacionHist(TobservacionHistId id, Thistorial thistorial, String vsumilla, String vusuariomodificacion, BigDecimal ntipo, String vusuariocreacion, Date dfechacreacion, Date dfechamodificacion) {
        this.id = id;
        this.thistorial = thistorial;
        this.vsumilla = vsumilla;
        this.vusuariomodificacion = vusuariomodificacion;
        this.ntipo = ntipo;
        this.vusuariocreacion = vusuariocreacion;
        this.dfechacreacion = dfechacreacion;
        this.dfechamodificacion = dfechamodificacion;
    }

    public TobservacionHistId getId() {
        return this.id;
    }

    public void setId(TobservacionHistId id) {
        this.id = id;
    }

    public Thistorial getThistorial() {
        return this.thistorial;
    }

    public void setThistorial(Thistorial thistorial) {
        this.thistorial = thistorial;
    }

    public String getVsumilla() {
        return this.vsumilla;
    }

    public void setVsumilla(String vsumilla) {
        this.vsumilla = vsumilla;
    }

    public String getVusuariomodificacion() {
        return this.vusuariomodificacion;
    }

    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }

    public BigDecimal getNtipo() {
        return this.ntipo;
    }

    public void setNtipo(BigDecimal ntipo) {
        this.ntipo = ntipo;
    }

    public String getVusuariocreacion() {
        return this.vusuariocreacion;
    }

    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }

    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    public Date getDfechamodificacion() {
        return this.dfechamodificacion;
    }

    public void setDfechamodificacion(Date dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }

}
