package pe.gob.mef.gescon.hibernate.domain;
// Generated 27/10/2015 06:08:09 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Tobservacion generated by hbm2java
 */
public class Tobservacion  implements java.io.Serializable {


     private TobservacionId id;
     private Tconocimiento tconocimiento;
     private String vsumilla;
     private String vusuariomodificacion;
     private BigDecimal ntipo;
     private String vusuariocreacion;
     private Date dfechacreacion;
     private Date dfechamodificacion;

    public Tobservacion() {
    }

	
    public Tobservacion(TobservacionId id, Tconocimiento tconocimiento) {
        this.id = id;
        this.tconocimiento = tconocimiento;
    }
    public Tobservacion(TobservacionId id, Tconocimiento tconocimiento, String vsumilla, String vusuariomodificacion, BigDecimal ntipo, String vusuariocreacion, Date dfechacreacion, Date dfechamodificacion) {
       this.id = id;
       this.tconocimiento = tconocimiento;
       this.vsumilla = vsumilla;
       this.vusuariomodificacion = vusuariomodificacion;
       this.ntipo = ntipo;
       this.vusuariocreacion = vusuariocreacion;
       this.dfechacreacion = dfechacreacion;
       this.dfechamodificacion = dfechamodificacion;
    }
   
    public TobservacionId getId() {
        return this.id;
    }
    
    public void setId(TobservacionId id) {
        this.id = id;
    }
    public Tconocimiento getTconocimiento() {
        return this.tconocimiento;
    }
    
    public void setTconocimiento(Tconocimiento tconocimiento) {
        this.tconocimiento = tconocimiento;
    }
    public String getVsumilla() {
        return this.vsumilla;
    }
    
    public void setVsumilla(String vsumilla) {
        this.vsumilla = vsumilla;
    }
    public String getVusuariomodificacion() {
        return this.vusuariomodificacion;
    }
    
    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }
    public BigDecimal getNtipo() {
        return this.ntipo;
    }
    
    public void setNtipo(BigDecimal ntipo) {
        this.ntipo = ntipo;
    }
    public String getVusuariocreacion() {
        return this.vusuariocreacion;
    }
    
    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }
    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }
    
    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }
    public Date getDfechamodificacion() {
        return this.dfechamodificacion;
    }
    
    public void setDfechamodificacion(Date dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }




}


