package pe.gob.mef.gescon.hibernate.domain;
// Generated 27/10/2015 06:08:09 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TobservacionId generated by hbm2java
 */
public class TobservacionId  implements java.io.Serializable {


     private BigDecimal nobservacionid;
     private BigDecimal nconocimientoid;

    public TobservacionId() {
    }

    public TobservacionId(BigDecimal nobservacionid, BigDecimal nconocimientoid) {
       this.nobservacionid = nobservacionid;
       this.nconocimientoid = nconocimientoid;
    }
   
    public BigDecimal getNobservacionid() {
        return this.nobservacionid;
    }
    
    public void setNobservacionid(BigDecimal nobservacionid) {
        this.nobservacionid = nobservacionid;
    }
    public BigDecimal getNconocimientoid() {
        return this.nconocimientoid;
    }
    
    public void setNconocimientoid(BigDecimal nconocimientoid) {
        this.nconocimientoid = nconocimientoid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TobservacionId) ) return false;
		 TobservacionId castOther = ( TobservacionId ) other; 
         
		 return ( (this.getNobservacionid()==castOther.getNobservacionid()) || ( this.getNobservacionid()!=null && castOther.getNobservacionid()!=null && this.getNobservacionid().equals(castOther.getNobservacionid()) ) )
 && ( (this.getNconocimientoid()==castOther.getNconocimientoid()) || ( this.getNconocimientoid()!=null && castOther.getNconocimientoid()!=null && this.getNconocimientoid().equals(castOther.getNconocimientoid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNobservacionid() == null ? 0 : this.getNobservacionid().hashCode() );
         result = 37 * result + ( getNconocimientoid() == null ? 0 : this.getNconocimientoid().hashCode() );
         return result;
   }   


}


