package pe.gob.mef.gescon.hibernate.domain;
// Generated 06/11/2015 11:03:52 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * TobservacionHistId generated by hbm2java
 */
public class TobservacionHistId implements java.io.Serializable {

    private BigDecimal nobservacionhid;
    private BigDecimal nconocimientoid;
    private BigDecimal nhistorialid;

    public TobservacionHistId() {
    }

    public TobservacionHistId(BigDecimal nobservacionhid, BigDecimal nconocimientoid, BigDecimal nhistorialid) {
        this.nobservacionhid = nobservacionhid;
        this.nconocimientoid = nconocimientoid;
        this.nhistorialid = nhistorialid;
    }

    public BigDecimal getNobservacionhid() {
        return this.nobservacionhid;
    }

    public void setNobservacionhid(BigDecimal nobservacionhid) {
        this.nobservacionhid = nobservacionhid;
    }

    public BigDecimal getNconocimientoid() {
        return this.nconocimientoid;
    }

    public void setNconocimientoid(BigDecimal nconocimientoid) {
        this.nconocimientoid = nconocimientoid;
    }

    public BigDecimal getNhistorialid() {
        return this.nhistorialid;
    }

    public void setNhistorialid(BigDecimal nhistorialid) {
        this.nhistorialid = nhistorialid;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof TobservacionHistId)) {
            return false;
        }
        TobservacionHistId castOther = (TobservacionHistId) other;

        return ((this.getNobservacionhid() == castOther.getNobservacionhid()) || (this.getNobservacionhid() != null && castOther.getNobservacionhid() != null && this.getNobservacionhid().equals(castOther.getNobservacionhid())))
                && ((this.getNconocimientoid() == castOther.getNconocimientoid()) || (this.getNconocimientoid() != null && castOther.getNconocimientoid() != null && this.getNconocimientoid().equals(castOther.getNconocimientoid())))
                && ((this.getNhistorialid() == castOther.getNhistorialid()) || (this.getNhistorialid() != null && castOther.getNhistorialid() != null && this.getNhistorialid().equals(castOther.getNhistorialid())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getNobservacionhid() == null ? 0 : this.getNobservacionhid().hashCode());
        result = 37 * result + (getNconocimientoid() == null ? 0 : this.getNconocimientoid().hashCode());
        result = 37 * result + (getNhistorialid() == null ? 0 : this.getNhistorialid().hashCode());
        return result;
    }

}
