package pe.gob.mef.gescon.hibernate.domain;
// Generated 12/10/2015 03:16:20 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Tbaselegal generated by hbm2java
 */
public class Toportunidadmejora implements Serializable {

    private BigDecimal noportunidadmejoraid;
    private String vusuariocreacion;
    private String vusuariomodificacion;
    private Date dfechacreacion;
    private Date dfechamodificacion;
    private BigDecimal ngobnacional;
    private BigDecimal ngobregional;
    private BigDecimal ngoblocal;
    private BigDecimal nmancomunidades;
    private BigDecimal nactivo;
    private BigDecimal nestadoid;
    private String vestado;

    public Toportunidadmejora() {
    }

    public Toportunidadmejora(BigDecimal noportunidadmejoraid) {
        this.noportunidadmejoraid = noportunidadmejoraid;
    }

    public Toportunidadmejora(
            BigDecimal noportunidadmejoraid, BigDecimal nestadoid, String vusuariocreacion, String vusuariomodificacion, Date dfechacreacion, Date dfechamodificacion, BigDecimal ngobnacional, BigDecimal ngobregional, BigDecimal ngoblocal, BigDecimal nmancomunidades, BigDecimal nactivo) {
        this.noportunidadmejoraid = noportunidadmejoraid;
        this.nestadoid = nestadoid;
        this.vusuariocreacion = vusuariocreacion;
        this.vusuariomodificacion = vusuariomodificacion;
        this.dfechacreacion = dfechacreacion;
        this.dfechamodificacion = dfechamodificacion;
        this.ngobnacional = ngobnacional;
        this.ngobregional = ngobregional;
        this.ngoblocal = ngoblocal;
        this.nmancomunidades = nmancomunidades;
        this.nactivo = nactivo;
        
    }
 

    public BigDecimal getNestadoid() {
        return nestadoid;
    }

    public void setNestadoid(BigDecimal nestadoid) {
        this.nestadoid = nestadoid;
    }
    

    public String getVusuariocreacion() {
        return this.vusuariocreacion;
    }

    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }

    public String getVusuariomodificacion() {
        return this.vusuariomodificacion;
    }

    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }

    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    public Date getDfechamodificacion() {
        return this.dfechamodificacion;
    }

    public void setDfechamodificacion(Date dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }

    public BigDecimal getNgobnacional() {
        return this.ngobnacional;
    }

    public void setNgobnacional(BigDecimal ngobnacional) {
        this.ngobnacional = ngobnacional;
    }

    public BigDecimal getNgobregional() {
        return this.ngobregional;
    }

    public void setNgobregional(BigDecimal ngobregional) {
        this.ngobregional = ngobregional;
    }

    public BigDecimal getNgoblocal() {
        return this.ngoblocal;
    }

    public void setNgoblocal(BigDecimal ngoblocal) {
        this.ngoblocal = ngoblocal;
    }

    public BigDecimal getNmancomunidades() {
        return this.nmancomunidades;
    }

    public void setNmancomunidades(BigDecimal nmancomunidades) {
        this.nmancomunidades = nmancomunidades;
    }

    public BigDecimal getNactivo() {
        return this.nactivo;
    }

    public void setNactivo(BigDecimal nactivo) {
        this.nactivo = nactivo;
    }

    public BigDecimal getNoportunidadmejoraid() {
        return noportunidadmejoraid;
    }

    public void setNoportunidadmejoraid(BigDecimal noportunidadmejoraid) {
        this.noportunidadmejoraid = noportunidadmejoraid;
    }

    public String getVestado() {
        return vestado;
    }

    public void setVestado(String vestado) {
        this.vestado = vestado;
    }

    
}
