package pe.gob.mef.gescon.hibernate.domain;
// Generated 11/09/2015 05:20:07 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Tpass generated by hbm2java
 */
public class Tpass  implements java.io.Serializable {


     private TpassId id;
     private Mtuser mtuser;
     private String vclave;
     private BigDecimal nusuariocreacion;
     private Date dfechacreacion;

    public Tpass() {
    }

	
    public Tpass(TpassId id, Mtuser mtuser) {
        this.id = id;
        this.mtuser = mtuser;
    }
    public Tpass(TpassId id, Mtuser mtuser, String vclave, BigDecimal nusuariocreacion, Date dfechacreacion) {
       this.id = id;
       this.mtuser = mtuser;
       this.vclave = vclave;
       this.nusuariocreacion = nusuariocreacion;
       this.dfechacreacion = dfechacreacion;
    }
   
    public TpassId getId() {
        return this.id;
    }
    
    public void setId(TpassId id) {
        this.id = id;
    }
    public Mtuser getMtuser() {
        return this.mtuser;
    }
    
    public void setMtuser(Mtuser mtuser) {
        this.mtuser = mtuser;
    }
    public String getVclave() {
        return this.vclave;
    }
    
    public void setVclave(String vclave) {
        this.vclave = vclave;
    }
    public BigDecimal getNusuariocreacion() {
        return this.nusuariocreacion;
    }
    
    public void setNusuariocreacion(BigDecimal nusuariocreacion) {
        this.nusuariocreacion = nusuariocreacion;
    }
    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }
    
    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }




}


