package pe.gob.mef.gescon.hibernate.domain;
// Generated 06/11/2015 11:03:52 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * TpassId generated by hbm2java
 */
public class TpassId implements java.io.Serializable {

    private BigDecimal npassid;
    private BigDecimal nusuarioid;

    public TpassId() {
    }

    public TpassId(BigDecimal npassid, BigDecimal nusuarioid) {
        this.npassid = npassid;
        this.nusuarioid = nusuarioid;
    }

    public BigDecimal getNpassid() {
        return this.npassid;
    }

    public void setNpassid(BigDecimal npassid) {
        this.npassid = npassid;
    }

    public BigDecimal getNusuarioid() {
        return this.nusuarioid;
    }

    public void setNusuarioid(BigDecimal nusuarioid) {
        this.nusuarioid = nusuarioid;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof TpassId)) {
            return false;
        }
        TpassId castOther = (TpassId) other;

        return ((this.getNpassid() == castOther.getNpassid()) || (this.getNpassid() != null && castOther.getNpassid() != null && this.getNpassid().equals(castOther.getNpassid())))
                && ((this.getNusuarioid() == castOther.getNusuarioid()) || (this.getNusuarioid() != null && castOther.getNusuarioid() != null && this.getNusuarioid().equals(castOther.getNusuarioid())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getNpassid() == null ? 0 : this.getNpassid().hashCode());
        result = 37 * result + (getNusuarioid() == null ? 0 : this.getNusuarioid().hashCode());
        return result;
    }

}
