package pe.gob.mef.gescon.hibernate.domain;
// Generated 11/09/2015 05:20:07 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * TpoliticaPerfil generated by hbm2java
 */
public class TpoliticaPerfil  implements java.io.Serializable {


     private TpoliticaPerfilId id;
     private Mtperfil mtperfil;
     private Mtpolitica mtpolitica;
     private BigDecimal nusuariomod;
     private BigDecimal nusuariocreacion;
     private Date dfechacreacion;

    public TpoliticaPerfil() {
    }

	
    public TpoliticaPerfil(TpoliticaPerfilId id, Mtperfil mtperfil, Mtpolitica mtpolitica) {
        this.id = id;
        this.mtperfil = mtperfil;
        this.mtpolitica = mtpolitica;
    }
    public TpoliticaPerfil(TpoliticaPerfilId id, Mtperfil mtperfil, Mtpolitica mtpolitica, BigDecimal nusuariomod, BigDecimal nusuariocreacion, Date dfechacreacion) {
       this.id = id;
       this.mtperfil = mtperfil;
       this.mtpolitica = mtpolitica;
       this.nusuariomod = nusuariomod;
       this.nusuariocreacion = nusuariocreacion;
       this.dfechacreacion = dfechacreacion;
    }
   
    public TpoliticaPerfilId getId() {
        return this.id;
    }
    
    public void setId(TpoliticaPerfilId id) {
        this.id = id;
    }
    public Mtperfil getMtperfil() {
        return this.mtperfil;
    }
    
    public void setMtperfil(Mtperfil mtperfil) {
        this.mtperfil = mtperfil;
    }
    public Mtpolitica getMtpolitica() {
        return this.mtpolitica;
    }
    
    public void setMtpolitica(Mtpolitica mtpolitica) {
        this.mtpolitica = mtpolitica;
    }
    public BigDecimal getNusuariomod() {
        return this.nusuariomod;
    }
    
    public void setNusuariomod(BigDecimal nusuariomod) {
        this.nusuariomod = nusuariomod;
    }
    public BigDecimal getNusuariocreacion() {
        return this.nusuariocreacion;
    }
    
    public void setNusuariocreacion(BigDecimal nusuariocreacion) {
        this.nusuariocreacion = nusuariocreacion;
    }
    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }
    
    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }




}


