package pe.gob.mef.gescon.hibernate.domain;
// Generated 06/11/2015 11:03:52 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * TpoliticaPerfilId generated by hbm2java
 */
public class TpoliticaPerfilId implements java.io.Serializable {

    private BigDecimal npoliticaid;
    private BigDecimal nperfilid;

    public TpoliticaPerfilId() {
    }

    public TpoliticaPerfilId(BigDecimal npoliticaid, BigDecimal nperfilid) {
        this.npoliticaid = npoliticaid;
        this.nperfilid = nperfilid;
    }

    public BigDecimal getNpoliticaid() {
        return this.npoliticaid;
    }

    public void setNpoliticaid(BigDecimal npoliticaid) {
        this.npoliticaid = npoliticaid;
    }

    public BigDecimal getNperfilid() {
        return this.nperfilid;
    }

    public void setNperfilid(BigDecimal nperfilid) {
        this.nperfilid = nperfilid;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof TpoliticaPerfilId)) {
            return false;
        }
        TpoliticaPerfilId castOther = (TpoliticaPerfilId) other;

        return ((this.getNpoliticaid() == castOther.getNpoliticaid()) || (this.getNpoliticaid() != null && castOther.getNpoliticaid() != null && this.getNpoliticaid().equals(castOther.getNpoliticaid())))
                && ((this.getNperfilid() == castOther.getNperfilid()) || (this.getNperfilid() != null && castOther.getNperfilid() != null && this.getNperfilid().equals(castOther.getNperfilid())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getNpoliticaid() == null ? 0 : this.getNpoliticaid().hashCode());
        result = 37 * result + (getNperfilid() == null ? 0 : this.getNperfilid().hashCode());
        return result;
    }

}
