package pe.gob.mef.gescon.hibernate.domain;
// Generated 11/09/2015 05:20:07 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * TpoliticaPerfil generated by hbm2java
 */
public class TpoliticaPerfil implements java.io.Serializable {

    private TpoliticaPerfilId id;
    private Mtperfil mtperfil;
    private Mtpolitica mtpolitica;
    private String vusuariomodificacion;
    private String vusuariocreacion;
    private Date dfechacreacion;
    private Date dfechamodificacion;

    public TpoliticaPerfil() {
    }

    public TpoliticaPerfil(TpoliticaPerfilId id, Mtperfil mtperfil, Mtpolitica mtpolitica) {
        this.id = id;
        this.mtperfil = mtperfil;
        this.mtpolitica = mtpolitica;
    }

    public TpoliticaPerfil(TpoliticaPerfilId id, Mtperfil mtperfil, Mtpolitica mtpolitica, String vusuariomodificacion, String vusuariocreacion, Date dfechacreacion) {
        this.id = id;
        this.mtperfil = mtperfil;
        this.mtpolitica = mtpolitica;
        this.vusuariomodificacion = vusuariomodificacion;
        this.vusuariocreacion = vusuariocreacion;
        this.dfechacreacion = dfechacreacion;
    }

    public TpoliticaPerfilId getId() {
        return this.id;
    }

    public void setId(TpoliticaPerfilId id) {
        this.id = id;
    }

    public Mtperfil getMtperfil() {
        return this.mtperfil;
    }

    public void setMtperfil(Mtperfil mtperfil) {
        this.mtperfil = mtperfil;
    }

    public Mtpolitica getMtpolitica() {
        return this.mtpolitica;
    }

    public void setMtpolitica(Mtpolitica mtpolitica) {
        this.mtpolitica = mtpolitica;
    }

    public String getVusuariomodificacion() {
        return this.vusuariomodificacion;
    }

    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }

    public String getVusuariocreacion() {
        return this.vusuariocreacion;
    }

    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }

    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    public Date getDfechamodificacion() {
        return dfechamodificacion;
    }

    public void setDfechamodificacion(Date dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }

}
