package pe.gob.mef.gescon.hibernate.domain;
// Generated 06/11/2015 11:03:52 AM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Tpregunta generated by hbm2java
 */
public class Tpregunta implements java.io.Serializable {

    private BigDecimal npreguntaid;
    private Mtcategoria mtcategoria;
    private Mtsituacion mtsituacion;
    private String vasunto;
    private String vdetalle;
    private BigDecimal nentidadid;
    private String vdatoadicional;
    private String vrespuesta;
    private String vmsjusuario2;
    private String vmsjespecialista;
    private BigDecimal nactivo;
    private String vmsjmoderador;
    private String vmsjusuario1;
    private String vusuariocreacion;
    private String vusuariomodificacion;
    private Date dfechacreacion;
    private Date dfechamodificacion;

    public Tpregunta() {
    }

    public Tpregunta(BigDecimal npreguntaid, Mtcategoria mtcategoria, Mtsituacion mtsituacion) {
        this.npreguntaid = npreguntaid;
        this.mtcategoria = mtcategoria;
        this.mtsituacion = mtsituacion;
    }

    public Tpregunta(BigDecimal npreguntaid, Mtcategoria mtcategoria, Mtsituacion mtsituacion, String vasunto, String vdetalle, BigDecimal nentidadid, String vdatoadicional, String vrespuesta, String vmsjusuario2, String vmsjespecialista, BigDecimal nactivo, String vmsjmoderador, String vmsjusuario1, String vusuariocreacion, String vusuariomodificacion, Date dfechacreacion, Date dfechamodificacion) {
        this.npreguntaid = npreguntaid;
        this.mtcategoria = mtcategoria;
        this.mtsituacion = mtsituacion;
        this.vasunto = vasunto;
        this.vdetalle = vdetalle;
        this.nentidadid = nentidadid;
        this.vdatoadicional = vdatoadicional;
        this.vrespuesta = vrespuesta;
        this.vmsjusuario2 = vmsjusuario2;
        this.vmsjespecialista = vmsjespecialista;
        this.nactivo = nactivo;
        this.vmsjmoderador = vmsjmoderador;
        this.vmsjusuario1 = vmsjusuario1;
        this.vusuariocreacion = vusuariocreacion;
        this.vusuariomodificacion = vusuariomodificacion;
        this.dfechacreacion = dfechacreacion;
        this.dfechamodificacion = dfechamodificacion;
    }

    public BigDecimal getNpreguntaid() {
        return this.npreguntaid;
    }

    public void setNpreguntaid(BigDecimal npreguntaid) {
        this.npreguntaid = npreguntaid;
    }

    public Mtcategoria getMtcategoria() {
        return this.mtcategoria;
    }

    public void setMtcategoria(Mtcategoria mtcategoria) {
        this.mtcategoria = mtcategoria;
    }

    public Mtsituacion getMtsituacion() {
        return this.mtsituacion;
    }

    public void setMtsituacion(Mtsituacion mtsituacion) {
        this.mtsituacion = mtsituacion;
    }

    public String getVasunto() {
        return this.vasunto;
    }

    public void setVasunto(String vasunto) {
        this.vasunto = vasunto;
    }

    public String getVdetalle() {
        return this.vdetalle;
    }

    public void setVdetalle(String vdetalle) {
        this.vdetalle = vdetalle;
    }

    public BigDecimal getNentidadid() {
        return this.nentidadid;
    }

    public void setNentidadid(BigDecimal nentidadid) {
        this.nentidadid = nentidadid;
    }

    public String getVdatoadicional() {
        return this.vdatoadicional;
    }

    public void setVdatoadicional(String vdatoadicional) {
        this.vdatoadicional = vdatoadicional;
    }

    public String getVrespuesta() {
        return this.vrespuesta;
    }

    public void setVrespuesta(String vrespuesta) {
        this.vrespuesta = vrespuesta;
    }

    public String getVmsjusuario2() {
        return this.vmsjusuario2;
    }

    public void setVmsjusuario2(String vmsjusuario2) {
        this.vmsjusuario2 = vmsjusuario2;
    }

    public String getVmsjespecialista() {
        return this.vmsjespecialista;
    }

    public void setVmsjespecialista(String vmsjespecialista) {
        this.vmsjespecialista = vmsjespecialista;
    }

    public BigDecimal getNactivo() {
        return this.nactivo;
    }

    public void setNactivo(BigDecimal nactivo) {
        this.nactivo = nactivo;
    }

    public String getVmsjmoderador() {
        return this.vmsjmoderador;
    }

    public void setVmsjmoderador(String vmsjmoderador) {
        this.vmsjmoderador = vmsjmoderador;
    }

    public String getVmsjusuario1() {
        return this.vmsjusuario1;
    }

    public void setVmsjusuario1(String vmsjusuario1) {
        this.vmsjusuario1 = vmsjusuario1;
    }

    public String getVusuariocreacion() {
        return this.vusuariocreacion;
    }

    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }

    public String getVusuariomodificacion() {
        return this.vusuariomodificacion;
    }

    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }

    public Serializable getDfechacreacion() {
        return this.dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    public Serializable getDfechamodificacion() {
        return this.dfechamodificacion;
    }

    public void setDfechamodificacion(Date dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }

}
