package pe.gob.mef.gescon.hibernate.domain;
// Generated 06/11/2015 11:03:52 AM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * TseccionHist generated by hbm2java
 */
public class TseccionHist implements java.io.Serializable {

    private TseccionHistId id;
    private Thistorial thistorial;
    private String vtitulo;
    private String vruta;
    private BigDecimal norden;
    private String vusuariocreacion;
    private Date dfechacreacion;
    private String vusuariomodificacion;
    private Date dfechamodificacion;

    public TseccionHist() {
    }

    public TseccionHist(TseccionHistId id, Thistorial thistorial) {
        this.id = id;
        this.thistorial = thistorial;
    }

    public TseccionHist(TseccionHistId id, Thistorial thistorial, String vtitulo, String vruta, BigDecimal norden, String vusuariocreacion, Date dfechacreacion, String vusuariomodificacion, Date dfechamodificacion) {
        this.id = id;
        this.thistorial = thistorial;
        this.vtitulo = vtitulo;
        this.vruta = vruta;
        this.norden = norden;
        this.vusuariocreacion = vusuariocreacion;
        this.dfechacreacion = dfechacreacion;
        this.vusuariomodificacion = vusuariomodificacion;
        this.dfechamodificacion = dfechamodificacion;
    }

    public TseccionHistId getId() {
        return this.id;
    }

    public void setId(TseccionHistId id) {
        this.id = id;
    }

    public Thistorial getThistorial() {
        return this.thistorial;
    }

    public void setThistorial(Thistorial thistorial) {
        this.thistorial = thistorial;
    }

    public String getVtitulo() {
        return this.vtitulo;
    }

    public void setVtitulo(String vtitulo) {
        this.vtitulo = vtitulo;
    }

    public String getVruta() {
        return this.vruta;
    }

    public void setVruta(String vruta) {
        this.vruta = vruta;
    }

    public BigDecimal getNorden() {
        return this.norden;
    }

    public void setNorden(BigDecimal norden) {
        this.norden = norden;
    }

    public String getVusuariocreacion() {
        return this.vusuariocreacion;
    }

    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }

    public Serializable getDfechacreacion() {
        return this.dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    public String getVusuariomodificacion() {
        return this.vusuariomodificacion;
    }

    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }

    public Serializable getDfechamodificacion() {
        return this.dfechamodificacion;
    }

    public void setDfechamodificacion(Date dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }

}
