package pe.gob.mef.gescon.hibernate.domain;
// Generated 06/11/2015 11:03:52 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * TseccionHistId generated by hbm2java
 */
public class TseccionHistId implements java.io.Serializable {

    private BigDecimal nseccionhid;
    private BigDecimal nconocimientoid;
    private BigDecimal nhistorialid;

    public TseccionHistId() {
    }

    public TseccionHistId(BigDecimal nseccionhid, BigDecimal nconocimientoid, BigDecimal nhistorialid) {
        this.nseccionhid = nseccionhid;
        this.nconocimientoid = nconocimientoid;
        this.nhistorialid = nhistorialid;
    }

    public BigDecimal getNseccionhid() {
        return this.nseccionhid;
    }

    public void setNseccionhid(BigDecimal nseccionhid) {
        this.nseccionhid = nseccionhid;
    }

    public BigDecimal getNconocimientoid() {
        return this.nconocimientoid;
    }

    public void setNconocimientoid(BigDecimal nconocimientoid) {
        this.nconocimientoid = nconocimientoid;
    }

    public BigDecimal getNhistorialid() {
        return this.nhistorialid;
    }

    public void setNhistorialid(BigDecimal nhistorialid) {
        this.nhistorialid = nhistorialid;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof TseccionHistId)) {
            return false;
        }
        TseccionHistId castOther = (TseccionHistId) other;

        return ((this.getNseccionhid() == castOther.getNseccionhid()) || (this.getNseccionhid() != null && castOther.getNseccionhid() != null && this.getNseccionhid().equals(castOther.getNseccionhid())))
                && ((this.getNconocimientoid() == castOther.getNconocimientoid()) || (this.getNconocimientoid() != null && castOther.getNconocimientoid() != null && this.getNconocimientoid().equals(castOther.getNconocimientoid())))
                && ((this.getNhistorialid() == castOther.getNhistorialid()) || (this.getNhistorialid() != null && castOther.getNhistorialid() != null && this.getNhistorialid().equals(castOther.getNhistorialid())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getNseccionhid() == null ? 0 : this.getNseccionhid().hashCode());
        result = 37 * result + (getNconocimientoid() == null ? 0 : this.getNconocimientoid().hashCode());
        result = 37 * result + (getNhistorialid() == null ? 0 : this.getNhistorialid().hashCode());
        return result;
    }

}
