package pe.gob.mef.gescon.hibernate.domain;
// Generated 06/11/2015 11:03:52 AM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;

/**
 * TuserPerfil generated by hbm2java
 */
public class TuserPerfil implements java.io.Serializable {

    private TuserPerfilId id;
    private Mtperfil mtperfil;
    private Mtuser mtuser;
    private String vusuariomodificacion;
    private String vusuariocreacion;
    private Date dfechacreacion;
    private Date dfechamodificacion;

    public TuserPerfil() {
    }

    public TuserPerfil(TuserPerfilId id, Mtperfil mtperfil, Mtuser mtuser) {
        this.id = id;
        this.mtperfil = mtperfil;
        this.mtuser = mtuser;
    }

    public TuserPerfil(TuserPerfilId id, Mtperfil mtperfil, Mtuser mtuser, String vusuariomodificacion, String vusuariocreacion, Date dfechacreacion, Date dfechamodificacion) {
        this.id = id;
        this.mtperfil = mtperfil;
        this.mtuser = mtuser;
        this.vusuariomodificacion = vusuariomodificacion;
        this.vusuariocreacion = vusuariocreacion;
        this.dfechacreacion = dfechacreacion;
        this.dfechamodificacion = dfechamodificacion;
    }

    public TuserPerfilId getId() {
        return this.id;
    }

    public void setId(TuserPerfilId id) {
        this.id = id;
    }

    public Mtperfil getMtperfil() {
        return this.mtperfil;
    }

    public void setMtperfil(Mtperfil mtperfil) {
        this.mtperfil = mtperfil;
    }

    public Mtuser getMtuser() {
        return this.mtuser;
    }

    public void setMtuser(Mtuser mtuser) {
        this.mtuser = mtuser;
    }

    public String getVusuariomodificacion() {
        return this.vusuariomodificacion;
    }

    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }

    public String getVusuariocreacion() {
        return this.vusuariocreacion;
    }

    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }

    public Serializable getDfechacreacion() {
        return this.dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    public Serializable getDfechamodificacion() {
        return this.dfechamodificacion;
    }

    public void setDfechamodificacion(Date dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }

}
