package pe.gob.mef.gescon.hibernate.domain;
// Generated 11/09/2015 05:20:07 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * TuserPerfil generated by hbm2java
 */
public class TuserPerfil  implements java.io.Serializable {


     private TuserPerfilId id;
     private Mtperfil mtperfil;
     private Mtuser mtuser;
     private BigDecimal nusuariomod;
     private String nusuariocreacion;
     private Date dfechacreacion;

    public TuserPerfil() {
    }

	
    public TuserPerfil(TuserPerfilId id, Mtperfil mtperfil, Mtuser mtuser) {
        this.id = id;
        this.mtperfil = mtperfil;
        this.mtuser = mtuser;
    }
    public TuserPerfil(TuserPerfilId id, Mtperfil mtperfil, Mtuser mtuser, BigDecimal nusuariomod, String nusuariocreacion, Date dfechacreacion) {
       this.id = id;
       this.mtperfil = mtperfil;
       this.mtuser = mtuser;
       this.nusuariomod = nusuariomod;
       this.nusuariocreacion = nusuariocreacion;
       this.dfechacreacion = dfechacreacion;
    }
   
    public TuserPerfilId getId() {
        return this.id;
    }
    
    public void setId(TuserPerfilId id) {
        this.id = id;
    }
    public Mtperfil getMtperfil() {
        return this.mtperfil;
    }
    
    public void setMtperfil(Mtperfil mtperfil) {
        this.mtperfil = mtperfil;
    }
    public Mtuser getMtuser() {
        return this.mtuser;
    }
    
    public void setMtuser(Mtuser mtuser) {
        this.mtuser = mtuser;
    }
    public BigDecimal getNusuariomod() {
        return this.nusuariomod;
    }
    
    public void setNusuariomod(BigDecimal nusuariomod) {
        this.nusuariomod = nusuariomod;
    }
    public String getNusuariocreacion() {
        return this.nusuariocreacion;
    }
    
    public void setNusuariocreacion(String nusuariocreacion) {
        this.nusuariocreacion = nusuariocreacion;
    }
    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }
    
    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }




}


