package pe.gob.mef.gescon.hibernate.domain;
// Generated 11/09/2015 05:20:07 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TuserPerfilId generated by hbm2java
 */
public class TuserPerfilId  implements java.io.Serializable {


     private BigDecimal nperfilid;
     private BigDecimal nusuarioid;

    public TuserPerfilId() {
    }

    public TuserPerfilId(BigDecimal nperfilid, BigDecimal nusuarioid) {
       this.nperfilid = nperfilid;
       this.nusuarioid = nusuarioid;
    }
   
    public BigDecimal getNperfilid() {
        return this.nperfilid;
    }
    
    public void setNperfilid(BigDecimal nperfilid) {
        this.nperfilid = nperfilid;
    }
    public BigDecimal getNusuarioid() {
        return this.nusuarioid;
    }
    
    public void setNusuarioid(BigDecimal nusuarioid) {
        this.nusuarioid = nusuarioid;
    }




}


