package pe.gob.mef.gescon.hibernate.domain;
// Generated 27/10/2015 06:08:09 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * TvincHistId generated by hbm2java
 */
public class TvincHistId  implements java.io.Serializable {

     private BigDecimal nvinculohid;
     private BigDecimal nhistorialid;
     private BigDecimal nconocimientoid;

    public TvincHistId() {
    }

    public TvincHistId(BigDecimal nvinculohid, BigDecimal nhistorialid, BigDecimal nconocimientoid) {
       this.nvinculohid = nvinculohid;
       this.nhistorialid = nhistorialid;
       this.nconocimientoid = nconocimientoid;
    }
   
    public BigDecimal getNvinculohid() {
        return this.nvinculohid;
    }
    
    public void setNvinculohid(BigDecimal nvinculohid) {
        this.nvinculohid = nvinculohid;
    }
    public BigDecimal getNhistorialid() {
        return this.nhistorialid;
    }
    
    public void setNhistorialid(BigDecimal nhistorialid) {
        this.nhistorialid = nhistorialid;
    }
    public BigDecimal getNconocimientoid() {
        return this.nconocimientoid;
    }
    
    public void setNconocimientoid(BigDecimal nconocimientoid) {
        this.nconocimientoid = nconocimientoid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TvincHistId) ) return false;
		 TvincHistId castOther = ( TvincHistId ) other; 
         
		 return ( (this.getNvinculohid()==castOther.getNvinculohid()) || ( this.getNvinculohid()!=null && castOther.getNvinculohid()!=null && this.getNvinculohid().equals(castOther.getNvinculohid()) ) )
 && ( (this.getNhistorialid()==castOther.getNhistorialid()) || ( this.getNhistorialid()!=null && castOther.getNhistorialid()!=null && this.getNhistorialid().equals(castOther.getNhistorialid()) ) )
 && ( (this.getNconocimientoid()==castOther.getNconocimientoid()) || ( this.getNconocimientoid()!=null && castOther.getNconocimientoid()!=null && this.getNconocimientoid().equals(castOther.getNconocimientoid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNvinculohid() == null ? 0 : this.getNvinculohid().hashCode() );
         result = 37 * result + ( getNhistorialid() == null ? 0 : this.getNhistorialid().hashCode() );
         result = 37 * result + ( getNconocimientoid() == null ? 0 : this.getNconocimientoid().hashCode() );
         return result;
   }   


}


