package pe.gob.mef.gescon.hibernate.domain;
// Generated 11/09/2015 05:20:07 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Tvinculo generated by hbm2java
 */
public class Tvinculo  implements java.io.Serializable {


     private TvinculoId id;
     private Tconocimiento tconocimiento;
     private BigDecimal nconocimientovinc;
     private BigDecimal nusuariomod;
     private BigDecimal nusuariocreacion;
     private Date dfechacreacion;

    public Tvinculo() {
    }

	
    public Tvinculo(TvinculoId id, Tconocimiento tconocimiento) {
        this.id = id;
        this.tconocimiento = tconocimiento;
    }
    public Tvinculo(TvinculoId id, Tconocimiento tconocimiento, BigDecimal nconocimientovinc, BigDecimal nusuariomod, BigDecimal nusuariocreacion, Date dfechacreacion) {
       this.id = id;
       this.tconocimiento = tconocimiento;
       this.nconocimientovinc = nconocimientovinc;
       this.nusuariomod = nusuariomod;
       this.nusuariocreacion = nusuariocreacion;
       this.dfechacreacion = dfechacreacion;
    }
   
    public TvinculoId getId() {
        return this.id;
    }
    
    public void setId(TvinculoId id) {
        this.id = id;
    }
    public Tconocimiento getTconocimiento() {
        return this.tconocimiento;
    }
    
    public void setTconocimiento(Tconocimiento tconocimiento) {
        this.tconocimiento = tconocimiento;
    }
    public BigDecimal getNconocimientovinc() {
        return this.nconocimientovinc;
    }
    
    public void setNconocimientovinc(BigDecimal nconocimientovinc) {
        this.nconocimientovinc = nconocimientovinc;
    }
    public BigDecimal getNusuariomod() {
        return this.nusuariomod;
    }
    
    public void setNusuariomod(BigDecimal nusuariomod) {
        this.nusuariomod = nusuariomod;
    }
    public BigDecimal getNusuariocreacion() {
        return this.nusuariocreacion;
    }
    
    public void setNusuariocreacion(BigDecimal nusuariocreacion) {
        this.nusuariocreacion = nusuariocreacion;
    }
    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }
    
    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }




}


