package pe.gob.mef.gescon.hibernate.domain;
// Generated 06/11/2015 11:03:52 AM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Tvinculo generated by hbm2java
 */
public class TvinculoPregunta implements java.io.Serializable {

    private BigDecimal nvinculoid;
    private BigDecimal npreguntaid;
    private BigDecimal nconocimientovinc;
    private BigDecimal ntipoconocimientovinc;
    private String vusuariomodificacion;
    private Date dfechacreacion;
    private Date dfechamodificacion;
    private String vusuariocreacion;

    public TvinculoPregunta() {
    }

    public TvinculoPregunta(BigDecimal nvinculoid) {
        this.nvinculoid = nvinculoid;
    }

    public TvinculoPregunta(BigDecimal nvinculoid, BigDecimal npreguntaid, BigDecimal nconocimientovinc, BigDecimal ntipoconocimientovinc, String vusuariomodificacion, Date dfechacreacion, Date dfechamodificacion, String vusuariocreacion) {
        this.nvinculoid = nvinculoid;
        this.npreguntaid = npreguntaid;
        this.nconocimientovinc = nconocimientovinc;
        this.ntipoconocimientovinc = ntipoconocimientovinc;
        this.vusuariomodificacion = vusuariomodificacion;
        this.dfechacreacion = dfechacreacion;
        this.dfechamodificacion = dfechamodificacion;
        this.vusuariocreacion = vusuariocreacion;
    }

    public BigDecimal getNvinculoid() {
        return this.nvinculoid;
    }

    public void setNvinculoid(BigDecimal nvinculoid) {
        this.nvinculoid = nvinculoid;
    }

    /**
     * @return the npreguntaid
     */
    public BigDecimal getNpreguntaid() {
        return npreguntaid;
    }

    /**
     * @param npreguntaid the npreguntaid to set
     */
    public void setNpreguntaid(BigDecimal npreguntaid) {
        this.npreguntaid = npreguntaid;
    }

    /**
     * @return the nconocimientovinc
     */
    public BigDecimal getNconocimientovinc() {
        return nconocimientovinc;
    }

    /**
     * @param nconocimientovinc the nconocimientovinc to set
     */
    public void setNconocimientovinc(BigDecimal nconocimientovinc) {
        this.nconocimientovinc = nconocimientovinc;
    }



    

    public BigDecimal getNtipoconocimientovinc() {
        return ntipoconocimientovinc;
    }

    public void setNtipoconocimientovinc(BigDecimal ntipoconocimientovinc) {
        this.ntipoconocimientovinc = ntipoconocimientovinc;
    }

    public String getVusuariomodificacion() {
        return this.vusuariomodificacion;
    }

    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }

    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    public Date getDfechamodificacion() {
        return this.dfechamodificacion;
    }

    public void setDfechamodificacion(Date dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }

    public String getVusuariocreacion() {
        return this.vusuariocreacion;
    }

    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }

}
