package pe.gob.mef.gescon.hibernate.domain;
// Generated 06/11/2015 11:03:52 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * TvinculoBaselegalId generated by hbm2java
 */
public class TvinculoBaselegalId implements java.io.Serializable {

    private BigDecimal nvinculoid;
    private BigDecimal nbaselegalid;

    public TvinculoBaselegalId() {
    }

    public TvinculoBaselegalId(BigDecimal nvinculoid, BigDecimal nbaselegalid) {
        this.nvinculoid = nvinculoid;
        this.nbaselegalid = nbaselegalid;
    }

    public BigDecimal getNvinculoid() {
        return this.nvinculoid;
    }

    public void setNvinculoid(BigDecimal nvinculoid) {
        this.nvinculoid = nvinculoid;
    }

    public BigDecimal getNbaselegalid() {
        return this.nbaselegalid;
    }

    public void setNbaselegalid(BigDecimal nbaselegalid) {
        this.nbaselegalid = nbaselegalid;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof TvinculoBaselegalId)) {
            return false;
        }
        TvinculoBaselegalId castOther = (TvinculoBaselegalId) other;

        return ((this.getNvinculoid() == castOther.getNvinculoid()) || (this.getNvinculoid() != null && castOther.getNvinculoid() != null && this.getNvinculoid().equals(castOther.getNvinculoid())))
                && ((this.getNbaselegalid() == castOther.getNbaselegalid()) || (this.getNbaselegalid() != null && castOther.getNbaselegalid() != null && this.getNbaselegalid().equals(castOther.getNbaselegalid())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getNvinculoid() == null ? 0 : this.getNvinculoid().hashCode());
        result = 37 * result + (getNbaselegalid() == null ? 0 : this.getNbaselegalid().hashCode());
        return result;
    }

}
