package pe.gob.mef.gescon.hibernate.domain;
// Generated 11/09/2015 05:20:07 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TvincHistId generated by hbm2java
 */
public class TvincHistId  implements java.io.Serializable {


     private BigDecimal nvinculohid;
     private BigDecimal nhistorialid;
     private BigDecimal nconocimientoid;
     private BigDecimal ntpoconocimientoid;

    public TvincHistId() {
    }

    public TvincHistId(BigDecimal nvinculohid, BigDecimal nhistorialid, BigDecimal nconocimientoid, BigDecimal ntpoconocimientoid) {
       this.nvinculohid = nvinculohid;
       this.nhistorialid = nhistorialid;
       this.nconocimientoid = nconocimientoid;
       this.ntpoconocimientoid = ntpoconocimientoid;
    }
   
    public BigDecimal getNvinculohid() {
        return this.nvinculohid;
    }
    
    public void setNvinculohid(BigDecimal nvinculohid) {
        this.nvinculohid = nvinculohid;
    }
    public BigDecimal getNhistorialid() {
        return this.nhistorialid;
    }
    
    public void setNhistorialid(BigDecimal nhistorialid) {
        this.nhistorialid = nhistorialid;
    }
    public BigDecimal getNconocimientoid() {
        return this.nconocimientoid;
    }
    
    public void setNconocimientoid(BigDecimal nconocimientoid) {
        this.nconocimientoid = nconocimientoid;
    }
    public BigDecimal getNtpoconocimientoid() {
        return this.ntpoconocimientoid;
    }
    
    public void setNtpoconocimientoid(BigDecimal ntpoconocimientoid) {
        this.ntpoconocimientoid = ntpoconocimientoid;
    }




}


