package pe.gob.mef.gescon.hibernate.domain;
// Generated 27/10/2015 06:08:09 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TvinculoId generated by hbm2java
 */
public class TvinculoId  implements java.io.Serializable {


     private BigDecimal nvinculoid;
     private BigDecimal nconocimientoid;

    public TvinculoId() {
    }

    public TvinculoId(BigDecimal nvinculoid, BigDecimal nconocimientoid) {
       this.nvinculoid = nvinculoid;
       this.nconocimientoid = nconocimientoid;
    }
   
    public BigDecimal getNvinculoid() {
        return this.nvinculoid;
    }
    
    public void setNvinculoid(BigDecimal nvinculoid) {
        this.nvinculoid = nvinculoid;
    }
    public BigDecimal getNconocimientoid() {
        return this.nconocimientoid;
    }
    
    public void setNconocimientoid(BigDecimal nconocimientoid) {
        this.nconocimientoid = nconocimientoid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TvinculoId) ) return false;
		 TvinculoId castOther = ( TvinculoId ) other; 
         
		 return ( (this.getNvinculoid()==castOther.getNvinculoid()) || ( this.getNvinculoid()!=null && castOther.getNvinculoid()!=null && this.getNvinculoid().equals(castOther.getNvinculoid()) ) )
 && ( (this.getNconocimientoid()==castOther.getNconocimientoid()) || ( this.getNconocimientoid()!=null && castOther.getNconocimientoid()!=null && this.getNconocimientoid().equals(castOther.getNconocimientoid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNvinculoid() == null ? 0 : this.getNvinculoid().hashCode() );
         result = 37 * result + ( getNconocimientoid() == null ? 0 : this.getNconocimientoid().hashCode() );
         return result;
   }   


}


