package pe.gob.mef.gescon.hibernate.domain;
// Generated 06/11/2015 11:03:52 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TvinculoHist generated by hbm2java
 */
public class TvinculoHist implements java.io.Serializable {

    private TvinculoHistId id;
    private Thistorial thistorial;
    private BigDecimal nconocimientovinc;
    private String vusuariomodificacion;
    private String vusuariocreacion;
    private Date dfechacreacion;
    private Date dfechamodificacion;
    private BigDecimal ntipoconocimientovinc;

    public TvinculoHist() {
    }

    public TvinculoHist(TvinculoHistId id, Thistorial thistorial) {
        this.id = id;
        this.thistorial = thistorial;
    }

    public TvinculoHist(TvinculoHistId id, Thistorial thistorial, BigDecimal nconocimientovinc, String vusuariomodificacion, String vusuariocreacion, Date dfechacreacion, Date dfechamodificacion, BigDecimal ntipoconocimientovinc) {
        this.id = id;
        this.thistorial = thistorial;
        this.nconocimientovinc = nconocimientovinc;
        this.vusuariomodificacion = vusuariomodificacion;
        this.vusuariocreacion = vusuariocreacion;
        this.dfechacreacion = dfechacreacion;
        this.dfechamodificacion = dfechamodificacion;
        this.ntipoconocimientovinc = ntipoconocimientovinc;
    }

    public TvinculoHistId getId() {
        return this.id;
    }

    public void setId(TvinculoHistId id) {
        this.id = id;
    }

    public Thistorial getThistorial() {
        return this.thistorial;
    }

    public void setThistorial(Thistorial thistorial) {
        this.thistorial = thistorial;
    }

    public BigDecimal getNconocimientovinc() {
        return this.nconocimientovinc;
    }

    public void setNconocimientovinc(BigDecimal nconocimientovinc) {
        this.nconocimientovinc = nconocimientovinc;
    }

    public String getVusuariomodificacion() {
        return this.vusuariomodificacion;
    }

    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }

    public String getVusuariocreacion() {
        return this.vusuariocreacion;
    }

    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }

    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    public Date getDfechamodificacion() {
        return dfechamodificacion;
    }

    public void setDfechamodificacion(Date dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }

    public BigDecimal getNtipoconocimientovinc() {
        return ntipoconocimientovinc;
    }

    public void setNtipoconocimientovinc(BigDecimal ntipoconocimientovinc) {
        this.ntipoconocimientovinc = ntipoconocimientovinc;
    }

}
