package pe.gob.mef.gescon.hibernate.domain;
// Generated 06/11/2015 11:03:52 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * TvinculoHistId generated by hbm2java
 */
public class TvinculoHistId implements java.io.Serializable {

    private BigDecimal nvinculohid;
    private BigDecimal nconocimientoid;
    private BigDecimal nhistorialid;

    public TvinculoHistId() {
    }

    public TvinculoHistId(BigDecimal nvinculohid, BigDecimal nconocimientoid, BigDecimal nhistorialid) {
        this.nvinculohid = nvinculohid;
        this.nconocimientoid = nconocimientoid;
        this.nhistorialid = nhistorialid;
    }

    public BigDecimal getNvinculohid() {
        return this.nvinculohid;
    }

    public void setNvinculohid(BigDecimal nvinculohid) {
        this.nvinculohid = nvinculohid;
    }

    public BigDecimal getNconocimientoid() {
        return this.nconocimientoid;
    }

    public void setNconocimientoid(BigDecimal nconocimientoid) {
        this.nconocimientoid = nconocimientoid;
    }

    public BigDecimal getNhistorialid() {
        return this.nhistorialid;
    }

    public void setNhistorialid(BigDecimal nhistorialid) {
        this.nhistorialid = nhistorialid;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof TvinculoHistId)) {
            return false;
        }
        TvinculoHistId castOther = (TvinculoHistId) other;

        return ((this.getNvinculohid() == castOther.getNvinculohid()) || (this.getNvinculohid() != null && castOther.getNvinculohid() != null && this.getNvinculohid().equals(castOther.getNvinculohid())))
                && ((this.getNconocimientoid() == castOther.getNconocimientoid()) || (this.getNconocimientoid() != null && castOther.getNconocimientoid() != null && this.getNconocimientoid().equals(castOther.getNconocimientoid())))
                && ((this.getNhistorialid() == castOther.getNhistorialid()) || (this.getNhistorialid() != null && castOther.getNhistorialid() != null && this.getNhistorialid().equals(castOther.getNhistorialid())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getNvinculohid() == null ? 0 : this.getNvinculohid().hashCode());
        result = 37 * result + (getNconocimientoid() == null ? 0 : this.getNconocimientoid().hashCode());
        result = 37 * result + (getNhistorialid() == null ? 0 : this.getNhistorialid().hashCode());
        return result;
    }

}
