package pe.gob.mef.gescon.hibernate.domain;
// Generated 06/11/2015 11:03:52 AM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Tvinculo generated by hbm2java
 */
public class Tvinculo implements java.io.Serializable {

    private BigDecimal nvinculoid;
    private Tconocimiento tconocimiento;
    private BigDecimal nconocimientovinc;
    private String vusuariomodificacion;
    private Date dfechacreacion;
    private Date dfechamodificacion;
    private String vusuariocreacion;

    public Tvinculo() {
    }

    public Tvinculo(BigDecimal nvinculoid, Tconocimiento tconocimiento) {
        this.nvinculoid = nvinculoid;
        this.tconocimiento = tconocimiento;
    }

    public Tvinculo(BigDecimal nvinculoid, Tconocimiento tconocimiento, BigDecimal nconocimientovinc, String vusuariomodificacion, Date dfechacreacion, Date dfechamodificacion, String vusuariocreacion) {
        this.nvinculoid = nvinculoid;
        this.tconocimiento = tconocimiento;
        this.nconocimientovinc = nconocimientovinc;
        this.vusuariomodificacion = vusuariomodificacion;
        this.dfechacreacion = dfechacreacion;
        this.dfechamodificacion = dfechamodificacion;
        this.vusuariocreacion = vusuariocreacion;
    }

    public BigDecimal getNvinculoid() {
        return this.nvinculoid;
    }

    public void setNvinculoid(BigDecimal nvinculoid) {
        this.nvinculoid = nvinculoid;
    }

    public Tconocimiento getTconocimiento() {
        return this.tconocimiento;
    }

    public void setTconocimiento(Tconocimiento tconocimiento) {
        this.tconocimiento = tconocimiento;
    }

    public BigDecimal getNconocimientovinc() {
        return this.nconocimientovinc;
    }

    public void setNconocimientovinc(BigDecimal nconocimientovinc) {
        this.nconocimientovinc = nconocimientovinc;
    }

    public String getVusuariomodificacion() {
        return this.vusuariomodificacion;
    }

    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }

    public Serializable getDfechacreacion() {
        return this.dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    public Serializable getDfechamodificacion() {
        return this.dfechamodificacion;
    }

    public void setDfechamodificacion(Date dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }

    public String getVusuariocreacion() {
        return this.vusuariocreacion;
    }

    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }

}
