package pe.gob.mef.gescon.hibernate.domain;
// Generated 11/09/2015 05:20:07 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TvinculoId generated by hbm2java
 */
public class TvinculoId  implements java.io.Serializable {


     private BigDecimal nvinculoid;
     private BigDecimal nconocimientoid;
     private BigDecimal ntpoconocimientoid;

    public TvinculoId() {
    }

    public TvinculoId(BigDecimal nvinculoid, BigDecimal nconocimientoid, BigDecimal ntpoconocimientoid) {
       this.nvinculoid = nvinculoid;
       this.nconocimientoid = nconocimientoid;
       this.ntpoconocimientoid = ntpoconocimientoid;
    }
   
    public BigDecimal getNvinculoid() {
        return this.nvinculoid;
    }
    
    public void setNvinculoid(BigDecimal nvinculoid) {
        this.nvinculoid = nvinculoid;
    }
    public BigDecimal getNconocimientoid() {
        return this.nconocimientoid;
    }
    
    public void setNconocimientoid(BigDecimal nconocimientoid) {
        this.nconocimientoid = nconocimientoid;
    }
    public BigDecimal getNtpoconocimientoid() {
        return this.ntpoconocimientoid;
    }
    
    public void setNtpoconocimientoid(BigDecimal ntpoconocimientoid) {
        this.ntpoconocimientoid = ntpoconocimientoid;
    }




}


