package pe.gob.mef.gescon.hibernate.domain;
// Generated 28/12/2015 01:39:52 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TvinculoBaselegalHist generated by hbm2java
 */
public class TvinculoBaselegalHist implements java.io.Serializable {

    private BigDecimal nvinculohistid;
    private BigDecimal nhistorialid;
    private BigDecimal nbaselegalid;
    private BigDecimal nbaselegalvinculadaid;
    private BigDecimal ntipovinculo;
    private String vusuariocreacion;
    private Date dfechacreacion;
    private String vusuariomodificacion;
    private Date dfechamodificacion;

    public TvinculoBaselegalHist() {
    }

    public TvinculoBaselegalHist(BigDecimal nvinculohistid) {
        this.nvinculohistid = nvinculohistid;
    }

    public TvinculoBaselegalHist(BigDecimal nvinculohistid, BigDecimal nhistorialid, BigDecimal nbaselegalid, BigDecimal nbaselegalvinculadaid, BigDecimal ntipovinculo, String vusuariocreacion, Date dfechacreacion, String vusuariomodificacion, Date dfechamodificacion) {
        this.nvinculohistid = nvinculohistid;
        this.nhistorialid = nhistorialid;
        this.nbaselegalid = nbaselegalid;
        this.nbaselegalvinculadaid = nbaselegalvinculadaid;
        this.ntipovinculo = ntipovinculo;
        this.vusuariocreacion = vusuariocreacion;
        this.dfechacreacion = dfechacreacion;
        this.vusuariomodificacion = vusuariomodificacion;
        this.dfechamodificacion = dfechamodificacion;
    }

    public BigDecimal getNvinculohistid() {
        return this.nvinculohistid;
    }

    public void setNvinculohistid(BigDecimal nvinculohistid) {
        this.nvinculohistid = nvinculohistid;
    }

    public BigDecimal getNhistorialid() {
        return this.nhistorialid;
    }

    public void setNhistorialid(BigDecimal nhistorialid) {
        this.nhistorialid = nhistorialid;
    }

    public BigDecimal getNbaselegalid() {
        return this.nbaselegalid;
    }

    public void setNbaselegalid(BigDecimal nbaselegalid) {
        this.nbaselegalid = nbaselegalid;
    }

    public BigDecimal getNbaselegalvinculadaid() {
        return this.nbaselegalvinculadaid;
    }

    public void setNbaselegalvinculadaid(BigDecimal nbaselegalvinculadaid) {
        this.nbaselegalvinculadaid = nbaselegalvinculadaid;
    }

    public BigDecimal getNtipovinculo() {
        return this.ntipovinculo;
    }

    public void setNtipovinculo(BigDecimal ntipovinculo) {
        this.ntipovinculo = ntipovinculo;
    }

    public String getVusuariocreacion() {
        return this.vusuariocreacion;
    }

    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }

    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    public String getVusuariomodificacion() {
        return this.vusuariomodificacion;
    }

    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }

    public Date getDfechamodificacion() {
        return this.dfechamodificacion;
    }

    public void setDfechamodificacion(Date dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }

}
