package pe.gob.mef.gescon.hibernate.domain;
// Generated 06/11/2015 11:03:52 AM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * TvinculoImplementacion generated by hbm2java
 */
public class TvinculoImplementacion implements java.io.Serializable {

    private BigDecimal nimplvinculoid;
    private BigDecimal nimplementacionid;
    private String vusuariocreacion;
    private Date dfechacreacion;
    private String vusuariomodificacion;
    private Date dfechamodificacion;
    private BigDecimal nconocimientovinc;

    public TvinculoImplementacion() {
    }

    public TvinculoImplementacion(BigDecimal nimplvinculoid) {
        this.nimplvinculoid = nimplvinculoid;
    }

    public TvinculoImplementacion(BigDecimal nimplvinculoid, BigDecimal nimplementacionid, String vusuariocreacion, Date dfechacreacion, String vusuariomodificacion, Date dfechamodificacion, BigDecimal nconocimientovinc) {
        this.nimplvinculoid = nimplvinculoid;
        this.nimplementacionid = nimplementacionid;
        this.vusuariocreacion = vusuariocreacion;
        this.dfechacreacion = dfechacreacion;
        this.vusuariomodificacion = vusuariomodificacion;
        this.dfechamodificacion = dfechamodificacion;
        this.nconocimientovinc = nconocimientovinc;
    }

    public BigDecimal getNimplvinculoid() {
        return this.nimplvinculoid;
    }

    public void setNimplvinculoid(BigDecimal nimplvinculoid) {
        this.nimplvinculoid = nimplvinculoid;
    }

    public BigDecimal getNimplementacionid() {
        return this.nimplementacionid;
    }

    public void setNimplementacionid(BigDecimal nimplementacionid) {
        this.nimplementacionid = nimplementacionid;
    }

    public String getVusuariocreacion() {
        return this.vusuariocreacion;
    }

    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }

    public Serializable getDfechacreacion() {
        return this.dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    public String getVusuariomodificacion() {
        return this.vusuariomodificacion;
    }

    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }

    public Serializable getDfechamodificacion() {
        return this.dfechamodificacion;
    }

    public void setDfechamodificacion(Date dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }

    public BigDecimal getNconocimientovinc() {
        return this.nconocimientovinc;
    }

    public void setNconocimientovinc(BigDecimal nconocimientovinc) {
        this.nconocimientovinc = nconocimientovinc;
    }

}
