package pe.gob.mef.gescon.hibernate.domain;
// Generated 06/11/2015 11:03:52 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TvinculoHist generated by hbm2java
 */
public class TvinculoHist implements java.io.Serializable {

    private TvinculoHistId id;
    private Thistorial thistorial;
    private BigDecimal nconocimientovinc;
    private BigDecimal nusuariomod;
    private BigDecimal nusuariocreacion;
    private Date dfechacreacion;

    public TvinculoHist() {
    }

    public TvinculoHist(TvinculoHistId id, Thistorial thistorial) {
        this.id = id;
        this.thistorial = thistorial;
    }

    public TvinculoHist(TvinculoHistId id, Thistorial thistorial, BigDecimal nconocimientovinc, BigDecimal nusuariomod, BigDecimal nusuariocreacion, Date dfechacreacion) {
        this.id = id;
        this.thistorial = thistorial;
        this.nconocimientovinc = nconocimientovinc;
        this.nusuariomod = nusuariomod;
        this.nusuariocreacion = nusuariocreacion;
        this.dfechacreacion = dfechacreacion;
    }

    public TvinculoHistId getId() {
        return this.id;
    }

    public void setId(TvinculoHistId id) {
        this.id = id;
    }

    public Thistorial getThistorial() {
        return this.thistorial;
    }

    public void setThistorial(Thistorial thistorial) {
        this.thistorial = thistorial;
    }

    public BigDecimal getNconocimientovinc() {
        return this.nconocimientovinc;
    }

    public void setNconocimientovinc(BigDecimal nconocimientovinc) {
        this.nconocimientovinc = nconocimientovinc;
    }

    public BigDecimal getNusuariomod() {
        return this.nusuariomod;
    }

    public void setNusuariomod(BigDecimal nusuariomod) {
        this.nusuariomod = nusuariomod;
    }

    public BigDecimal getNusuariocreacion() {
        return this.nusuariocreacion;
    }

    public void setNusuariocreacion(BigDecimal nusuariocreacion) {
        this.nusuariocreacion = nusuariocreacion;
    }

    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

}
