package pe.gob.mef.gescon.hibernate.domain;
// Generated 11/09/2015 05:20:07 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * TvincHist generated by hbm2java
 */
public class TvincHist  implements java.io.Serializable {


     private TvincHistId id;
     private BigDecimal nconocimientovinc;
     private BigDecimal nusuariomod;
     private BigDecimal nusuariocreacion;
     private Date dfechacreacion;

    public TvincHist() {
    }

	
    public TvincHist(TvincHistId id) {
        this.id = id;
    }
    public TvincHist(TvincHistId id, BigDecimal nconocimientovinc, BigDecimal nusuariomod, BigDecimal nusuariocreacion, Date dfechacreacion) {
       this.id = id;
       this.nconocimientovinc = nconocimientovinc;
       this.nusuariomod = nusuariomod;
       this.nusuariocreacion = nusuariocreacion;
       this.dfechacreacion = dfechacreacion;
    }
   
    public TvincHistId getId() {
        return this.id;
    }
    
    public void setId(TvincHistId id) {
        this.id = id;
    }
    public BigDecimal getNconocimientovinc() {
        return this.nconocimientovinc;
    }
    
    public void setNconocimientovinc(BigDecimal nconocimientovinc) {
        this.nconocimientovinc = nconocimientovinc;
    }
    public BigDecimal getNusuariomod() {
        return this.nusuariomod;
    }
    
    public void setNusuariomod(BigDecimal nusuariomod) {
        this.nusuariomod = nusuariomod;
    }
    public BigDecimal getNusuariocreacion() {
        return this.nusuariocreacion;
    }
    
    public void setNusuariocreacion(BigDecimal nusuariocreacion) {
        this.nusuariocreacion = nusuariocreacion;
    }
    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }
    
    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }




}


