package pe.gob.mef.gescon.hibernate.domain;
// Generated 27/10/2015 06:08:09 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;

/**
 * TvinculoImplementacion generated by hbm2java
 */
public class TvinculoImplementacion  implements java.io.Serializable {


     private BigDecimal nimplvinculoid;
     private Timplementacion timplementacion;
     private BigDecimal nconocimientovinc;
     private BigDecimal vusuariocreacion;
     private BigDecimal vusuariomodificacion;
     private Serializable dfechacreacion;
     private Serializable dfechamodificacion;
     private BigDecimal nconocimientoid;

    public TvinculoImplementacion() {
    }

	
    public TvinculoImplementacion(BigDecimal nimplvinculoid, Timplementacion timplementacion, BigDecimal nconocimientoid) {
        this.nimplvinculoid = nimplvinculoid;
        this.timplementacion = timplementacion;
        this.nconocimientoid = nconocimientoid;
    }
    public TvinculoImplementacion(BigDecimal nimplvinculoid, Timplementacion timplementacion, BigDecimal nconocimientovinc, BigDecimal vusuariocreacion, BigDecimal vusuariomodificacion, Serializable dfechacreacion, Serializable dfechamodificacion, BigDecimal nconocimientoid) {
       this.nimplvinculoid = nimplvinculoid;
       this.timplementacion = timplementacion;
       this.nconocimientovinc = nconocimientovinc;
       this.vusuariocreacion = vusuariocreacion;
       this.vusuariomodificacion = vusuariomodificacion;
       this.dfechacreacion = dfechacreacion;
       this.dfechamodificacion = dfechamodificacion;
       this.nconocimientoid = nconocimientoid;
    }
   
    public BigDecimal getNimplvinculoid() {
        return this.nimplvinculoid;
    }
    
    public void setNimplvinculoid(BigDecimal nimplvinculoid) {
        this.nimplvinculoid = nimplvinculoid;
    }
    public Timplementacion getTimplementacion() {
        return this.timplementacion;
    }
    
    public void setTimplementacion(Timplementacion timplementacion) {
        this.timplementacion = timplementacion;
    }
    public BigDecimal getNconocimientovinc() {
        return this.nconocimientovinc;
    }
    
    public void setNconocimientovinc(BigDecimal nconocimientovinc) {
        this.nconocimientovinc = nconocimientovinc;
    }
    public BigDecimal getVusuariocreacion() {
        return this.vusuariocreacion;
    }
    
    public void setVusuariocreacion(BigDecimal vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }
    public BigDecimal getVusuariomodificacion() {
        return this.vusuariomodificacion;
    }
    
    public void setVusuariomodificacion(BigDecimal vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }
    public Serializable getDfechacreacion() {
        return this.dfechacreacion;
    }
    
    public void setDfechacreacion(Serializable dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }
    public Serializable getDfechamodificacion() {
        return this.dfechamodificacion;
    }
    
    public void setDfechamodificacion(Serializable dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }
    public BigDecimal getNconocimientoid() {
        return this.nconocimientoid;
    }
    
    public void setNconocimientoid(BigDecimal nconocimientoid) {
        this.nconocimientoid = nconocimientoid;
    }




}


