package pe.gob.mef.gescon.hibernate.domain;
// Generated 06/11/2015 11:03:52 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Tvinculo generated by hbm2java
 */
public class Tvinculo implements java.io.Serializable {

    private BigDecimal nvinculoid;
    private BigDecimal nconocimientoid;
    private BigDecimal nconocimientovinc;
    private BigDecimal ntipoconocimientovinc;
    private String vusuariomodificacion;
    private Date dfechacreacion;
    private Date dfechamodificacion;
    private String vusuariocreacion;

    public Tvinculo() {
    }

    public Tvinculo(BigDecimal nvinculoid) {
        this.nvinculoid = nvinculoid;
    }

    public Tvinculo(BigDecimal nvinculoid, BigDecimal nconocimientoid, BigDecimal nconocimientovinc, BigDecimal ntipoconocimientovinc, String vusuariomodificacion, Date dfechacreacion, Date dfechamodificacion, String vusuariocreacion) {
        this.nvinculoid = nvinculoid;
        this.nconocimientoid = nconocimientoid;
        this.nconocimientovinc = nconocimientovinc;
        this.ntipoconocimientovinc = ntipoconocimientovinc;
        this.vusuariomodificacion = vusuariomodificacion;
        this.dfechacreacion = dfechacreacion;
        this.dfechamodificacion = dfechamodificacion;
        this.vusuariocreacion = vusuariocreacion;
    }

    public BigDecimal getNvinculoid() {
        return this.nvinculoid;
    }

    public void setNvinculoid(BigDecimal nvinculoid) {
        this.nvinculoid = nvinculoid;
    }

    public BigDecimal getNconocimientoid() {
        return this.nconocimientoid;
    }

    public void setNconocimientoid(BigDecimal nconocimientoid) {
        this.nconocimientoid = nconocimientoid;
    }

    public BigDecimal getNconocimientovinc() {
        return this.nconocimientovinc;
    }

    public void setNconocimientovinc(BigDecimal nconocimientovinc) {
        this.nconocimientovinc = nconocimientovinc;
    }

    public BigDecimal getNtipoconocimientovinc() {
        return ntipoconocimientovinc;
    }

    public void setNtipoconocimientovinc(BigDecimal ntipoconocimientovinc) {
        this.ntipoconocimientovinc = ntipoconocimientovinc;
    }

    public String getVusuariomodificacion() {
        return this.vusuariomodificacion;
    }

    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }

    public Date getDfechacreacion() {
        return this.dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    public Date getDfechamodificacion() {
        return this.dfechamodificacion;
    }

    public void setDfechamodificacion(Date dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }

    public String getVusuariocreacion() {
        return this.vusuariocreacion;
    }

    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }

}
