/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.gob.mef.gescon.web.bean;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Tconocimiento generated by hbm2java
 */
public class Conocimiento  implements Serializable {

    private BigDecimal nconocimientoid;
    private BigDecimal ncategoriaid;
    private BigDecimal nsituacionid;
    private BigDecimal ntipoconocimientoid;
    private String vdescripcion;
    private String vtitulo;
    private String vusuariomodificacion;
    private String vusuariocreacion;
    private Date dfechacreacion;
    private String vruta;
    private String vnumero;
    private String vtema;
    private String vcontenido;
    private BigDecimal ndias;
    private BigDecimal nactivo;
    private String vobservacion;
    private Date dfechamodificacion;
    private BigDecimal ndestacado;
    private Date dfechapublicacion;
    private String vmsjsolicita;
    private String vmsjrespuesta;
    private BigDecimal nflgvinculo;

    public Conocimiento() {
    }

    public BigDecimal getNconocimientoid() {
        return nconocimientoid;
    }

    public void setNconocimientoid(BigDecimal nconocimientoid) {
        this.nconocimientoid = nconocimientoid;
    }

    public BigDecimal getNcategoriaid() {
        return ncategoriaid;
    }

    public void setNcategoriaid(BigDecimal ncategoriaid) {
        this.ncategoriaid = ncategoriaid;
    }

    public BigDecimal getNsituacionid() {
        return nsituacionid;
    }

    public void setNsituacionid(BigDecimal nsituacionid) {
        this.nsituacionid = nsituacionid;
    }

    public BigDecimal getNtipoconocimientoid() {
        return ntipoconocimientoid;
    }

    public void setNtipoconocimientoid(BigDecimal ntipoconocimientoid) {
        this.ntipoconocimientoid = ntipoconocimientoid;
    }

    public String getVdescripcion() {
        return vdescripcion;
    }

    public void setVdescripcion(String vdescripcion) {
        this.vdescripcion = vdescripcion;
    }

    public String getVtitulo() {
        return vtitulo;
    }

    public void setVtitulo(String vtitulo) {
        this.vtitulo = vtitulo;
    }

    public String getVusuariomodificacion() {
        return vusuariomodificacion;
    }

    public void setVusuariomodificacion(String vusuariomodificacion) {
        this.vusuariomodificacion = vusuariomodificacion;
    }

    public String getVusuariocreacion() {
        return vusuariocreacion;
    }

    public void setVusuariocreacion(String vusuariocreacion) {
        this.vusuariocreacion = vusuariocreacion;
    }

    public Date getDfechacreacion() {
        return dfechacreacion;
    }

    public void setDfechacreacion(Date dfechacreacion) {
        this.dfechacreacion = dfechacreacion;
    }

    public String getVruta() {
        return vruta;
    }

    public void setVruta(String vruta) {
        this.vruta = vruta;
    }

    public String getVnumero() {
        return vnumero;
    }

    public void setVnumero(String vnumero) {
        this.vnumero = vnumero;
    }

    public String getVtema() {
        return vtema;
    }

    public void setVtema(String vtema) {
        this.vtema = vtema;
    }

    public String getVcontenido() {
        return vcontenido;
    }

    public void setVcontenido(String vcontenido) {
        this.vcontenido = vcontenido;
    }

    public BigDecimal getNdias() {
        return ndias;
    }

    public void setNdias(BigDecimal ndias) {
        this.ndias = ndias;
    }

    public BigDecimal getNactivo() {
        return nactivo;
    }

    public void setNactivo(BigDecimal nactivo) {
        this.nactivo = nactivo;
    }

    public String getVobservacion() {
        return vobservacion;
    }

    public void setVobservacion(String vobservacion) {
        this.vobservacion = vobservacion;
    }

    public Date getDfechamodificacion() {
        return dfechamodificacion;
    }

    public void setDfechamodificacion(Date dfechamodificacion) {
        this.dfechamodificacion = dfechamodificacion;
    }

    public BigDecimal getNdestacado() {
        return ndestacado;
    }

    public void setNdestacado(BigDecimal ndestacado) {
        this.ndestacado = ndestacado;
    }

    public Date getDfechapublicacion() {
        return dfechapublicacion;
    }

    public void setDfechapublicacion(Date dfechapublicacion) {
        this.dfechapublicacion = dfechapublicacion;
    }

    /**
     * @return the vmsjsolicita
     */
    public String getVmsjsolicita() {
        return vmsjsolicita;
    }

    /**
     * @param vmsjsolicita the vmsjsolicita to set
     */
    public void setVmsjsolicita(String vmsjsolicita) {
        this.vmsjsolicita = vmsjsolicita;
    }

    /**
     * @return the vmsjrespuesta
     */
    public String getVmsjrespuesta() {
        return vmsjrespuesta;
    }

    /**
     * @param vmsjrespuesta the vmsjrespuesta to set
     */
    public void setVmsjrespuesta(String vmsjrespuesta) {
        this.vmsjrespuesta = vmsjrespuesta;
    }

    public BigDecimal getNflgvinculo() {
        return nflgvinculo;
    }

    public void setNflgvinculo(BigDecimal nflgvinculo) {
        this.nflgvinculo = nflgvinculo;
    }
}
